1020 - Update the code to add the aria-label property to the modus-modal's both buttons
trimble-oss/modus-web-components pull request #1032
Opened 2023-02-20 10:40 UTC by hrgondaliya

Update the code to add the aria-label property to the modus-modal's both buttons

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (including CHANGELOG updates)
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

2023-02-20 10:42 UTC, msankaran0712 requested changes
We also need to change the properties for the Modal component on the storybook page.

2023-02-20 10:43 UTC, msankaran0712 requested changes

2023-02-20 10:43 UTC, msankaran0712 commented on stencil-workspace/src/components.d.ts
> +        "secondaryButtonAreaLabel": string | null;
I believe it should read  `..AriaLabel`

2023-02-20 10:50 UTC, msankaran0712 commented
It would be nice to have something like https://shoelace.style/components/dialog?id=slots for the footer section as optional, what do you think? @ryan-henness-trimble

2023-02-20 10:53 UTC, msankaran0712 requested changes

2023-02-20 10:53 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-modal/modus-modal.tsx
> +  @Prop() primaryButtonAreaLabel: string | null;
I believe it should read ..AriaLabel, also in the description text.

2023-02-20 10:57 UTC, msankaran0712 requested changes

2023-02-20 10:57 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-modal/modus-modal.tsx
> +  @Prop() secondaryButtonAreaLabel: string | null;
I believe it is sufficient to use only `string` for prop type @ryan-henness-trimble please correct me if am wrong.

2023-02-21 07:40 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-modal/modus-modal.tsx
> +  @Prop() secondaryButtonAreaLabel: string | null;
I recommend keeping only `string`.

2023-02-21 17:12 UTC, ryan-henness-trimble commented on stencil-workspace/src/components/modus-modal/modus-modal.tsx
> +  @Prop() secondaryButtonAreaLabel: string | null;
If I remember correctly, the Storybook accessibility checks were not passing unless we included `null`

2023-02-21 17:25 UTC, ryan-henness-trimble commented on stencil-workspace/src/components/modus-modal/modus-modal.tsx
> +  /** (optional) The modal's primary button Aria label. */
Can we change `Aria label` to `aria-label` in the comments?

2023-02-21 17:25 UTC, ryan-henness-trimble commented on stencil-workspace/src/components/modus-modal/modus-modal.tsx
> +  @Prop() secondaryButtonAriaLabel: string | null;
Let's alphasort these `@Prop()`s - that way they're next to their corresponding `ButtonText` prop

2023-02-21 17:29 UTC, ryan-henness-trimble commented
> It would be nice to have something like https://shoelace.style/components/dialog?id=slots for the footer section as optional, any thoughts? @ryan-henness-trimble

It depends on the Modus spec, do we want to allow the user to add more than 3 buttons? Do we want them to be able to render elements in the footer other than buttons?

2023-02-21 21:30 UTC, ryan-henness-trimble approved these changes

2023-02-22 05:38 UTC, msankaran0712 commented
> > It would be nice to have something like https://shoelace.style/components/dialog?id=slots for the footer section as optional, any thoughts? @ryan-henness-trimble
> 
> It depends on how rigid we want to adhere to the Modus specs. Do we want to allow the dev to add more than two buttons? Do we want them to be able to render elements other than buttons in the footer?
> 
> If we want to give them full control, a slot sounds like a good option. But if we want to limit what can be rendered in the footer, we might want to consider another option
> 
> I would lean towards adding optional slots that will override the default buttons. More control seems better in this case

@ryan-henness-trimble I agree to have optional slots for buttons. It is true that users should not add buttons more than two, but providing a slot as an option will give users better control over the button configurations instead of adding those configs in the Modal's API, which in the future might become too much.

2023-02-22 06:14 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-modal/modus-modal.tsx
> +  @Prop() secondaryButtonAreaLabel: string | null;
hey, @ryan-henness-trimble @hrgondaliya I tested the storybook page by removing `null` from the properties and keeping only `string` as a type, seems like there is no issue with accessibility, so up to you to decide whether to remove `null` or keep it.

2023-02-23 16:51 UTC, merged