Dev/ankurkoul/data table sorting
trimble-oss/modus-web-components pull request #1156
Opened 2023-04-11 09:40 UTC by Ankur-Koul

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (including CHANGELOG updates)
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

2023-04-17 08:52 UTC, Ankur-Koul commented on stencil-workspace/src/components/modus-data-table/modus-data-table.tsx
>  import { ModusTableDisplayOptions } from '../modus-table/modus-table.models';
Created new interface under modus-data-table.

2023-04-17 08:53 UTC, Ankur-Koul commented on stencil-workspace/src/components/modus-data-table/modus-data-table.tsx
>                })}
Done.

2023-04-17 10:03 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-data-table/modus-data-table.tsx
>    @Prop({ mutable: true }) columnHeaders!: ModusDataTableColumn[];
can we rename `columnHeaders` to just `columns` ? it might give the impression that it has only the header-specific details.

2023-04-17 10:25 UTC, msankaran0712 commented on stencil-workspace/storybook/stories/components/modus-data-table/modus-data-table.stories.tsx
>      <modus-data-table />
In the file `modus-data-table-storybook-docs.mdx` - line 17, should increase the height px.

2023-04-17 10:40 UTC, msankaran0712 commented on stencil-workspace/storybook/stories/components/modus-data-table/modus-data-table.stories.tsx
>      document.querySelector('modus-data-table').data = [{ firstName: 'Gordon', lastName: 'Lemke', age: 40, visits: 434, progress: 97, status: 'single', createdAt: '2002-11-21T12:48:51.739Z', }, { firs
Line 7: users should be able to pass arguments, ex: please refer to `argTypes` prop in `modus-alert.stories.tsx`

2023-04-17 10:43 UTC, msankaran0712 commented on stencil-workspace/storybook/stories/components/modus-data-table/modus-data-table.stories.tsx
> +export const SortingOnHover = () => html`
I think it is sufficient to have only one example for sorting, and if users want to test sorting on hover, they can use arguments to change the value `showSortIconOnHover`

2023-04-17 10:48 UTC, msankaran0712 commented on stencil-workspace/storybook/stories/components/modus-data-table/modus-data-table.stories.tsx
> +    document.querySelector('modus-data-table').hover = true;
simple data types like booleans and integers can be passed as strings too so we can add them in the HTML directly and reuse the script that initialises data and column definitions.

2023-04-17 11:12 UTC, msankaran0712 commented on stencil-workspace/storybook/stories/components/modus-data-table/modus-data-table.stories.tsx
>      document.querySelector('modus-data-table').displayOptions = { borderless: true, cellBorderless: true }
script functions return a string so try to reuse and create new ones only to include additional code

2023-04-17 11:38 UTC, msankaran0712 requested changes

2023-04-17 11:38 UTC, msankaran0712 commented on stencil-workspace/storybook/stories/components/modus-data-table/modus-data-table.stories.tsx
>  export const Hover = () => html`
similar to `<Story id="components-data-table--default" height={'250px'} />` please show other examples on `Docs` page too

2023-04-17 11:38 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-data-table/modus-data-table.tsx
>    options: TableOptionsResolved<unknown> = {
Please keep only the declaration here and move the object initialization to the `componentWillLoad` method https://stenciljs.com/docs/component-lifecycle#componentwillload

2023-04-17 11:38 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-data-table/modus-data-table.tsx
>    table: Table<unknown> = createTable(this.options);
I think `table` should be a State variable

2023-04-17 11:38 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-data-table/modus-data-table.tsx
>    @Prop({ mutable: true }) data!: unknown[];
Needs a watch handler to update table instance on change

2023-04-17 11:38 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-data-table/modus-data-table.tsx
>    @Prop({ mutable: true }) columnHeaders!: ModusDataTableColumn[];
Needs a watch handler to update table instance on change

2023-04-17 11:47 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-data-table/modus-data-table.tsx
>    table: Table<unknown> = createTable(this.options);
A State variable will automatically re-render the component on change

2023-04-17 12:10 UTC, msankaran0712 requested changes

2023-04-18 07:15 UTC, Ankur-Koul commented on stencil-workspace/src/components/modus-data-table/modus-data-table.tsx
>    @Prop({ mutable: true }) columnHeaders!: ModusDataTableColumn[];
Changed.

2023-04-18 07:15 UTC, Ankur-Koul commented on stencil-workspace/storybook/stories/components/modus-data-table/modus-data-table.stories.tsx
>      <modus-data-table />
Element is not taking the height, so removed 1 data row to fit.

2023-04-18 07:15 UTC, Ankur-Koul commented on stencil-workspace/storybook/stories/components/modus-data-table/modus-data-table.stories.tsx
>      document.querySelector('modus-data-table').columnHeaders = [{ header: 'First Name', accessorKey: 'firstName', id: 'first-name', dataType: 'text', }, { header: 'Last Name', accessorKey: 'lastName'
Done

2023-04-18 07:15 UTC, Ankur-Koul commented on stencil-workspace/storybook/stories/components/modus-data-table/modus-data-table.stories.tsx
> +export const SortingOnHover = () => html`
Removed

2023-04-18 07:21 UTC, Ankur-Koul commented on stencil-workspace/storybook/stories/components/modus-data-table/modus-data-table.stories.tsx
> +    document.querySelector('modus-data-table').hover = true;
Changed to inline code.

2023-04-18 07:21 UTC, Ankur-Koul commented on stencil-workspace/src/components/modus-data-table/modus-data-table.tsx
>    options: TableOptionsResolved<unknown> = {
Done

2023-04-18 07:21 UTC, Ankur-Koul commented on stencil-workspace/src/components/modus-data-table/modus-data-table.tsx
>    table: Table<unknown> = createTable(this.options);
Done

2023-04-18 07:21 UTC, Ankur-Koul commented on stencil-workspace/src/components/modus-data-table/modus-data-table.tsx
>    @Prop({ mutable: true }) data!: unknown[];
Added a watch function

2023-04-18 07:22 UTC, Ankur-Koul commented on stencil-workspace/src/components/modus-data-table/modus-data-table.tsx
>    @Prop({ mutable: true }) columnHeaders!: ModusDataTableColumn[];
Added a watch function

2023-04-18 07:22 UTC, Ankur-Koul commented on stencil-workspace/src/components/modus-data-table/modus-data-table.tsx
> +  @Event() sorting: EventEmitter<SortingState>;
Done

2023-04-18 07:22 UTC, Ankur-Koul commented on stencil-workspace/src/components/modus-data-table/modus-data-table.tsx
> +  @Prop() canSort = false;
Done

2023-04-18 10:00 UTC, msankaran0712 requested changes

2023-04-18 10:00 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-data-table/parts/modus-data-table-header.tsx
> +          {props.header.column.getCanSort() ? (
can you move sort icon into a separate render function like https://codesandbox.io/s/dry-fog-42qisy?file=/src/data-table.ts

2023-04-18 13:54 UTC, Ankur-Koul commented on stencil-workspace/storybook/stories/components/modus-data-table/modus-data-table.stories.tsx
Made some changes, please check.

2023-04-18 13:54 UTC, Ankur-Koul commented on stencil-workspace/storybook/stories/components/modus-data-table/modus-data-table.stories.tsx
>  export const Hover = () => html`
Added

2023-04-18 13:55 UTC, Ankur-Koul commented on stencil-workspace/storybook/stories/components/modus-data-table/modus-data-table.stories.tsx
>      document.querySelector('modus-data-table').displayOptions = { borderless: true, cellBorderless: true }
Will look into this later

2023-04-18 13:56 UTC, Ankur-Koul commented on stencil-workspace/storybook/stories/components/modus-data-table/modus-data-table.stories.tsx
>      document.querySelector('modus-data-table').data = [{ firstName: 'Gordon', lastName: 'Lemke', age: 40, visits: 434, progress: 97, status: 'single', createdAt: '2002-11-21T12:48:51.739Z', }, { firs
done

2023-04-18 14:43 UTC, msankaran0712 requested changes

2023-04-18 14:43 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-data-table/modus-data-table.tsx
> +  /** (Optional) To display border data in table. */
hey @Ankur-Koul it still reads "To display border data in table."

2023-04-18 14:43 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-data-table/modus-data-table.tsx
> +    const options: TableOptionsResolved<unknown> = {
please move this block to a function something like 'initializeTable'

2023-04-18 14:43 UTC, msankaran0712 commented on stencil-workspace/storybook/stories/components/modus-data-table/modus-data-table.stories.tsx
hey @Ankur-Koul I was asking for something like https://modus-web-components.trimble.com/?path=/docs/user-inputs-time-picker--default#properties

2023-04-18 14:49 UTC, msankaran0712 commented
Good Job @Ankur-Koul !!. A few more comments and we are almost done.

2023-04-19 05:03 UTC, Ankur-Koul commented on stencil-workspace/src/components/modus-data-table/parts/modus-data-table-header.tsx
> +          {props.header.column.getCanSort() ? (
Moded

2023-04-19 05:26 UTC, Ankur-Koul commented on stencil-workspace/src/components/modus-data-table/modus-data-table.tsx
> +    const options: TableOptionsResolved<unknown> = {
Moved.

2023-04-19 05:59 UTC, Ankur-Koul commented on stencil-workspace/storybook/stories/components/modus-data-table/modus-data-table.stories.tsx
Done

2023-04-19 06:05 UTC, Ankur-Koul commented on stencil-workspace/storybook/stories/components/modus-data-table/modus-data-table.stories.tsx
> +    <modus-data-table hover="{true}" />
Chnaged

2023-04-19 10:44 UTC, msankaran0712 approved these changes

2023-04-19 10:45 UTC, merged