Table column resizing development
trimble-oss/modus-web-components pull request #1210
Opened 2023-04-21 06:01 UTC by sankarNous

## Description

Table column resizing development.

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (including CHANGELOG updates)
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

2023-04-21 09:06 UTC, Ankur-Koul commented on stencil-workspace/src/components/modus-data-table/modus-data-table.scss
> +.resizer {
Please provide/use classes with respect to the hierarchy.

2023-04-21 09:06 UTC, Ankur-Koul commented on stencil-workspace/src/components/modus-data-table/parts/modus-data-table-cell.tsx
> +          ${props.cell.column.getIsResizing() ? 'is-resizing' : ''}
You can rename this to `can-resize` as `can-sort`, so as to maintain the same naming convention.

2023-04-21 10:04 UTC, sankarNous commented on stencil-workspace/src/components/modus-data-table/modus-data-table.tsx
> +  @State() columnSizing: ColumnSizingState = {};
they using through `updatingState` function

2023-04-21 10:50 UTC, sankarNous commented on stencil-workspace/src/components/modus-data-table/modus-data-table.tsx
> +      onColumnSizingChange: (updater: Updater<ColumnSizingState>) =>
it doesn't have any

2023-04-21 11:05 UTC, sankarNous commented on stencil-workspace/storybook/stories/components/modus-data-table/modus-data-table.stories.tsx
> +    <modus-data-table enable-column-resizing=true/>
done

2023-04-21 11:05 UTC, sankarNous commented on stencil-workspace/storybook/stories/components/modus-data-table/modus-data-table-storybook-docs.mdx
> +### Properties
Have added

2023-04-21 11:06 UTC, sankarNous commented on stencil-workspace/src/components/modus-data-table/modus-data-table.tsx
> +  @Prop() enableColumnResizing = false;
done

2023-04-21 11:06 UTC, sankarNous commented on stencil-workspace/src/components/modus-data-table/modus-data-table.tsx
> +      columnResizeMode: 'onChange',
done

2023-04-21 11:07 UTC, sankarNous commented on stencil-workspace/src/components/modus-data-table/modus-data-table.scss
> +.is-resizing {
Have adjusted in hierarchy

2023-04-21 11:07 UTC, sankarNous commented on stencil-workspace/src/components/modus-data-table/modus-data-table.scss
> +.resizer {
Have adjusted in hierarchy

2023-04-21 11:07 UTC, sankarNous commented on stencil-workspace/src/components/modus-data-table/parts/modus-data-table-cell.tsx
> +          ${props.cell.column.getIsResizing() ? 'is-resizing' : ''}
done

2023-04-27 08:19 UTC, msankaran0712 requested changes

2023-04-27 08:19 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-data-table/parts/modus-data-table-column-resizing-handler.tsx
> +> = (props: ModusDataTableColumnResizingHandlerProps) => {
Please use nested object destructuring for `props`. It should be like `const {header: {column, getResizeHandler}} = props`

2023-04-27 08:19 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-switch/modus-switch.scss
> +      right: 0;
please revert this

2023-04-27 08:19 UTC, msankaran0712 commented on stencil-workspace/storybook/stories/components/modus-data-table/modus-data-table-storybook-docs.mdx
> +# Table
why does it not read Data Table ?

2023-04-27 09:18 UTC, sankarNous commented on stencil-workspace/src/components/modus-data-table/models/modus-data-table-column.ts
> +  enableSorting?: boolean;
we have to set in other way like by default all columns are resizable enable resizing. we can disable for the columns by `enableResizing: false
`![image](https://user-images.githubusercontent.com/57536801/234817876-6e388003-19e3-4118-a435-7f3dc1dd955b.png)

2023-04-27 10:15 UTC, sankarNous commented on stencil-workspace/src/components/modus-data-table/modus-data-table.scss
> +        border-right: 2px solid $modus-table-column-resizing-border-color;
I can't use outline as I can't set an outline for one side, like border-right.

2023-04-27 10:16 UTC, msankaran0712 requested changes

2023-04-27 10:16 UTC, msankaran0712 commented on stencil-workspace/storybook/stories/components/modus-data-table/modus-data-table.stories.tsx
> +  },
I think you should add the arguments for Column resizing here

2023-04-27 10:16 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-data-table/modus-data-table.scss
> +        border-right: 2px solid $modus-table-column-resizing-border-color;
it is done in react, please check there once

2023-05-02 05:41 UTC, sankarNous commented on stencil-workspace/src/components/modus-data-table/modus-data-table.scss
> +        border-right: 2px solid $modus-table-column-resizing-border-color;
I'm closing this as it can't work here.

2023-05-02 05:46 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-data-table/models/modus-data-table-column.ts
> +  enableSorting?: boolean;
-yes please add that in column level too

2023-05-02 06:23 UTC, sankarNous commented on stencil-workspace/src/components/modus-data-table/modus-data-table.tsx
> +        columnPinning: {},
Functionality won't work; we have to define the state beforehand.

2023-05-02 08:12 UTC, msankaran0712 requested changes
The scroll bars were not visible earlier

![image](https://user-images.githubusercontent.com/50131391/235614167-0df973f1-f1dd-45c7-bf16-a8ff93ad8c95.png)

2023-05-02 08:12 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-data-table/parts/modus-data-table-column-resizing-handler.tsx
> +> = (props: ModusDataTableColumnResizingHandlerProps) => {
@sankarNous Please fix this.

2023-05-04 12:03 UTC, msankaran0712 requested changes

2023-05-05 04:49 UTC, msankaran0712 approved these changes

2023-05-05 04:50 UTC, closed without merging