Added summary row for Data Table
trimble-oss/modus-web-components pull request #1221
Opened 2023-04-25 07:00 UTC by Ankur-Koul

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #[1208](https://github.com/trimble-oss/modus-web-components/issues/1208)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [*] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [*] Documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (including CHANGELOG updates)
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

2023-05-08 10:58 UTC, msankaran0712 requested changes

2023-05-08 10:58 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-data-table/modus-data-table.tsx
> +      sortDescFirst: false, // To-Do, this is work around to sort descending by default.
please update the comment, "workaround to prevent sort descending on certain columns, e.g. numeric"

2023-05-08 10:58 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-data-table/modus-data-table.tsx
> +    const rowData: unknown[] = this.table.options.data.map(
how do we validate if a valid column key is passed ?

2023-05-08 10:58 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-data-table/modus-data-table.tsx
> +  // getColumnData(){
Please remove the commented lines for now, if needed you can keep a local copy.

2023-05-08 10:58 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-data-table/modus-data-table.tsx
> +  public getRowDataByCurrentIndex(
please add comments to describe what the method does.

2023-05-08 10:58 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-data-table/modus-data-table.tsx
> +        <slot name="footer"></slot>
please rename it to "custom-footer"

2023-05-08 10:58 UTC, msankaran0712 commented on stencil-workspace/storybook/stories/components/modus-data-table/modus-data-table-storybook-docs.mdx
> +### Summary Row
Needed implementation details about the summary row.

2023-05-08 10:58 UTC, msankaran0712 commented on stencil-workspace/storybook/stories/components/modus-data-table/modus-data-table.stories.tsx
> +export const SummaryRow = () => html`
Looks like sorting and summary examples are having an accessibility issue 
![image](https://user-images.githubusercontent.com/50131391/236804991-dcb2f511-9161-4d10-88e3-dc62c1e9423d.png)

2023-05-08 10:58 UTC, msankaran0712 commented on stencil-workspace/storybook/stories/components/modus-data-table/modus-data-table.stories.tsx
do we have an argument for `summaryrow`  in `argTypes` ?

2023-05-08 11:05 UTC, msankaran0712 commented on stencil-workspace/storybook/stories/components/modus-data-table/modus-data-table-storybook-docs.mdx
> +### Summary Row
If you can add the comments in the format shown in the screenshot, README will automatically pick it up and you can copy paste the slots table under API section in storybook. Example below,
![image](https://user-images.githubusercontent.com/50131391/236808031-142b132f-99e5-4d5f-8c6e-71cf0171a9f4.png)
![image](https://user-images.githubusercontent.com/50131391/236808121-3898df5b-338f-411f-8e2f-9e77c7af8c62.png)

2023-05-08 11:14 UTC, msankaran0712 commented
Please use object destructuring here
![image](https://user-images.githubusercontent.com/50131391/236809827-6eab4d49-d1d9-4a46-b003-14a4361f9224.png)

2023-05-09 06:23 UTC, Ankur-Koul commented on stencil-workspace/storybook/stories/components/modus-data-table/modus-data-table.stories.tsx
Yes

2023-05-09 06:25 UTC, Ankur-Koul commented on stencil-workspace/storybook/stories/components/modus-data-table/modus-data-table-storybook-docs.mdx
> +### Summary Row
Done

2023-05-09 06:25 UTC, Ankur-Koul commented on stencil-workspace/src/components/modus-data-table/modus-data-table.tsx
> +        <slot name="footer"></slot>
Done.

2023-05-09 06:30 UTC, Ankur-Koul commented on stencil-workspace/src/components/modus-data-table/modus-data-table.tsx
> +  public getRowDataByCurrentIndex(
Done

2023-05-09 06:30 UTC, Ankur-Koul commented on stencil-workspace/src/components/modus-data-table/modus-data-table.tsx
> +  // getColumnData(){
Done

2023-05-09 06:30 UTC, Ankur-Koul commented on stencil-workspace/src/components/modus-data-table/modus-data-table.tsx
> +    const rowData: unknown[] = this.table.options.data.map(
If column key is not passed we are returning an empty array.

2023-05-09 06:32 UTC, Ankur-Koul commented on stencil-workspace/src/components/modus-data-table/modus-data-table.tsx
> +      sortDescFirst: false, // To-Do, this is work around to sort descending by default.
Done

2023-05-09 07:32 UTC, Ankur-Koul commented on stencil-workspace/storybook/stories/components/modus-data-table/modus-data-table.stories.tsx
> +export const SummaryRow = () => html`
Resolved.

2023-05-09 10:54 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-data-table/modus-data-table.tsx
> +                  {row.getAllCells()?.map((cell) => {
I think it is right to use `getVisibleCells` before we can hide columns too

2023-05-09 10:54 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-data-table/modus-data-table.tsx
> +  public getRowDataByOriginalIndex(
for `getRowDataByCurrentIndex` and `getRowDataByOriginalIndex`, did you find any use cases?

2023-05-09 10:54 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-data-table/parts/modus-data-table-header.tsx
> +      {header.isPlaceholder ? null : (
not clear why we need a header placeholder, is it passed by the user?

2023-05-09 10:54 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-data-table/modus-data-table.tsx
> +    const rowData: unknown[] = this.table.options.data.map(
as we discussed, we need to eliminate the unnecessary iteration if the accessor key is invalid.

2023-05-09 11:17 UTC, msankaran0712 commented on stencil-workspace/storybook/stories/components/modus-data-table/modus-data-table.stories.tsx
It does not reflect here
![image](https://github.com/trimble-oss/modus-web-components/assets/50131391/5e7bbe7d-1876-4787-89f8-05ec6bada2f4)

2023-05-09 11:19 UTC, msankaran0712 requested changes
Please check the unresolved comments

2023-05-09 11:21 UTC, Ankur-Koul commented on stencil-workspace/src/components/modus-data-table/modus-data-table.tsx
> +    const rowData: unknown[] = this.table.options.data.map(
Done, added an if condition to check for accessor key.

2023-05-10 05:20 UTC, Ankur-Koul commented on stencil-workspace/src/components/modus-data-table/modus-data-table.tsx
> +                  {row.getAllCells()?.map((cell) => {
This I have changed to `getAllCells`

2023-05-10 05:23 UTC, Ankur-Koul commented on stencil-workspace/src/components/modus-data-table/parts/modus-data-table-header.tsx
> +      {header.isPlaceholder ? null : (
Removed

2023-05-10 05:30 UTC, Ankur-Koul commented on stencil-workspace/storybook/stories/components/modus-data-table/modus-data-table.stories.tsx
It is reflection now.

2023-05-10 05:32 UTC, Ankur-Koul commented on stencil-workspace/src/components/modus-data-table/modus-data-table.tsx
> +  public getRowDataByOriginalIndex(
Removed both the functions

2023-05-10 06:30 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-data-table/modus-data-table.tsx
> +                  {row.getAllCells()?.map((cell) => {
@Ankur-Koul Okay, but we would need to test it again when we enable Add/Remove columns

2023-05-10 07:00 UTC, msankaran0712 requested changes
Few questions, 
On the Columns's model
- what is the difference between `accessorKey` and id ?
- what is the use of `accessoryFn`? Is it similar to cell formatting ?

2023-05-10 07:05 UTC, msankaran0712 requested changes
For a better visibility please move the accessibility section above the properties section,
![image](https://github.com/trimble-oss/modus-web-components/assets/50131391/346902a3-7797-4aa8-b708-0f4d081c55e8)

2023-05-10 07:05 UTC, msankaran0712 requested changes
For a better visibility please move the accessibility section above the properties section,
![image](https://github.com/trimble-oss/modus-web-components/assets/50131391/346902a3-7797-4aa8-b708-0f4d081c55e8)

2023-05-10 11:43 UTC, msankaran0712 requested changes
can you place the code block before the summary row section

2023-05-10 11:43 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-data-table/modus-data-table.tsx
> +    const headerGroups: HeaderGroup<unknown>[] = this.table.getHeaderGroups();
Please try using `getAllLeafColumns` or `getLeafHeaders`

2023-05-10 11:43 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-data-table/modus-data-table.tsx
> +                      isNestedParentHeader={index < lengthOfHeaderGroups - 1}
I would suggest `isColumnGroupHeader`

2023-05-10 11:43 UTC, msankaran0712 commented on stencil-workspace/storybook/stories/components/modus-data-table/modus-data-table-storybook-docs.mdx
> +  accessorKey?: string;
is `accessorKey` optional ?

2023-05-10 11:51 UTC, msankaran0712 requested changes

2023-05-10 11:51 UTC, msankaran0712 commented on stencil-workspace/storybook/stories/components/modus-data-table/modus-data-table-storybook-docs.mdx
> +Users can use this to prove custom elements.
typo `to add custom elements`

2023-05-10 11:59 UTC, Ankur-Koul commented on stencil-workspace/storybook/stories/components/modus-data-table/modus-data-table-storybook-docs.mdx
> +Users can use this to prove custom elements.
rectified.

2023-05-10 11:59 UTC, Ankur-Koul commented on stencil-workspace/storybook/stories/components/modus-data-table/modus-data-table-storybook-docs.mdx
> +  accessorKey?: string;
nop

2023-05-11 06:50 UTC, msankaran0712 requested changes
Issue1 : 
![image](https://github.com/trimble-oss/modus-web-components/assets/50131391/83a60dbf-3560-422f-8443-034e58fbf9b5)

Issue 2: 
![image](https://github.com/trimble-oss/modus-web-components/assets/50131391/3a52e38b-34e8-4237-9113-dedd0dcbac7e)

Issue 3: Incorrect sorting tooltip message
![image](https://github.com/trimble-oss/modus-web-components/assets/50131391/208e41e2-2ba5-4507-b901-6b1d1b836bd4)

2023-05-11 07:18 UTC, msankaran0712 approved these changes

2023-05-11 07:18 UTC, merged