Modus data table pagination
trimble-oss/modus-web-components pull request #1231
Opened 2023-04-27 09:40 UTC by hemantk1325

Fixes #1110 

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation (including CHANGELOG updates)
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] I have checked my code and corrected any misspellings

2023-04-27 12:00 UTC, hemantk1325 commented on stencil-workspace/src/components/modus-data-table/modus-data-table.tsx
> +  @Prop() pageSizeList: number[] = [];
I have added default value of pageSizeList [10,20,30,40]

2023-04-27 12:00 UTC, hemantk1325 commented on stencil-workspace/src/components/modus-data-table/modus-data-table.tsx
> +        {(this.pagination && this.data.length !== 0) && (
made the changes

2023-04-27 12:01 UTC, hemantk1325 commented on stencil-workspace/src/components/modus-pagination/modus-pagination.tsx
> +    this.maxPage > 1 && pages.push(this.minPage);
it is checking if the pages are more than one than it will execute this condition.

2023-04-27 12:02 UTC, hemantk1325 commented on stencil-workspace/src/components/modus-data-table/parts/modus-data-table-pagination.tsx
> +        View{' '}
done

2023-04-27 12:02 UTC, hemantk1325 commented on stencil-workspace/storybook/stories/components/modus-data-table/modus-data-table.stories.tsx
>    `;
done

2023-04-28 10:35 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-data-table/modus-data-table.scss
> +  font-size: 14px;
please always use a variable for font-size, for 14px it must be $rem-14px. Check `src/ global/modus-varaibles.scss` file

2023-04-28 10:36 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-data-table/modus-data-table.scss
> +  font-size: 14px;
Please update the font size wherever it is used

2023-04-28 10:37 UTC, msankaran0712 requested changes
Please check the comments

2023-04-28 12:43 UTC, hemantk1325 commented on stencil-workspace/src/components/modus-data-table/modus-data-table.scss
> +  font-size: 14px;
done

2023-05-03 10:50 UTC, msankaran0712 approved these changes

2023-05-03 11:43 UTC, msankaran0712 approved these changes

2023-05-04 12:05 UTC, msankaran0712 commented
Closing this PR for now as there will be a new PR with pagination and column resizing clubbed.

2023-05-04 12:05 UTC, closed without merging