Modus NavBar - Include Add icon
trimble-oss/modus-web-components pull request #1255
Opened 2023-05-02 17:51 UTC by cjwinsor

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #1247

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (including CHANGELOG updates)
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

2023-05-02 17:59 UTC, cjwinsor commented on stencil-workspace/src/components/modus-navbar/modus-navbar.e2e.ts
> +  });
Similar to other tests, checks for proper emitting of event

2023-05-02 18:00 UTC, cjwinsor commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +            {this.showAdd && (
This is where we handled `showAdd`

2023-05-02 18:02 UTC, cjwinsor commented on stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar.stories.tsx
> +  },
Allowing canvas to toggle this on/off.  Will most likely tackle the rest of the properties in future PRs

2023-05-02 18:51 UTC, cjwinsor commented
We can wait on this being included in a future release at this time.

2023-05-03 05:31 UTC, coliff commented on stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar.stories.tsx
> +      description: 'Toogle the plus button',
Can you pls fix this typo on 'toggle'

2023-05-08 06:15 UTC, msankaran0712 requested changes
As discussed we needed an array input for icons.

2023-05-18 13:08 UTC, closed without merging

2023-05-18 13:08 UTC, cjwinsor commented
Closing, will create new PR when work is completed on changes.