[EPD-11101] Search - add overlay and search functionality to Modus bar
trimble-oss/modus-web-components pull request #1284
Opened 2023-05-12 21:48 UTC by cjwinsor

Search - add overlay and search functionality to Modus bar

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (including CHANGELOG updates)
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

2023-05-18 06:20 UTC, Sanket8793 commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +  }
on Search Button Click show the search Overlay

2023-05-18 06:21 UTC, Sanket8793 commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +  }
on Close Button Hide the search overlay and set value to null

2023-05-18 06:22 UTC, Sanket8793 commented on stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
> +
Added includeTextBoxInNavbar boolean Proeprty to Check whether the textbox is in Navbar

2023-05-18 06:27 UTC, Sanket8793 commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +        </div>
Added <modus-autocomplete> component and close button to show search overlay textbox when we click on search button and it handles through expand and collapse classes

2023-05-18 06:29 UTC, Sanket8793 commented on stencil-workspace/src/components/modus-text-input/modus-text-input.tsx
> +            } ${this.includeTextBoxInNavbar ? 'has-textbox' : ''}`}
Apply the class when includeTextBoxInNavbar is true to apply the css style

2023-06-20 12:12 UTC, hsoni177 commented on stencil-workspace/src/components/modus-navbar/modus-navbar-search-overlay/modus-navbar-search-overlay.tsx
> +}
Moved the search overlay box into the `ModusNavbarSearchOverlay` component.

2023-06-20 12:15 UTC, msankaran0712 commented
@hsoni177 @Sanket8793, for adding comments for your code,

please use `Start a review` 
![image](https://github.com/trimble-oss/modus-web-components/assets/50131391/83f2bdc7-6cf9-45df-8759-0b484daf392f)

And after adding the comments, select the `Comment` option 
![image](https://github.com/trimble-oss/modus-web-components/assets/50131391/9b09d002-f03f-4899-84ed-bc1665af7187)

This approach will make sure the `Resolve conversation` button is not visible.

2023-06-20 12:17 UTC, hsoni177 commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +          {!this.searchOverlayVisible && <Fragment>
Instead of show and hide navbar render the navbar only if  `searchOverlayVisible` is `false`.

2023-06-20 12:19 UTC, hsoni177 commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +          </modus-navbar-search-overlay>}
`modus-navbar-search-overlay` only render when `searchOverlayVisible` is true

2023-06-21 09:43 UTC, msankaran0712 requested changes

2023-06-21 09:43 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-navbar/modus-navbar-search-overlay/modus-navbar-search-overlay.scss
> +:host {
rename the folder to just `search-overlay`, to keep it consistent with other folders.

2023-06-21 09:43 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-navbar/modus-navbar-search-overlay/modus-navbar-search-overlay.tsx
> +  @Event() close: EventEmitter<boolean>;
`close` event do not need an argument, I don't see the argument is been used anywhere

2023-06-21 09:43 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-navbar/modus-navbar-search-overlay/modus-navbar-search-overlay.tsx
> +              <IconClose
pressing close button using keyboard nothing happens

2023-06-21 09:43 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +          {!this.searchOverlayVisible && <Fragment>
I would suggest keeping overlay functionality optional, using a separate configuration `enableSearchOverlay`.  So both `showSearch` and `enableSearchOverlay` should decide on the overlay visibility.

2023-06-21 09:43 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +          {!this.searchOverlayVisible && <Fragment>
I'd like to check with @egunther39 and @soniakaukonen whether the Navbar search includes an overlay by default, or if it's only a variant.
cc @cjwinsor @ryan-henness-trimble

2023-06-21 09:43 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +  @State() value: string;
it looks like `value` state is not used anywhere

2023-06-21 09:43 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +          {this.searchOverlayVisible && <modus-navbar-search-overlay
Please keep the overlay block in a constant

2023-06-21 09:43 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-navbar/modus-navbar.vars.scss
> +$modus-navbar-search-active-color: var(--modus-navbar-trimble-green, #349C44) !default;
where is `--modus-navbar-trimble-green` defined ?

2023-06-21 09:43 UTC, msankaran0712 commented on stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar-storybook-docs.mdx
> +| `searchChange`            | An event that fires on search value change.            | `CustomEvent<string>`         |
Please add update the `implementation details` section about the search overlay

2023-06-21 09:44 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-navbar/modus-navbar-search-overlay/modus-navbar-search-overlay.tsx
> +              <IconClose
Please note that the search icon cannot be accessed using the tab key, I would request to fix that as well.

2023-06-21 09:46 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-navbar/modus-navbar-search-overlay/modus-navbar-search-overlay.tsx
> +              <IconClose
After the overlay is closed, I would expect the focus to stay in Navbar. Please confirm @soniakaukonen @egunther39

2023-06-23 05:56 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +          {!this.searchOverlayVisible && <Fragment>
@cjwinsor @hsoni177 @egunther39 confirmed that overlay is optional. We should be able to use `enableSearchOverlay`. Currently, clicking on the search icon performs no action. However, I anticipate that in the future, we will incorporate a search animation that expands and reveals a search text box.

2023-06-23 05:57 UTC, msankaran0712 commented
Should we move the PR to "Ready for review" status? @cjwinsor @hsoni177

2023-06-23 14:04 UTC, msankaran0712 requested changes
Accessibility Issues:

1. As a user, when the search overlay opens, I would expect the cursor to be in the text box by default because that is the only purpose the overlay has.
2. When the overlay closes, the focus should be on the search icon, so that I can continue to navigate through the Navbar elements.
3. When the search overlay is open, after focusing the close icon, pressing any key closes the overlay.

2023-06-23 14:05 UTC, msankaran0712 requested changes
Accessibility Issues:
- As a user, when the search overlay opens, I would expect the cursor to be in the text box by default because that is the only purpose the overlay has.
- When the overlay closes, the focus should be on the search icon, so that I can continue to navigate through the Navbar elements.
- When the search overlay is open, after focusing the close icon, pressing any key closes the overlay.

2023-06-23 14:39 UTC, msankaran0712 requested changes

2023-06-23 14:39 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-navbar/modus-navbar.scss
> +  .autocomplete {
I don't think the class is used anywhere

2023-06-23 14:39 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-navbar/search-overlay/modus-navbar-search-overlay.scss
> +      width: 708px;
I am concerned about search box responsiveness because of the fixed width, 708px. It overflows on a small screen. Please use min and max width. 
The submission document shows how the text box resizes on smaller screens.

![image](https://github.com/trimble-oss/modus-web-components/assets/50131391/41176cbf-ae23-47d2-a0b8-3adc7670ca21)

2023-06-23 14:39 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +  searchButtonClickHandler(event: MouseEvent) {
Rename to `searchMenuClickHandler`

2023-06-23 14:39 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +  searchButtonKeydownHandler(event: KeyboardEvent): void {
Rename to `searchMenuKeydownHandler` to be consistent with existing methods

2023-06-23 14:39 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +    const overlay = this.enableSearchOverlay && this.searchOverlayVisible &&
Do we need to check `enableSearchOverlay`?

2023-06-23 14:39 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-navbar/modus-navbar.scss
> +    &.expand {
It looks like this block of CSS is repeated for `.left` and `.right`. Please keep the common CSS in a single block.

2023-06-23 14:39 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-navbar/search-overlay/modus-navbar-search-overlay.tsx
> +              onKeyDown={() => this.close.emit()}>
Why do we have the close emit code at two places?

2023-06-23 14:39 UTC, msankaran0712 commented on stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar-storybook-docs.mdx
> +- Search overlay only works with the 'show-search' attribute, on clicking on the search menu button search overly will be opened.
Please fix the typos and mention `enableSearchOverlay` too. 

The text could be put in a better way, just a thought.

2023-06-27 12:27 UTC, hsoni177 commented on stencil-workspace/src/components/modus-navbar/modus-navbar.scss
> +    &.expand {
a

2023-06-27 12:46 UTC, hsoni177 commented on stencil-workspace/src/components/modus-navbar/modus-navbar.scss
> +    &.expand {
@msankaran0712 Moved common CSS from left and right into single block statement but not found much.

2023-06-27 12:46 UTC, hsoni177 commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +
@msankaran0712 removed the button from event name.

2023-06-27 12:46 UTC, hsoni177 commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +  }
Set the the timeout to make sure nav-bar rendering completed in DOM, So we can easily find the search button and set focus back when search overlay closed.

2023-06-27 12:46 UTC, hsoni177 commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +      </modus-navbar-search-overlay>;
@msankaran0712 removed the unwanted condition.

2023-06-27 12:46 UTC, hsoni177 commented on stencil-workspace/src/components/modus-navbar/search-overlay/modus-navbar-search-overlay.scss
> +    }
As of now we don't have minimum textbox width for small mobile screen (for 320px), So set the minimum width accordingly.
https://www.figma.com/file/wyfVJUHWRMkeCfdB38HFEE/Modus---Web?node-id=1920%3A11782&mode=dev

2023-07-06 08:01 UTC, msankaran0712 requested changes

2023-07-06 08:25 UTC, hsoni177 commented on stencil-workspace/src/components/modus-navbar/search-overlay/modus-navbar-search-overlay.tsx
> +    const modusTextInput = this.element.querySelector("modus-text-input");
> Does the `autoFocus` prop on text input not work?

Yes, I tried with the same, but it only works once on page load only, for the dynamic element it's not working. I think required some time to complete the rendering in DOM then we can set the focus on elements that could not be worked with autofocus, that's why set the focus by code.

2023-07-07 07:19 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-navbar/search-overlay/modus-navbar-search-overlay.tsx
> +  modusTextInput?: HTMLModusTextInputElement;
no need for "?"

2023-07-07 08:14 UTC, msankaran0712 approved these changes

2023-07-07 08:15 UTC, merged