Pagination issue fix
trimble-oss/modus-web-components pull request #1297
Opened 2023-05-17 09:49 UTC by hemantk1325

## Description

Fix pagination row per page issue when pagination is not enable.

2023-05-18 11:35 UTC, msankaran0712 requested changes

2023-05-18 11:35 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-data-table/constants/constants.ts
> +export const PageSizeList = [10, 20, 50];
Please rename it to `DefaultPageSizes`

2023-05-18 11:54 UTC, hemantk1325 commented on stencil-workspace/src/components/modus-data-table/constants/constants.ts
> +export const PageSizeList = [10, 20, 50];
done

2023-05-18 11:54 UTC, hemantk1325 commented on stencil-workspace/src/components/modus-data-table/modus-data-table.tsx
> +    this.pagination &&
done

2023-05-19 11:10 UTC, msankaran0712 approved these changes

2023-05-19 11:10 UTC, merged