[EPD-11114] Modus NavBar - User Menu Tooltip
trimble-oss/modus-web-components pull request #1298
Opened 2023-05-17 12:27 UTC by hsoni177

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #1294

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (including CHANGELOG updates)
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

2023-05-17 14:59 UTC, hsoni177 commented on stencil-workspace/src/components.d.ts
>          /**
profileMenuLabel prop used to display text on tooltip.

2023-05-17 15:01 UTC, hsoni177 commented on stencil-workspace/src/components/modus-navbar/modus-navbar.e2e.ts
>  });
Here we wanted to make sure that when hover on user menu it dose show the tooltip.

2023-05-17 15:03 UTC, hsoni177 commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +
profileMenuLabel prop used to display text on tooltip.

2023-05-17 15:05 UTC, hsoni177 commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +            </modus-tooltip>
Wrapped user menu with modus-tooltip to display tooltip. And also if profileMenuLabel is not found then display the user name in tooltip.

2023-05-17 15:06 UTC, hsoni177 commented on stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar.stories.tsx
Add a textbox control to set tooltip text in storybook

2023-05-17 18:24 UTC, cjwinsor commented on stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar.stories.tsx
> -      inlineStories: true,
Why was this removed?

2023-05-17 18:25 UTC, cjwinsor commented on stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar.stories.tsx
> -    viewMode: 'docs',
Why was viewMode removed?

2023-05-18 11:12 UTC, hsoni177 commented on stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar.stories.tsx
> -      inlineStories: true,
Reverted this changes.

2023-05-18 11:12 UTC, hsoni177 commented on stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar.stories.tsx
> -    viewMode: 'docs',
Reverted this changes.

2023-05-23 11:12 UTC, msankaran0712 requested changes

2023-05-23 11:12 UTC, msankaran0712 commented on stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar.stories.tsx
> +      description: 'Set the tooltip text for user menu',
description should read `profile` menu

2023-05-23 16:28 UTC, ryan-henness-trimble requested changes

2023-05-23 16:28 UTC, ryan-henness-trimble commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +
I suggest using 'Tooltip' instead of 'Label' in the naming convention. For example, `profileMenuTooltip` or `profileMenuTooltipText` would be more descriptive and aligned with the prop's purpose

2023-05-23 16:28 UTC, ryan-henness-trimble commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +            </modus-tooltip>
It would be more intuitive if the tooltip did not appear when the menu is open. Having both the menu and tooltip displayed simultaneously seems counterintuitive to me

Could we consider adding a `showOnHover` prop to the `modus-tooltip` component with a default value of `true`? This way, we can set it to `false` when the menu is open, ensuring that only the menu is displayed

2023-05-23 16:28 UTC, ryan-henness-trimble commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +            </modus-tooltip>
Additionally, it might be worth considering not displaying anything if the `profileMenuLabel` prop is not provided. Leaving it up to the consumer to decide what they want to show in the tooltip will provide more flexibility for the component

2023-05-23 16:28 UTC, ryan-henness-trimble commented on stencil-workspace/src/components/modus-navbar/modus-navbar.e2e.ts
>  });
Good job on this test! 

If it's relatively easy to do, could we add an additional part to the test to make sure the tooltip goes away when hovering over the open user menu?

2023-05-24 14:23 UTC, hsoni177 commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +            </modus-tooltip>
> It would be more intuitive if the tooltip did not appear when the menu is open. Having both the menu and tooltip displayed simultaneously seems counterintuitive to me
> 
> Could we consider adding a `showOnHover` prop to the `modus-tooltip` component with a default value of `true`? This way, we can set it to `false` when the menu is open, ensuring that only the menu is displayed

Is it required to change this in this PR? Because we don't have property `showOnHover ` in `modus-tooltip` component so do we need to create a new issue for it?

2023-05-26 13:38 UTC, cjwinsor commented
@ryan-henness-trimble For the tooltip property, would it make sense to use an object with `text` and aria-label` properties so we make sure we aren't missing out on accessibility needs. So it would become

```ts
@Prop() searchTooltip: { text: string, aria-label: string | null }
@Prop() profileMenuTooltip: { text: string, aria-label: string | null }
```

Alternatively we could add a `tooltip` property to the `profileMenuOptions`.

@msankaran0712 @coliff Thoughts as well on this?

With the + icon changes, and the potential for a dynamic list of icons.  I could see the navbar only having a search icon and a user menu as built in, and the icons added in the  + could use the same interface for setting both text and aria-label.   I think we were overlooking the `aria-label` up until this point because it wasn't in our requirements.

We could look to add a `ModusNavbarTooltip` interface to define these properties, as I don't believe we'd ever need or want the ability to control position.

2023-05-29 07:28 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +
I absolutely agree @ryan-henness-trimble including 'tooltip' is better and clear.

2023-05-29 07:53 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +            </modus-tooltip>
@ryan-henness-trimble Thanks a lot!! I would love to have an option to choose whether to show tooltip on hover so that it does not linger around when clicking.
My concern is, when a component has a property `showOn<something>`, it usually means to show/hide it only on a specific scenario, and users should be able to see it other ways, like on click, on focus. 

`showOnHover` might lead to confusions, maybe "hideOnClick" is a better name.

2023-05-29 08:14 UTC, msankaran0712 commented
> @ryan-henness-trimble For the tooltip property, would it make sense to use an object with `text` and aria-label` properties so we make sure we aren't missing out on accessibility needs. So it would become
> 
> ```ts
> @Prop() searchTooltip: { text: string, aria-label: string | null }
> @Prop() profileMenuTooltip: { text: string, aria-label: string | null }
> ```
> 
> Alternatively we could add a `tooltip` property to the `profileMenuOptions`.
> 
> @msankaran0712 @coliff Thoughts as well on this?
> 
> With the + icon changes, and the potential for a dynamic list of icons. I could see the navbar only having a search icon and a user menu as built in, and the icons added in the + could use the same interface for setting both text and aria-label. I think we were overlooking the `aria-label` up until this point because it wasn't in our requirements.
> 
> We could look to add a `ModusNavbarTooltip` interface to define these properties, as I don't believe we'd ever need or want the ability to control position.

I agree 👍🏼 Also we can add position too, if it is on `modus-tooltip`  it should be on our interface too.

2023-05-30 14:32 UTC, cjwinsor commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +            </modus-tooltip>
@msankaran0712 @ryan-henness-trimble Just an outside though, but what if we had a `disabled` property?  This way when the profile menu opens we set `disabled=true` and when it's closed we set it to `disabled=false` so it can resume working normally.  This avoids the implications from the other names.  

With `showOnHover` we are basically doing the same, disabling the hover functionality while the profile is open.  I could see a `showOnActive` being an alternative property for when its tabbed into.  But then, of course, we'd have to disable both when the profile menu is shown.  `disabled` would handle both of those at once.

2023-05-31 16:04 UTC, ryan-henness-trimble commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +            </modus-tooltip>
@cjwinsor @msankaran0712 `disabled` seems like a great way to solve this. I like how it abstracts the hover concept so that we don't have to worry about the difference between hover and active, and aligns better with common naming conventions

Just a summary to check my understanding:
The `modus-tooltip` has an optional input called `disabled` that is set to `false` by default
When the user hovers over the `modus-navbar`'s user menu button, the tooltip appears
When the `modus-navbar`'s user menu is open, the tooltip's `disabled` flag will be set to `true` so that the tooltip does not appear

2023-05-31 16:33 UTC, ryan-henness-trimble commented
> @ryan-henness-trimble For the tooltip property, would it make sense to use an object with `text` and aria-label` properties so we make sure we aren't missing out on accessibility needs. So it would become
> 
> ```ts
> @Prop() searchTooltip: { text: string, aria-label: string | null }
> @Prop() profileMenuTooltip: { text: string, aria-label: string | null }
> ```
> 
> Alternatively we could add a `tooltip` property to the `profileMenuOptions`.
> 
> @msankaran0712 @coliff Thoughts as well on this?
> 
> With the + icon changes, and the potential for a dynamic list of icons. I could see the navbar only having a search icon and a user menu as built in, and the icons added in the + could use the same interface for setting both text and aria-label. I think we were overlooking the `aria-label` up until this point because it wasn't in our requirements.
> 
> We could look to add a `ModusNavbarTooltip` interface to define these properties, as I don't believe we'd ever need or want the ability to control position.

Defining the Tooltip interface while adding it as property to the `profileMenuOptions` seems like a good choice to me as the `profileMenuTooltip` and `profileMenuOptions` are closely related. Also like you said, the new interface would make it easier to include tooltips for the dynamic navbar icons as well

2023-05-31 18:22 UTC, hsoni177 commented
@ryan-henness-trimble @msankaran0712 I updated the PR as per feedback. Can you review it again please?
CC: @cjwinsor

2023-05-31 22:55 UTC, ryan-henness-trimble commented
Breaking change: Name and interface update to the `searchLabel` input

2023-06-01 09:49 UTC, hsoni177 commented
@ryan-henness-trimble My apologies, accidently I Re-requested to the review so please ignore.

2023-06-02 16:04 UTC, hsoni177 commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +
@ryan-henness-trimble @msankaran0712 Moved the profileMenuTooltip in profileMenuOptions.

2023-06-02 16:08 UTC, hsoni177 commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +            </modus-tooltip>
@ryan-henness-trimble @msankaran0712 rename the prop name from showOnHover to disabled, and also did code change when disabled=true then hide the tooltip and on false show the tooltip, set default disabled=false.

2023-06-02 16:09 UTC, hsoni177 commented on stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar.stories.tsx
> +      description: 'Set the tooltip text for user menu',
@msankaran0712 updated the with `profile`.

2023-06-02 16:12 UTC, hsoni177 commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +                <modus-tooltip {...this.searchTooltip} position="bottom">
@ryan-henness-trimble updated the code as per suggestion.

2023-06-05 12:12 UTC, msankaran0712 requested changes

2023-06-05 12:12 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-tooltip/modus-tooltip.tsx
> +  @Prop() disabled: boolean;
please add a unit test

2023-06-05 12:12 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-tooltip/modus-tooltip.tsx
> +  /** Whether to show the tooltip or not on hover */
I don't think the comment is right, it should be saying hover and focus.

cc @ryan-henness-trimble @cjwinsor 

Confirming with @egunther39 @soniakaukonen if a tooltip is required to appear on focus.

2023-06-05 14:50 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-tooltip/modus-tooltip.tsx
> +  /** Whether to show the tooltip or not on hover */
as discussed with @egunther39 @soniakaukonen  we need a tooltip on focus too, especially for icon buttons

@hsoni177 please rewrite your comments for the `disabled` prop to `To hide/show the tooltip` 

cc @ryan-henness-trimble

2023-06-05 19:51 UTC, ryan-henness-trimble commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +                <modus-tooltip {...this.searchTooltip} position="bottom">
the TypeScript compiler won't catch differences in the interfaces for the `modus-tooltip` inputs and the `searchTooltip` interface. Even though it works right now with the interfaces we have, we should explicitly set the `modus-tooltip` inputs instead of spreading the `searchTooltip` just in case the `searchTooltip`'s interface or inputs change in the future

If either of the interfaces change, we won't get an error which could potentially be hard to debug

I suggest making it
```html
<modus-tooltip 
    position="bottom" 
    text={this.searchTooltip.text} 
    aria-label={this.searchTooltip.ariaLabel}>
</modus-tooltip>
```

2023-06-06 15:54 UTC, hsoni177 commented on stencil-workspace/src/components/modus-tooltip/modus-tooltip.tsx
> +  /** Whether to show the tooltip or not on hover */
@msankaran0712 We can address the tooltip on focus too later?

2023-06-07 06:48 UTC, hsoni177 commented on stencil-workspace/src/components/modus-tooltip/modus-tooltip.tsx
> +  /** Whether to show the tooltip or not on hover */
@msankaran0712 Updated  comments for the disabled prop to To hide/show the tooltip

2023-06-07 06:49 UTC, hsoni177 commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +                <modus-tooltip {...this.searchTooltip} position="bottom">
@ryan-henness-trimble Updated the code as per your suggestion.

2023-06-07 07:02 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-tooltip/modus-tooltip.tsx
> +  /** Whether to show the tooltip or not on hover */
Yes, handling focus is a separate issue #1391

2023-06-07 08:16 UTC, msankaran0712 approved these changes

2023-06-07 17:00 UTC, ryan-henness-trimble approved these changes

2023-06-07 17:01 UTC, merged