Added configurations for Modus pagination component
trimble-oss/modus-web-components pull request #1314
Opened 2023-05-19 06:30 UTC by hemantk1325

## Description

Added configuration for modus component

Fixes #1171

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] I have checked my code and corrected any misspellings

2023-05-22 05:17 UTC, msankaran0712 requested changes

2023-05-22 07:47 UTC, msankaran0712 requested changes
Also can you please make the dropdown icon hoverable too ?

2023-05-22 07:49 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-pagination/modus-pagination.tsx
>    activePageWatch(newValue: number, oldValue: number) {
please make sure the code block for watch handlers are placed immediately below the respective property

2023-05-22 07:52 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-pagination/modus-pagination.tsx
> +                        <div
Ideally page numbers should be `<li>` items with a parent`<ul>` or `<option>` items with a parent `<select>`, why is a div used for rendering each item?

2023-05-22 07:53 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-pagination/modus-pagination.tsx
> +                          onClick={(event) => {
I think we can make use for modus-dropdown component for the page numbers, have a look at https://deploy-preview-1314--modus-webcomponents.netlify.app/?path=/docs/components-dropdown--default.

2023-05-22 09:09 UTC, sankarNous commented on stencil-workspace/src/components/modus-pagination/modus-pagination.tsx
> +  @Prop() pagerText: string;
I agree

2023-05-22 09:26 UTC, sankarNous commented on stencil-workspace/src/components/modus-pagination/modus-pagination.scss
> +    background-color: #333;
create variable for colors

2023-05-22 09:35 UTC, sankarNous commented on stencil-workspace/src/components/modus-pagination/modus-pagination.scss
>        width: 2rem;
pick one measurement unit. don't mix both(px and rem). I think we should use pixels for everything expect font-size. 
@msankaran0712 any thoughts?

2023-05-22 21:50 UTC, ryan-henness-trimble requested changes

2023-05-22 21:50 UTC, ryan-henness-trimble commented on stencil-workspace/src/components/modus-pagination/modus-pagination.tsx
> +  @State() pages: (number | string)[];
Do we need the `string` type here? This seems like it should just be `number`

2023-05-22 21:50 UTC, ryan-henness-trimble commented on stencil-workspace/src/components/modus-pagination/modus-pagination.tsx
> +                        {(this.showDropdownLeft = false)}
Setting state here seems odd. Why do we need to do this?

We may want to reconsider how we're triggering the logic for showing/hiding the dropdowns

2023-05-22 21:50 UTC, ryan-henness-trimble commented on stencil-workspace/src/components/modus-pagination/modus-pagination.tsx
> +                {isNaN(+page) &&
These dropdowns should close when the user clicks outside of its bounds

They also look like they are missing the shared dropdown item styling - I would expect them to be styled the same as the Dropdown/Select component options

I believe the caret icons should also be placed next to the ellipses, like shown in #1171

2023-05-22 21:50 UTC, ryan-henness-trimble commented on stencil-workspace/src/components/modus-pagination/modus-pagination.tsx
> +  @Prop() pagerText: string;
I would maybe go for something like `useArrowPagingControls` or `useArrowControls` as a `boolean` defaulted to `true` - if left false, uses the 'prev' and 'next' controls

2023-05-22 21:50 UTC, ryan-henness-trimble commented on stencil-workspace/src/components/modus-pagination/modus-pagination.scss
> +    background-color: #333;
Do we want the scrollbar to be customized at all? We may want to stick with the browser's default scrollbar since there are no specs defined around this in the design system

2023-05-22 21:50 UTC, ryan-henness-trimble commented on stencil-workspace/src/components/modus-pagination/modus-pagination.scss
> -      height: 2rem;
🤔

2023-05-22 21:50 UTC, ryan-henness-trimble commented on stencil-workspace/src/components/modus-pagination/modus-pagination.scss
> +  .hidden-page-number-dropdown {
just `page-number-dropdown` seems good

2023-05-22 21:50 UTC, ryan-henness-trimble commented on stencil-workspace/src/components/modus-pagination/modus-pagination.tsx
> +  @Prop() ellipsis: string;
Should it be `showPageDropdowns` since there are 2 dropdowns?

Also, we should try to be consistent with `pages` vs `pageNumbers` wherever we're using them since they're referring to the same thing. It looks like they're being used interchangeably right now. One spot is the `.hidden-page-number-dropdown` css class name

2023-05-22 21:50 UTC, ryan-henness-trimble commented on stencil-workspace/src/components/modus-pagination/modus-pagination.tsx
> +        pages.push(
This OR `||` is a bit confusing here

2023-05-22 21:50 UTC, ryan-henness-trimble commented on stencil-workspace/src/components/modus-pagination/modus-pagination.tsx
> +        pages.push(
maybe it should be turned into an if-statement that pushes if true?

```ts
if (this.showPageNumberDropdowns) {
    pages.push(...);
}
```

2023-05-22 21:50 UTC, ryan-henness-trimble commented on stencil-workspace/src/components/modus-pagination/modus-pagination.tsx
>      const pages: (number | string)[] = [];
It looks like we're pushing a JSX element into the array now too 🤔 I'm wondering if this name and type needs to change

2023-05-22 21:50 UTC, ryan-henness-trimble commented on stencil-workspace/src/components/modus-pagination/modus-pagination.scss
>        width: 2rem;
@msankaran0712 I think we should be using `rem` unless we've got specific cases that need to be `px`

2023-05-22 21:50 UTC, ryan-henness-trimble commented on stencil-workspace/src/components/modus-pagination/modus-pagination.scss
>        width: 2rem;
`px` may be more appropriate in places where we have specific design constraints

2023-05-22 23:35 UTC, msankaran0712 commented
hey @ryan-henness-trimble, the dropdown is optional and am yet to complete the review as the code looks like it needs a lot of improvements

2023-05-22 23:59 UTC, ryan-henness-trimble commented on stencil-workspace/src/components/modus-pagination/util.tsx
> +export function rightPageDropdown(
These functions would be good candidates for unit tests

2023-05-23 10:50 UTC, msankaran0712 commented
@ryan-henness-trimble @coliff am going to close this PR because it needs a rework.

2023-05-23 10:50 UTC, closed without merging