Added cell render for value formatter
trimble-oss/modus-web-components pull request #1315
Opened 2023-05-19 06:54 UTC by Ankur-Koul

## Description

Added cell rendrer 

Fixes # 1209

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (including CHANGELOG updates)
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

2023-05-19 09:49 UTC, sankarNous commented on stencil-workspace/src/components/modus-data-table/models/modus-data-table-column.ts
> +  // columns?: ModusDataTableColumn[]; //To-do
give some comments for 'TODO'

2023-05-22 06:02 UTC, msankaran0712 requested changes
1. Is it possible to disable sort tooltips on all columns when performing the column resize? because it is interrupting with tooltip messages which is not necessary when resizing a column. You can check with @sankarNous for more details on how to do it.
2. It is okay to show footer in only one example. Please make sure there is no scrollbar appearing.

2023-05-22 06:03 UTC, msankaran0712 requested changes
Please make these changes

![image](https://github.com/trimble-oss/modus-web-components/assets/50131391/53ed60ee-9286-4068-ac86-c55998545d96)

2023-05-22 06:16 UTC, msankaran0712 requested changes
Please keep these types commented out for now, and add a comment explaining why.

![image](https://github.com/trimble-oss/modus-web-components/assets/50131391/92f5f7eb-93ee-4b35-b611-9b1d905371dc)

2023-05-22 06:16 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-data-table/parts/modus-data-table-cell-formatter.tsx
> +function isComponent<TProps>(
please add some comments for these functions

2023-05-22 06:27 UTC, msankaran0712 requested changes

2023-05-22 06:27 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-data-table/parts/modus-data-table-header.tsx
> +          <span>
why do we need a cell formatter for header?

2023-05-22 06:27 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-data-table/models/modus-data-table-column.ts
>    id?: string;
we should a add cell property here.

2023-05-22 06:27 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-data-table/parts/modus-data-table-cell-formatter.tsx
> +function isClassComponent<TProps>(component: Renderable<TProps>) {
I think we must rename the functions to "isFunctionalComponent", "isFunction" as we don't exactly look for a class component

2023-05-22 06:27 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-data-table/parts/modus-data-table-cell.tsx
> +         cell.column.columnDef[PropertyDataType] ===
once we comment out currency data type, we might need to remove the OR clause

2023-05-22 06:35 UTC, msankaran0712 requested changes
@Ankur-Koul Can you please also add one column showing currency, one for date, one for decimal places ?

examples:

![image](https://github.com/trimble-oss/modus-web-components/assets/50131391/9e512f62-41bb-4f74-8363-9605dde2d65f)

![image](https://github.com/trimble-oss/modus-web-components/assets/50131391/837e1670-f950-4c26-ba8c-253ab5ea6866)

2023-05-24 07:27 UTC, Ankur-Koul commented on stencil-workspace/src/components/modus-data-table/models/modus-data-table-column.ts
> +  // columns?: ModusDataTableColumn[]; //To-do
Added

2023-05-24 07:27 UTC, Ankur-Koul commented on stencil-workspace/src/components/modus-data-table/parts/modus-data-table-header.tsx
> +          <span>
Removed

2023-05-24 07:28 UTC, Ankur-Koul commented on stencil-workspace/src/components/modus-data-table/models/modus-data-table-column.ts
>    id?: string;
Added

2023-05-24 07:28 UTC, Ankur-Koul commented on stencil-workspace/src/components/modus-data-table/parts/modus-data-table-cell-formatter.tsx
> +function isClassComponent<TProps>(component: Renderable<TProps>) {
Done

2023-05-24 07:28 UTC, Ankur-Koul commented on stencil-workspace/src/components/modus-data-table/parts/modus-data-table-cell.tsx
> +         cell.column.columnDef[PropertyDataType] ===
Removed

2023-05-24 11:25 UTC, msankaran0712 requested changes
Scrollbars are appearing for value formatter and column resize examples.

2023-05-24 11:25 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-data-table/enums/modus-column-data-type.ts
> +  // To-do, how to support for these datatypes is not decided for now.
please remove "TODO" and update it to "to support in the future"

2023-05-24 11:25 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-data-table/parts/modus-data-table-cell-formatter.tsx
> + * Checks if the item to display is a component or not.
I would recommend updating the text to "checks if the input for cell formatter is a functional component or class component"

2023-05-24 11:25 UTC, msankaran0712 commented on stencil-workspace/storybook/stories/components/modus-data-table/modus-data-table-storybook-docs.mdx
> +User can take the data of a cell and modify it according to there requirements
Recommendation for line 148: "User can take the data of a cell and apply any string-based formatting logic."

2023-05-24 14:01 UTC, msankaran0712 approved these changes

2023-05-24 14:01 UTC, merged