Added prev Next text option to modus pagination
trimble-oss/modus-web-components pull request #1329
Opened 2023-05-23 07:40 UTC by hemantk1325

## Type of change
- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

2023-05-23 10:22 UTC, msankaran0712 requested changes

2023-05-23 10:22 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-pagination/modus-pagination.scss
>        width: 3rem;
I think we need to remove width set on the page number elements. It should be replaced by a padding.
Modus Pagination web component sets a standard width (ex: 3rem for large) on all the page numbers, it looks fine on a single page number but on double digits, it is not.

Comparison: 
Styleguide
![image](https://github.com/trimble-oss/modus-web-components/assets/50131391/d198486d-13a0-40f3-a31b-66a4094e1c6a)

Bootstrap:
![image](https://github.com/trimble-oss/modus-web-components/assets/50131391/cad5ef47-ac3e-496e-ae5c-c5172bb0181f)


web components:
![image](https://github.com/trimble-oss/modus-web-components/assets/50131391/cc0c2292-b0cd-46aa-a82f-51dbdd524001)

2023-05-23 10:48 UTC, msankaran0712 requested changes

2023-05-23 10:48 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-pagination/modus-pagination.scss
> +    padding: 5px;
padding should be removed

2023-05-23 10:48 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-pagination/modus-pagination.scss
> +    padding: 5px;
we might need to remove the whole css block because most of the styles are already set in the parent elements

2023-05-23 10:48 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-pagination/modus-pagination.tsx
> +              <span class="prev-next-text-button">Prev  </span>
please remove space next `Prev` text

2023-05-23 10:48 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-pagination/modus-pagination.vars.scss
> +$modus-table-pagination-color: var(--modus-table-color, #6A6976) !default;
why do we need this new variable ?

2023-05-23 10:48 UTC, msankaran0712 commented on stencil-workspace/storybook/stories/components/modus-pagination/modus-pagination.stories.tsx
> +      description: 'The pagination\'s pager text',
update the description

2023-05-23 10:48 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-pagination/modus-pagination.tsx
> +  /* Pager prev and next button */
please update the description to "Display prev and next button"

2023-05-23 12:35 UTC, hemantk1325 commented on stencil-workspace/src/components/modus-pagination/modus-pagination.scss
>        width: 3rem;
removed width and added padding instead

2023-05-23 12:35 UTC, hemantk1325 commented on stencil-workspace/src/components/modus-pagination/modus-pagination.tsx
> +  /* Pager prev and next button */
done

2023-05-23 12:35 UTC, hemantk1325 commented on stencil-workspace/src/components/modus-pagination/modus-pagination.vars.scss
> +$modus-table-pagination-color: var(--modus-table-color, #6A6976) !default;
removed as it is not needed now

2023-05-23 12:36 UTC, hemantk1325 commented on stencil-workspace/src/components/modus-pagination/modus-pagination.tsx
> +              <span class="prev-next-text-button">Prev  </span>
done

2023-05-23 12:36 UTC, hemantk1325 commented on stencil-workspace/src/components/modus-pagination/modus-pagination.scss
> +    padding: 5px;
done

2023-05-23 16:41 UTC, ryan-henness-trimble commented
Please remember to fill out the `Description` and `How Has This Been Tested?` sections on future PRs? It'll help reviewers with less context of the issue

2023-05-23 17:29 UTC, ryan-henness-trimble requested changes

2023-05-23 17:29 UTC, ryan-henness-trimble commented on stencil-workspace/src/components/modus-pagination/modus-pagination.tsx
> +              {this.prevNextTextButton ? (
The parent `<li>` elements no longer require curly braces as there are no longer any JSX conditionals being used

I would recommend renaming the `handleChevronClick` function to something like `handlePageChange` since it now handles both text and chevron interactions

To improve code readability, it would be beneficial to extract both `<li>` controls into separate elements. Additionally, you could consider extracting the page number map into its own element. Here is an example of how you could create two smaller constants within your render function to enhance readability (please adapt the code to your specific changeset, as the code provided here may be outdated):

```ts
render(): unknown {
    const previousPageControl = (
      <li
        class={`${this.activePage != this.minPage ? 'hoverable' : 'disabled'}`}
        onClick={() => this.handleChevronClick('back')}
        onKeyDown={(event) => this.handleKeydownBack(event)}
        tabIndex={0}>
        <IconChevronLeftThick size={this.chevronSizeBySize.get(this.size)} />
      </li>
    );

    const nextPageControl = (
      <li
        class={`${
          this.activePage != this.maxPage ? 'hoverable' : 'disabled'
        }`}
        onClick={() => this.handleChevronClick('forward')}
        onKeyDown={(event) => this.handleKeydownForward(event)}
        tabIndex={0}>
        <IconChevronRightThick
          size={this.chevronSizeBySize.get(this.size)}
        />
      </li>
    );

    return (
      <nav
        aria-label={this.ariaLabel}
        class={`${this.classBySize.get(this.size)}`}>
        <ol>
          {previousPageControl}
          {this.pages.map((page) => {
            return (
              <li
                class={`${page === this.activePage ? 'active' : ''} ${
                  !isNaN(+page) ? 'hoverable' : ''
                }`}
                onClick={() => this.handlePageClick(+page)}>
                {page}
              </li>
            );
          })}
          {nextPageControl}
        </ol>
      </nav>
    );
```

2023-05-23 17:29 UTC, ryan-henness-trimble commented on stencil-workspace/src/components/modus-pagination/modus-pagination.tsx
> +  /* Display prev and next button */
This comment should be updated to: `Whether to display prev and next buttons` to align better with our other comments

2023-05-23 17:29 UTC, ryan-henness-trimble commented on stencil-workspace/storybook/stories/components/modus-pagination/modus-pagination-storybook-docs.mdx
> +### Previous Next Text
I would add to this header, like `Previous and Next Text Controls`, or `Previous/Next Text Controls`

2023-05-23 17:29 UTC, ryan-henness-trimble commented on stencil-workspace/storybook/stories/components/modus-pagination/modus-pagination-storybook-docs.mdx
> +        <td>The pagination's pager text</td>
This should be the same as the comment on the prop inside of the component: `Whether to display prev and next buttons`

Stencil outputs a README within the component's directory when the project is built. You can copy that markdown table from there and replace the `<table>` here with it - that makes it easier to stay 1:1 with the component rather than manually updating this `<table>`

2023-05-23 17:29 UTC, ryan-henness-trimble commented on stencil-workspace/storybook/stories/components/modus-pagination/modus-pagination.stories.tsx
> +      description: "To Display pagination's Prev and Next button text option",
This description should also match the prop's comment

2023-05-23 17:29 UTC, ryan-henness-trimble commented on stencil-workspace/src/components/modus-pagination/modus-pagination.e2e.ts
> +    const element = await page.find('modus-pagination');
We should also check that the previous/next buttons are not found before setting `prevNextTextButton` to `true` on line `35`. This will give us more confidence that the text buttons are not displaying when the arrows should be

Adding `data-testid` attributes to the elements might make it easier to find them within this test (instead of searching for spans)

2023-05-24 06:22 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-pagination/modus-pagination.tsx
> +  @Prop() prevNextTextButton = false;
yes you are right @ryan-henness-trimble I was able to find examples in google with texts like "previous page", "previous", "prev"

2023-05-25 11:21 UTC, msankaran0712 approved these changes

2023-05-25 11:22 UTC, msankaran0712 commented
@ryan-henness-trimble since all the comments are fixed, am merging the PR now but the changes are not going to `main` branch so if you have any more comments, we can still work on it.

2023-05-25 11:25 UTC, merged

2023-05-25 19:57 UTC, ryan-henness-trimble commented on stencil-workspace/src/components/modus-pagination/modus-pagination.tsx
> +  /** Weather to display text or previous icon. */
These button text props should be optional I think - we want to show the arrow icons if the consumer does not set them right?

The comments should be updated to something like: `/* The previous page button text. If not set, an icon control will be used. */`

2023-05-25 19:57 UTC, ryan-henness-trimble commented on stencil-workspace/storybook/stories/components/modus-pagination/modus-pagination-storybook-docs.mdx
> +| `size`               | `size`                  | The pagination's size                    | `"large" \| "medium" \| "small"` | `'medium'`  |
There are some leftover `\` from the copy and paste

2023-05-25 19:57 UTC, ryan-henness-trimble commented
> @ryan-henness-trimble since all the comments are fixed, am merging the PR now but the changes are not going to `main` branch so if you have any more comments, we can still work on it.

Added some minor comments 👍

2023-05-29 06:17 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-pagination/modus-pagination.tsx
> +  /** Weather to display text or previous icon. */
@ryan-henness-trimble Aren't the props by default optional if not using `! ` ?

2023-05-29 06:19 UTC, msankaran0712 commented on stencil-workspace/storybook/stories/components/modus-pagination/modus-pagination-storybook-docs.mdx
> +| `size`               | `size`                  | The pagination's size                    | `"large" \| "medium" \| "small"` | `'medium'`  |
we need to escape pipe symbol from treated as a column separator. We might need to manually replace pipeline symbol with a comma or something every time we copy paste the content from README.md

2023-05-29 06:20 UTC, msankaran0712 commented
> > @ryan-henness-trimble since all the comments are fixed, am merging the PR now but the changes are not going to `main` branch so if you have any more comments, we can still work on it.
> 
> Added some minor comments 👍

hey @ryan-henness-trimble your comments are fixed in [PR](https://github.com/trimble-oss/modus-web-components/pull/1347/files)