[EPD-11205] Implement changes to + icon based on feedback
trimble-oss/modus-web-components pull request #1341
Opened 2023-05-25 08:50 UTC by Sanket8793

## Description

 Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change. 

References https://github.com/trimble-oss/modus-web-components/issues/1247

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] Documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration 

We tested both using the index.html page and running storybook to verify. Review was done by different developer than the one doing the work.

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules
- [X] I have checked my code and corrected any misspellings

2023-05-25 09:00 UTC, Sanket8793 commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +  @Prop() items: ModusNavbarItem[];
I took the **items** property for the ModusNavbarItem array

2023-05-25 09:07 UTC, Sanket8793 commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +          )))}
The icons that are given in the array are looped through the items and will create new buttons

2023-05-25 09:08 UTC, Sanket8793 commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +                    icon={i.icon}
The icons that are given in the array are looped through the items and will create new buttons

2023-05-25 09:10 UTC, Sanket8793 commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +                </modus-navbar-item-menu>
Clicking the icon sets the item's menu to 'pop-out' and shows the item's ID slot accordingly.

2023-05-25 09:12 UTC, Sanket8793 commented on stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar.stories.tsx
> +};
to show the example passing an items array to the default theme

2023-05-25 09:14 UTC, coliff commented
I noticed that in light mode the add icon is displaying as `#252a2e` but the other icons are `#6A6976`.
https://deploy-preview-1341--modus-webcomponents.netlify.app/?path=/docs/components-navbar--default

2023-05-26 13:41 UTC, cjwinsor commented
@ryan-henness-trimble For the tooltip property on `ModusNavbarItem`,  I have an active question on #1298 on whether we should define a `ModusNavbarTooltip` interface.  If so we could use that here as well to provide for an `aria-label`.  

@msankaran0712 @coliff Thoughts as well on this?

2023-05-29 08:14 UTC, msankaran0712 commented
> @ryan-henness-trimble For the tooltip property on `ModusNavbarItem`, I have an active question on #1298 on whether we should define a `ModusNavbarTooltip` interface. If so we could use that here as well to provide for an `aria-label`.
> 
> @msankaran0712 @coliff Thoughts as well on this?

I agree 👍🏼

2023-05-31 21:39 UTC, ryan-henness-trimble commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +  @Prop() items: ModusNavbarItem[];
As a consumer, I'd expect this to be a generic input where I can define buttons that either:
1. Perform some action when clicked
2. Open up a pop-out menu, where the content is provided as dynamic component slots with names `button-menu-{id}`

With those in mind, I think the usage would look something like this:
```html
<body>
    <modus-navbar>
        <div slot="button-menu-add-item">
            This is my custom slot content
        </div>
    </modus-navbar>
    
    <script>
        const navbar = document.querySelector('modus-navbar');

        navbar.buttons = [
            { 
                id: 'add-item', 
                tooltip: 'Add something'
                icon: 'add',
                orderIndex: 0,
                menu: 'pop-out'
            },
            { 
                id: 'home', 
                tooltip: 'Go home'
                icon: 'home',
                orderIndex: 1,
            },
        ];

        navbar.addEventListener('buttonClick', (event) => {
            window.alert(`The ${event.details.id} button was clicked!`);
        });
    </script>
</body>
```

> Notes:
> 1. Each button menu slot will be prefixed with `button-menu`, and then contain the id of the button.
> 2. The `buttonClick` event outputs the id of the button clicked
> 3. I'd expect to be able to add any icon from the [Modus Icons](https://modus-icons.trimble.com/). We can skip this for this PR but should probably write an issue to consume the icon library instead of defining our own svg files

2023-05-31 21:39 UTC, ryan-henness-trimble commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +  @Prop() items: ModusNavbarItem[];
`buttons` or `iconButtons` feel like stronger input names to me

2023-05-31 21:39 UTC, ryan-henness-trimble commented on stencil-workspace/src/components/modus-navbar/item-menu/modus-navbar-item-menu.tsx
> +        <div class="title">Items</div>
I think we want to avoid adding specific implementation in these menus and allow consumers to add whatever content they want via slots

2023-05-31 21:39 UTC, ryan-henness-trimble commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +  @Event() itemMenuOpen: EventEmitter<string>;
This shouldn't be needed once we implement the `buttonClick` event. The `buttonClick` event should emit the button's id, signaling to the consumer which of their buttons was clicked

2023-05-31 21:39 UTC, ryan-henness-trimble commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +    this.items?.forEach(item => item.menu = undefined);
I think we'll want to keep some internal state for whether the dynamic button menus are open. We shouldn't be mutating the `buttons` input

2023-05-31 21:39 UTC, ryan-henness-trimble commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +          {(this.items?.map((i) =>
May want to pull this dynamic icon button logic out into a constant or `FunctionalComponent`

2023-05-31 21:53 UTC, ryan-henness-trimble commented on stencil-workspace/src/components/modus-navbar/item-menu/modus-navbar-item-menu.tsx
> +import {
Shall we call this `modus-navbar-button-menu` and make it a `FunctionalComponent`?

2023-05-31 23:25 UTC, ryan-henness-trimble commented
Deprecation: Buttons that can be replaced by the new `buttons` input

2023-06-01 13:49 UTC, cjwinsor commented on stencil-workspace/src/components/modus-navbar/item-menu/modus-navbar-item-menu.tsx
> +        <div class="title">Items</div>
@ryan-henness-trimble Should we create a `title` prop. I don't think they will have access to the `title` style to style it correctly otherwise.  If not set, then we can hide the title.

2023-06-01 13:56 UTC, cjwinsor commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +          {(this.items?.map((i) =>
@ryan-henness-trimble We can move this into a `ModusNavbarButtonList` and have that handle the display of the list (which can be used later for responsiveness).... and create a `ModusNavBarButton` which handles the click event and the slot and styles etc.

2023-06-01 14:05 UTC, cjwinsor commented on stencil-workspace/src/components/modus-navbar/item-menu/modus-navbar-item-menu.tsx
> +import {
@ryan-henness-trimble Are you thinking something like this

```html
<modus-navbar>
    <modus-navbar-button-list>
        <modus-navbar-button></modus-navbar-button>
        <modus-navbar-button></modus-navbar-button>
        <modus-navbar-button></modus-navbar-button>
    </modus-navbar-button-list>
</modus-navbar>
```

2023-06-01 14:09 UTC, cjwinsor commented on stencil-workspace/src/components/modus-navbar/item-menu/modus-navbar-item-menu.tsx
> +import {
I didn't account for slots in that example, just quick and dirty

2023-06-01 15:59 UTC, ryan-henness-trimble commented on stencil-workspace/src/components/modus-navbar/item-menu/modus-navbar-item-menu.tsx
> +        <div class="title">Items</div>
hmm, I'm not seeing a title defined in the design system. It makes me wonder if we should leave it up to the consumer to style the title if they need one

2023-06-01 16:04 UTC, ryan-henness-trimble commented on stencil-workspace/src/components/modus-navbar/item-menu/modus-navbar-item-menu.tsx
> +import {
My initial thought was that we'd define the buttons in js through the `buttons` prop, and then add slotted elements inside of `modus-navbar` for just the menu content needed

But after seeing your example, I think it makes more sense to encapsulate the button definition/content into composable components like you've got with those child components

2023-06-06 11:00 UTC, msankaran0712 commented
as mentioned by @enowak1031 we need to limit the number of icon buttons on the Navbar to 6 including the profile icon.

cc @cjwinsor @coliff @ryan-henness-trimble @egunther39 @soniakaukonen

2023-06-06 20:19 UTC, cjwinsor commented
> as mentioned by @enowak1031 we need to limit the number of icon buttons on the Navbar to 6 including the profile icon.
> 
> cc @cjwinsor @coliff @ryan-henness-trimble @egunther39 @soniakaukonen

@msankaran0712 I can see that we would need at least

- Notification
- Help
- App Drawer
- Placeholder?

Search and User Profile are special purpose enough that I'd hesitate to include them in the dynamic list.  Are we still thinking to include the Add icon?  I know there have been discussions on other icons but I have no idea if they've been approved.

2023-06-08 15:01 UTC, msankaran0712 commented
> @msankaran0712 Per #1403, can we proceed at this time without limiting anything to six?
> 
> To recap where we are right now, here is what I see as pending items for this PR:
> 
> 1. Move dynamic list of buttons to its own `ModusNavbarButtonList` functional component
> 2. Create a `ModusNavbarButton` functional component
> 3. We won't change the existing icons at this time to use this dynamic list.  The existing buttons can be deprecated later.
> 4. We can update the existing buttons to use the new `ModusNavbarButton` component
> 5. We can rename `items` to `buttons` for the Navbar api
> 6. We can explore composing the `ModusNavbarButtonList` as a child element and/or use `buttons` in the api.  We would still want events for when the button is clicked so content can be dynamically loaded if needed.  Also considering we might want to change the elements programmatically without having to deal with dom elements.
> 
> I think we can resolve all the previous comments and continue from this comment to avoid confusion.

Yes @cjwinsor, limiting to 6 is a low priority at this stage, maybe we can do it when we add all the icons to the dynamic list.

2023-06-13 20:26 UTC, Sanket8793 commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +  }
on buttonClick event got the slotId from the detail of the buttonClickEvent and use that slotId  to render the slot in the  <modus-navbar-button-menu> component

2023-06-13 20:28 UTC, Sanket8793 commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +            </modus-navbar-button-list>
passed the buttons to modus-navbar-button-list component so we can generate the button

2023-06-13 20:32 UTC, Sanket8793 commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +            )}
Slot is not rendered in the <modus-navbar-button> component, so render the slot in <modus-navbar> component through slotId, we got from buttonClick event of the button based on the buttonId

Another approach may be something like this (without use of slot)

<modus-navbar>
    <modus-navbar-button-list>
        <modus-navbar-button id="add-item" tooltip="Quick Add" icon="add">
            <modus-navbar-button-menu title="items" type="pop-out">
                Content
            </modus-navbar-button-menu>
        </modus-navbar-button>
        <modus-navbar-button id="help-item" tooltip="Help" icon="help"></modus-navbar-button>
    </modus-navbar-button-list>
</modus-navbar>

2023-06-13 20:43 UTC, Sanket8793 commented on stencil-workspace/src/components/modus-navbar/button-list/modus-navbar-button-list.tsx
> +export class ModusNavbarButtonList {
Create ModusNavbarButtonList stencil component to create dynamic list of buttons

2023-06-13 20:44 UTC, Sanket8793 commented on stencil-workspace/src/components/modus-navbar/button/modus-navbar-button.tsx
> +export class ModusNavbarButton {
Create a ModusNavbarButton stencil component and update the existing buttons

2023-06-13 20:45 UTC, Sanket8793 commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +  @Prop() buttons: ModusNavbarButton[];
rename items to buttons for the Navbar api

2023-06-14 18:41 UTC, Sanket8793 commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +            )}
Just wanted to follow up on this

2023-06-15 10:33 UTC, msankaran0712 reviewed
Test

2023-06-15 13:17 UTC, Sanket8793 reviewed
@msankaran0712 @ryan-henness-trimble @coliff What is the final decision on naming for user input?

2023-06-16 09:07 UTC, msankaran0712 requested changes
@cjwinsor @Sanket8793 

The Navbar's dynamic icon functionality isn't working as expected. Some issues I observed when testing the code locally,
 1. When multiple icons are added to `buttons`, whichever icon is pressed, the menu pop-up appears at the exact location, not below the clicked icon.
 2. Dynamic icon's menu does not close when clicking outside the menu.
 3. Ordering of dynamic icons does not work
 4. Dynamic icon's menu appears far away from the icon.
 5. The menu starts from the middle of the icon instead of appearing below the icon. Inconsistent with other standard icons like notifications and help.
 6. Dynamic icon's menu overlaps with the menu of standard icons like notifications


Locally,
![chrome_ZD779Yr6zc](https://github.com/trimble-oss/modus-web-components/assets/50131391/a69b5773-c7da-4af2-9c65-3874808e90fd)

2023-06-16 09:11 UTC, msankaran0712 requested changes
This issue is seen very well in the PR preview but not locally. Add icon moves when clicked for the first time.

![chrome_ZD779Yr6zc](https://github.com/trimble-oss/modus-web-components/assets/50131391/f47d9698-de8d-43f7-a09a-fb7903936c50)

2023-06-16 09:15 UTC, msankaran0712 commented
> This issue is seen very well in the PR preview but not locally. Add icon moves when clicked for the first time.
> 
> ![chrome_k3tzki8cDf](https://user-images.githubusercontent.com/50131391/246373391-83cb7d41-8035-4714-b694-8683cc4c47d6.gif)

I believe this issue is caused because of dynamically generating slots.

2023-06-16 12:25 UTC, Sanket8793 commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +  @Event() itemMenuButtonClick: EventEmitter<string>;
> 1. Description is not right
> 2. `itemMenuButtonClick` - we might have to rename this too.

@msankaran0712 what should be the ideal name for this?

2023-06-17 18:08 UTC, Sanket8793 commented on stencil-workspace/src/components/modus-navbar/readme.md
> +| `buttons`              | --                       | (optional) The buttons to render in the Navbar.
Added buttons config in Properties section

2023-06-17 18:11 UTC, Sanket8793 commented on stencil-workspace/src/components/modus-navbar/readme.md
> +| `buttons`              | --                       | (optional) The buttons to render in the Navbar.
Added buttons config in Properties section

2023-06-17 18:13 UTC, Sanket8793 commented on stencil-workspace/src/components/modus-navbar/button-list/modus-navbar-button-list.tsx
> +  tooltip: ModusNavbarTooltip;
change type for tooltip to ModusNavbarTooltip

2023-06-17 18:16 UTC, Sanket8793 commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +            </modus-navbar-button-list>
Sort buttons based on the orderIndex property should appear on the navbar

2023-06-17 18:17 UTC, Sanket8793 commented on stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar-storybook-docs.mdx
> +  ];
use the addMenu as an id for a dynamic menu

2023-06-17 18:22 UTC, Sanket8793 commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> + }
Close dynamic icon's menu when clicking outside the menu.

2023-06-20 07:52 UTC, msankaran0712 requested changes

2023-06-20 07:52 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +            <modus-navbar-button-list class="navbar-button-list" buttons={this.buttons?.sort((a, b) => (a.orderIndex) - (b.orderIndex))}>
Please move the buttons logic to a constant

2023-06-20 12:10 UTC, Sanket8793 commented
> we are calling respective button menu and showing the slot for that button

Hi @msankaran0712 We haven't decided the approach to show the menu on button click, so I will  the implementation details after we decide the approach

2023-06-20 12:16 UTC, Sanket8793 commented
> ![image](https://user-images.githubusercontent.com/50131391/247045558-8aae44c9-32d5-45f9-8f49-7f5000226802.png)
> 
> We need to make sure we add the implementation details about how to add a dynamic menu

Hi @msankaran0712 We haven't decided the approach to show the menu on button click, so I will add the implementation details after we finalized that

2023-06-23 08:17 UTC, Sanket8793 reviewed
@msankaran0712 As discussed I used <modus-dropdown> component to create dynamic button and using <modus-button-menu> I show the slot on the click of that button

2023-06-23 09:02 UTC, Sanket8793 reviewed
@msankaran0712 As discussed I used component to create dynamic button and using I show the slot on the click of that button

2023-06-23 09:02 UTC, Sanket8793 commented on stencil-workspace/src/components/modus-navbar/button-list/modus-navbar-button-list.tsx
> +        </div>
@msankaran0712 As discussed I used <modus-dropdown> component to create dynamic button and using <modus-button-menu> I show the slot on the click of that button

2023-06-23 09:11 UTC, Sanket8793 commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +  }
Click the button I have stored the button id in openButtonMenuId state, so that we can use that state to close the menu when we click on other button icons and also manage to show and hide popup using button's menu property.

2023-06-23 09:12 UTC, Sanket8793 commented on stencil-workspace/src/components/modus-navbar/button-list/modus-navbar-button-list.tsx
> +        </div>
@msankaran0712 As discussed I have used modus-dropdown component to create a dynamic button and using modus-button-menu I show the slot on click of that button.

2023-06-23 09:15 UTC, Sanket8793 commented on stencil-workspace/src/components/modus-navbar/button-list/modus-navbar-button-list.tsx
> +        </div>
@msankaran0712 As discussed I have used modus-dropdown component to create a dynamic button and using modus-button-menu I show the slot on click of that button.

2023-06-23 09:19 UTC, Sanket8793 commented on stencil-workspace/src/components/modus-navbar/button-list/modus-navbar-button-list.tsx
> +        </div>
@msankaran0712 As discussed I have used modus-dropdown component to create a dynamic button and using modus-button-menu I show the slot on click of that button.

2023-06-23 09:24 UTC, Sanket8793 commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +  }
on button Click event I have stored the button id in openButtonMenuId state, so that we can use that state to close the menu when we click on other button icons and also manage to show and hide popup using button's menu property

2023-06-23 09:26 UTC, Sanket8793 commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +    }
Close the dynamic opened menu when we click another button using the openButtonMenuId state

2023-06-26 07:58 UTC, msankaran0712 requested changes
Bugs;
1. When a button menu is open, clicking anywhere on the document closes the menu, but the icon stays highlighted until I click another icon.

2023-06-26 07:58 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-navbar/button-list/modus-navbar-button-list.tsx
> +  orderIndex: number;
please remove `orderIndex` if not used here.

2023-06-26 07:58 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-navbar/button-list/modus-navbar-button-list.tsx
> +    buttonsList: ModusNavbarButton[];
just `buttons` should suffice, no need to append `List`

2023-06-26 07:58 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-navbar/button-list/modus-navbar-button-list.tsx
> +export interface ModusNavbarButton {
Any type that is exposed to user-end should be added to `stencil-workspace\src\interfaces.d.ts`

2023-06-26 07:58 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-navbar/button-list/modus-navbar-button-list.tsx
> +      buttons?.map((button, index) =>
null check is not needed, as we default it with an empty array in the above line of code

2023-06-26 07:58 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-navbar/button-list/modus-navbar-button-list.tsx
> +          <modus-dropdown toggle-element-id={'toggleElement-' + index}>
Id `navbar-button-<index>` would give a better context rather than `toggleElement`. Just a thought.

2023-06-26 07:58 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-navbar/button-list/modus-navbar-button-list.tsx
> +            {button.menu === "pop-out" && (
We need to hide the menu using `display: none` rather than rendering it conditionally because it happens when a slot is dynamically created; it does not render well for the first time, which is the same issue you are facing now. Showing below the edited code. You can use it.

![image](https://github.com/trimble-oss/modus-web-components/assets/50131391/40b9b5f5-3e06-4273-a3ec-d48ff64a7059)

![image](https://github.com/trimble-oss/modus-web-components/assets/50131391/88604490-ad8a-4bd7-811c-644b9c60f84f)

![image](https://github.com/trimble-oss/modus-web-components/assets/50131391/715bed88-a7ab-4925-9afd-f172987f2820)

2023-06-26 07:58 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-navbar/button-menu/modus-navbar-button-menu.scss
> +.open-menu {
Can't we keep `top: 0` in the  `.button-menu` class?  `open-menu` is not conditional anyway.

2023-06-26 07:58 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-navbar/button-menu/modus-navbar-button-menu.scss
> +  .title {
where is `.title` class applied ?

2023-06-26 08:31 UTC, msankaran0712 requested changes

2023-06-26 08:31 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +      button.menu = 'pop-out';
I don't think we really need this `pop-out` logic because

- I don't see any use case where Navbar shows a menu open by default, even if it does Modus Dropdown does not support it yet.
- Modus Dropdown takes care of opening and closing the menu. At the moment, there seems to be an issue with the dropdown not closing when the button is clicked. However, this can be resolved.

2023-06-26 09:59 UTC, msankaran0712 requested changes

2023-06-26 09:59 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-navbar/button-menu/modus-navbar-button-menu.tsx
> +      <div class={`button-menu open-menu ${direction}`} onClick={(event) => event.preventDefault()}>
why prevent default event here?

2023-06-26 09:59 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-navbar/modus-navbar.scss
> +  .icon-add {
where is `.icon-add` is used?

2023-06-26 09:59 UTC, msankaran0712 commented on stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar-storybook-docs.mdx
> +    { id:'addMenu', icon: 'add' }
If possible, please add one more button, easy to see and test multiple dynamic icons

2023-06-26 09:59 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +      button.menu = 'pop-out';
Am  open for discussion

2023-06-26 10:01 UTC, msankaran0712 commented
> > ![image](https://user-images.githubusercontent.com/50131391/247045558-8aae44c9-32d5-45f9-8f49-7f5000226802.png)
> > We need to make sure we add the implementation details about how to add a dynamic menu
> 
> Hi @msankaran0712, We haven't decided on the approach to show the menu on button click, so I will add the implementation details after we finalize that

I am fine with the existing functionality, if there is nothing pending please go ahead and make the change

2023-06-26 11:26 UTC, msankaran0712 requested changes
Also, can you please fix the existing icon's dropdown positioning? Add icon is correct. We have to fix existing icons, notifications, apps, etc

![chrome_5hUw3MPaTY](https://github.com/trimble-oss/modus-web-components/assets/50131391/b82f876c-e8c2-4e95-969d-503ba28dafb2)

2023-06-26 11:31 UTC, Sanket8793 commented on stencil-workspace/src/components/modus-navbar/button-menu/modus-navbar-button-menu.scss
> +.open-menu {
No we can't,
We need to override the custom-navbar-menu style for top Property that we got by importing modus-navbar.vars

2023-06-26 11:31 UTC, Sanket8793 commented on stencil-workspace/src/components/modus-navbar/button-menu/modus-navbar-button-menu.scss
> +  .title {
Not Required, Will remove from the code

2023-06-26 11:44 UTC, Sanket8793 commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +      button.menu = 'pop-out';
@msankaran0712  Yes you are right without pop-out logic, Modus Dropdown should continue to work as expected.
But we can't identified for which icon button we clicked, and we can't applied pressed class for to apply CSS for Active button because that was happened based on the pop-out

2023-06-26 11:49 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-navbar/button-menu/modus-navbar-button-menu.scss
> +.open-menu {
I have tried it, and it was working for me,

![image](https://github.com/trimble-oss/modus-web-components/assets/50131391/6b6d712f-5fc7-439c-967c-849879a41c98)

2023-06-26 11:50 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +      button.menu = 'pop-out';
okay

2023-06-26 12:05 UTC, Sanket8793 commented on stencil-workspace/src/components/modus-navbar/modus-navbar.scss
> +  .icon-add {
give style to the add icon that we show in the navbar

2023-06-26 14:30 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-navbar/modus-navbar.scss
> +  .icon-add {
The purpose of having a dynamic menu is to make Modus Navbar handle any icon, so the Navbar should not have icon-specific code unless there is no other way.

We cannot keep adding icons here for adding style.

2023-06-30 18:17 UTC, msankaran0712 approved these changes

2023-06-30 18:17 UTC, msankaran0712 commented
Created another PR https://github.com/trimble-oss/modus-web-components/pull/1477 because of the failing Netlify

2023-06-30 18:17 UTC, closed without merging