Column visibility feature development
trimble-oss/modus-web-components pull request #1342
Opened 2023-05-25 11:03 UTC by sankarNous

## Description

- Have added the Column visibility feature
- Missing Column resize keyboard navigation info added to the storybook.

References [#1111](https://github.com/trimble-oss/modus-web-components/issues/1111)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

2023-05-25 11:30 UTC, msankaran0712 requested changes
Storybook,

1. Clicking outside the table is not closing the column visibility panel
2. Modus checkbox should be used 
3. Looks like arguments are not passed correctly so the controls tab is not editable
4. Make the configuration for show/hide the panel visible in controls tab

2023-05-29 09:05 UTC, sankarNous commented
> Storybook,
> 
> 1. Clicking outside the table is not closing the column visibility panel
> 2. Modus checkbox should be used
> 3. Looks like arguments are not passed correctly so the controls tab is not editable
> 4. Make the configuration for show/hide the panel visible in controls tab

2023-05-29 09:51 UTC, msankaran0712 requested changes

2023-05-29 09:51 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-data-table/modus-data-table.vars.scss
> +$modus-primary-color: var(--modus-primary, #019aeb) !default;
which was the variable name changed? It looked right before

2023-05-29 09:51 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-data-table/modus-data-table.vars.scss
> +$modus-menu-dropdown-color: var(--modus-menu-dropdown-color, #d0d0d7) !default;
css variable "--modus-menu-dropdown-color" is not found in themes.scss, where is the variable defined ?

2023-05-29 09:51 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-data-table/modus-data-table.vars.scss
> +$modus-menu-dropdown-bg: var(--modus-body-bg, #fff) !default;
where did you refer for the color codes for menu dropdown ?

2023-05-29 09:51 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-data-table/modus-data-table.tsx
> +  /** (Optional) To display column visibility. */
Comments is not clear about what the configuration does. I would suggest, "To display a menu to select columns for visibility".

2023-05-29 10:03 UTC, msankaran0712 requested changes
Why there is no slot option to add external elements in the header panel ?

2023-05-29 10:03 UTC, msankaran0712 commented on stencil-workspace/src/components/icons/icon-horizontal-ellipsis.tsx
> +    class="mi-outline mi-more-horizontal"
@sankarNous Please remove these css classes, I just confirmed it with @coliff.

2023-05-29 10:10 UTC, sankarNous commented on stencil-workspace/src/components/modus-data-table/modus-data-table.vars.scss
> +$modus-menu-dropdown-color: var(--modus-menu-dropdown-color, #d0d0d7) !default;
I think it missed. will add it

2023-05-29 11:07 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-data-table/modus-data-table.vars.scss
> +$modus-primary-color: var(--modus-primary, #019aeb) !default;
Closing the comment, as primary color being used in multiple places inside the table component

2023-05-30 05:52 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-data-table/models/modus-header-panel.ts
> +export interface ModusHeaderPanel {
Rename it to `ModusDataTableHeaderPanel`

2023-05-30 09:41 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-data-table/modus-data-table.tsx
> +              <slot name="headerLeft"></slot>
@sankarNous 

Edited the above comment: `panelGroupLeft` and `panelGroupRight`

2023-05-30 09:42 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-data-table/parts/modus-data-table-header-panel/modus-data-table-header-panel.scss
> +.menu-container {
@sankarNous 

this comment is not valid anymore, because you can find the correct CSS name in the files attached.

2023-05-30 10:12 UTC, msankaran0712 requested changes

2023-05-30 10:12 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-data-table/modus-data-table.tsx
> + * @slot panelLeft - Slot for header panel left section.
slots are not in the same comments block

2023-05-30 10:12 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-data-table/parts/panel/modus-data-table-dropdown-menu.tsx
> +    <div class="menu-container">
Please update all the css class names in this component as per the file I shared

2023-05-30 10:12 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-data-table/parts/panel/modus-data-table-panel/modus-data-table-panel.scss
> +@import '../../../modus-data-table.vars';
From the zip file, refer the `modus-data-table-dropdown-menu.tsx` for css classes

2023-05-30 10:12 UTC, msankaran0712 commented on stencil-workspace/storybook/stories/components/modus-data-table/modus-data-table-storybook-docs.mdx
> +- The newly added `tablePanel`, which has 2 parts with 2 slots each (panelLeft, panelRight), enables you to insert customized content. If column-visibility is turned on, the meatball menu will be sho
slot names are supposed to be panelGroupLeft and panelGroupRight.

2023-05-30 10:26 UTC, msankaran0712 requested changes

2023-05-30 10:26 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-data-table/parts/panel/modus-data-table-dropdown-menu.tsx
> +                <label>
why there is a `label` tag here ?

2023-05-30 10:26 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-data-table/parts/panel/modus-data-table-panel/modus-data-table-panel.tsx
> +  @State() dropdownMenu = false;
rename it to showDropdownMenu

2023-05-30 10:26 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-data-table/parts/panel/modus-data-table-panel/modus-data-table-panel.tsx
> +          <div>
why there is div wrapper for slot

2023-05-30 10:26 UTC, msankaran0712 commented on stencil-workspace/storybook/stories/components/modus-data-table/modus-data-table-storybook-docs.mdx
> +Column visibility allows the user to show or hide the columns of a table.
We need to simplify this text

2023-05-30 10:33 UTC, msankaran0712 requested changes

2023-05-30 10:33 UTC, msankaran0712 commented on stencil-workspace/storybook/stories/components/modus-data-table/modus-data-table-storybook-docs.mdx
> +  summary-row="true">
please set summary row to false

2023-05-30 11:39 UTC, sankarNous commented on stencil-workspace/src/components/modus-data-table/parts/panel/modus-data-table-dropdown-menu.tsx
> +                <label>
missed while code cleanup

2023-05-30 11:39 UTC, sankarNous commented on stencil-workspace/src/components/modus-data-table/parts/panel/modus-data-table-panel/modus-data-table-panel.tsx
> +          <div>
missed it while code cleanup

2023-06-01 06:25 UTC, msankaran0712 requested changes
1. In Storybook:

Users can control the visibility of columns in one place using `panelOptions`. By setting a value, a panel is added above the table with a meatball icon at the right corner, and clicking on it shows a dropdown menu with the columns for selection. Additionally, users can also use `slot='panelGroupLeft' and slot='panelGroupRight'` to add content in the panel.

2. add `ModusDataTablePanelOptions` and `ModusDataTableColumnVisibility` in Types section

2023-06-01 08:15 UTC, msankaran0712 approved these changes

2023-06-01 10:24 UTC, msankaran0712 approved these changes

2023-06-02 06:39 UTC, merged