Fixing modus select issue
trimble-oss/modus-web-components pull request #1375
Opened 2023-06-02 10:09 UTC by hemantk1325

## Description

Fixing modus select issue and using native select for select dropdown instead of div.

References #559 , #1334 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

2023-06-02 20:16 UTC, ryan-henness-trimble commented on stencil-workspace/src/components/modus-select/modus-select.tsx
> +  @Prop({ mutable: true }) value: unknown;
I know we were mutating the `value` input previously, but I'm not so sure we should be doing that

If we want to change the value of an input internally, I think we should represent that input with internal state. We then could mutate that internal state instead

@msankaran0712 thoughts on this?

2023-06-02 20:16 UTC, ryan-henness-trimble commented on stencil-workspace/src/components/modus-select/modus-select.scss
> +      font-weight: 400;
Is the `font-weight` attribute necessary?

2023-06-02 20:16 UTC, ryan-henness-trimble commented on stencil-workspace/src/components/modus-select/modus-select.tsx
> +import { Component, Event, EventEmitter, h, Prop } from '@stencil/core';
This component has a black border when it is interacted with via tabbing in Chrome. When the component is tabbed to, it should have a blue bottom border

It looks like a good example of this working correctly is the Text Input component

2023-06-02 20:16 UTC, ryan-henness-trimble commented on stencil-workspace/src/components/modus-select/modus-select.tsx
> +  @Prop({ mutable: true }) value: unknown;
We could do this with a `@Watch` function that updates the internal state when the prop updates

2023-06-02 20:16 UTC, ryan-henness-trimble commented on stencil-workspace/src/components/modus-select/modus-select.tsx
> +            onChange={(event) => {
We should add functions for logic within the markup like this

2023-06-07 07:40 UTC, sankarNous commented on stencil-workspace/storybook/stories/components/modus-select/modus-select-storybook-docs.mdx
> +| `size`               | `size`                 | (optional) The input's size.                         | `"large"    | "medium"`   |
is 'Large' datatype?

2023-06-07 08:56 UTC, msankaran0712 requested changes

2023-06-07 08:56 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-select/modus-select.tsx
> +      this.options.length > 0 &&
`this.options?.`

2023-06-07 08:56 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-select/modus-select.tsx
> +            disabled={this.disabled || this.options.length === 0}
why to disable it when no options?

2023-06-07 08:56 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-select/modus-select.scss
> +      font-size: $rem-14px;
font size should be $rem-12px. Refer to https://modus.trimble.com/components/web/inputs/styles/ and please verify for font size for label, select text and placeholder text for 'medium'(default) and 'large' sizes

2023-06-07 08:56 UTC, msankaran0712 commented on stencil-workspace/storybook/stories/components/modus-select/modus-select-storybook-docs.mdx
>  <modus-select label="Select Demo 4" valid-text="Valid demo"></modus-select>
Please add one example for large size Select

2023-06-07 08:56 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-select/modus-select.scss
>        height: $btn_height;
where is $btn_height defined ?

2023-06-07 08:56 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-select/modus-select.scss
> +select:focus {
On focus, Select input should only have a bottom blue border, no full border, refer https://modus.trimble.com/components/web/inputs/styles/#behaviors

2023-06-07 08:56 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-select/modus-select.scss
> +select.error:focus {
no need for a full border for error and valid states too. Please remove this CSS block.

2023-06-07 08:56 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-select/modus-select.scss
> +}
`.sub-text` font size should be $rem-12px

2023-06-07 09:00 UTC, msankaran0712 commented on stencil-workspace/storybook/stories/components/modus-select/modus-select-storybook-docs.mdx
> +| `size`               | `size`                 | (optional) The input's size.                         | `"large"    | "medium"`   |
@sankarNous `large` and `medium` are options for `size` property

2023-06-07 09:03 UTC, msankaran0712 commented on stencil-workspace/storybook/stories/components/modus-select/modus-select-storybook-docs.mdx
> +| `size`               | `size`                 | (optional) The input's size.                         | `"large"    | "medium"`   |
@hemantk1325 please copy the properties section from README again and paste it into the storybook

Expected:
![image](https://github.com/trimble-oss/modus-web-components/assets/50131391/5b3cfbf0-81cd-4719-8456-29b33d1d5492)

2023-06-08 05:34 UTC, hemantk1325 commented on stencil-workspace/src/components/modus-select/modus-select.e2e.ts
> +xdescribe('modus-select', () => {
added test cases

2023-06-08 05:35 UTC, hemantk1325 commented on stencil-workspace/src/components/modus-select/modus-select.scss
> +}
done

2023-06-08 05:35 UTC, hemantk1325 commented on stencil-workspace/src/components/modus-select/modus-select.scss
> +select.error:focus {
made the changes

2023-06-08 05:35 UTC, hemantk1325 commented on stencil-workspace/src/components/modus-select/modus-select.scss
> +select:focus {
done

2023-06-08 05:36 UTC, hemantk1325 commented on stencil-workspace/src/components/modus-select/modus-select.scss
>        height: $btn_height;
done

2023-06-08 05:36 UTC, hemantk1325 commented on stencil-workspace/storybook/stories/components/modus-select/modus-select-storybook-docs.mdx
>  <modus-select label="Select Demo 4" valid-text="Valid demo"></modus-select>
Added example for large size

2023-06-08 05:36 UTC, hemantk1325 commented on stencil-workspace/src/components/modus-select/modus-select.tsx
> +      this.options.length > 0 &&
done

2023-06-08 05:37 UTC, hemantk1325 commented on stencil-workspace/src/components/modus-select/modus-select.tsx
> +  renderText(): JSX.Element | null {
done

2023-06-08 05:37 UTC, hemantk1325 commented on stencil-workspace/src/components/modus-select/modus-select.tsx
> +    if (this.errorText) {
done

2023-06-08 05:37 UTC, hemantk1325 commented on stencil-workspace/src/components/modus-select/modus-select.tsx
>  // eslint-disable-next-line
done

2023-06-08 05:37 UTC, hemantk1325 commented on stencil-workspace/src/components/modus-select/modus-select.tsx
> +  h,
done

2023-06-08 05:37 UTC, hemantk1325 commented on stencil-workspace/storybook/stories/components/modus-select/modus-select-storybook-docs.mdx
> +| `size`               | `size`                 | (optional) The input's size.                         | `"large"    | "medium"`   |
done

2023-06-08 10:52 UTC, msankaran0712 commented on stencil-workspace/storybook/stories/components/modus-select/modus-select.stories.tsx
> +    id="select-demo-5"
Please give the label as "Large Select"

2023-06-08 11:03 UTC, msankaran0712 requested changes
Also, Increase the container height in storybook 
![image](https://github.com/trimble-oss/modus-web-components/assets/50131391/de870208-ed03-46ab-b621-f301f78c01da)

2023-06-09 07:44 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-select/modus-select.tsx
> +  @Prop({ mutable: true }) value: unknown;
@ryan-henness-trimble it looks like in `modus-text-input`  we are mutating the `value` inside the component without marking it as `mutable`

2023-06-09 08:54 UTC, hemantk1325 commented on stencil-workspace/src/components/modus-select/modus-select.tsx
> +      this.options.length > 0 &&
done

2023-06-09 08:55 UTC, hemantk1325 commented on stencil-workspace/src/components/modus-select/modus-select.tsx
> +            disabled={this.disabled || this.options.length === 0}
done

2023-06-09 08:55 UTC, hemantk1325 commented on stencil-workspace/src/components/modus-select/modus-select.scss
> +      font-size: $rem-14px;
done

2023-06-09 08:55 UTC, hemantk1325 commented on stencil-workspace/storybook/stories/components/modus-select/modus-select.stories.tsx
> +    id="select-demo-5"
done

2023-06-09 10:43 UTC, msankaran0712 commented
Closing the PR due to branching issues

2023-06-09 10:43 UTC, closed without merging

2023-06-09 10:43 UTC, msankaran0712 commented
Created a new PR for the issue https://github.com/trimble-oss/modus-web-components/pull/1407

2023-06-09 10:52 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-select/modus-select.tsx
> +  @Prop({ mutable: true }) value: unknown;
@ryan-henness-trimble We have close this PR due to some branch issues and please check the new PR https://github.com/trimble-oss/modus-web-components/pull/1407