Column visibility functionality development
trimble-oss/modus-web-components pull request #1378
Opened 2023-06-05 05:09 UTC by sankarNous

## Description

Column visibility functionality development - making the apply and cancel buttons usable to control the display of columns

References #[1212](https://github.com/trimble-oss/modus-web-components/issues/1212)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

2023-06-13 10:03 UTC, msankaran0712 requested changes
1. Rename `stencil-workspace\src\components\modus-data-table\models\modus-data-table-column-visibility.ts` to `modus-data-table-columns-visibility` 
2. Rename the column visibility prop in `stencil-workspace\src\components\modus-data-table\models\modus-data-table-panel-options.ts`
3.

2023-06-13 11:45 UTC, msankaran0712 requested changes
In `stencil-workspace\src\components\modus-data-table\parts\panel\modus-data-table-panel\modus-data-table-panel.tsx` 
1. Line 21, rename `panelOptions` to `options`
2. Please convert `modus-data-table-dropdown-menu` to a class component
 - this way, we can avoid dropdown state management logic inside the panel
4. Line 42, rename the method to `setVisibleColumns` and create a separate method to clear the state. It is confusing when combining both the logic inside one method.
5. In Line 54, the null check is not needed because you are already checking it at line 53 and rendering the dropdown only if it is not null

2023-06-14 06:24 UTC, msankaran0712 requested changes

2023-06-14 06:24 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-data-table/parts/panel/modus-data-table-panel/modus-data-table-panel.tsx
>    @Listen('click', { target: 'document' })
We can move this listener to the dropdown menu class component

2023-06-14 06:24 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-data-table/parts/panel/modus-data-table-panel/modus-data-table-panel.tsx
>    @State() showDropdownMenu = false;
state name can be simplified to "showDropdown"

2023-06-14 06:24 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-data-table/parts/panel/modus-data-table-panel/modus-data-table-panel.tsx
Line 20, simplify the comments to "Table Panel options", it should be understood because we have explained it briefly in the `modus-data-table.tsx`

2023-06-14 06:24 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-data-table/parts/panel/modus-data-table-panel/modus-data-table-panel.tsx
> +  @State() columnsVisibilityState = {} as {
I would use a simple string array to store the checked columns or use a `Map<string, boolean>` type instead of `{string:string}`

2023-06-14 06:24 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-data-table/parts/panel/modus-data-table-dropdown-menu.tsx
> +  let dropdownMenuIconDiv: HTMLInputElement;
please rename "dropdownMenuIconDiv" to "menuIconContainerRef" and the type should `HTMLDivElement`

2023-06-14 06:24 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-data-table/parts/panel/modus-data-table-dropdown-menu.tsx
> +      if (typeof columnsVisibilityState[column.id] === 'boolean') {
Why do we need this if clause?

2023-06-14 06:24 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-data-table/parts/panel/modus-data-table-dropdown-menu.tsx
> +      (event.key.toLowerCase() === EnterKey ||
Please eep the event.key.toLowerCase() in a constant

2023-06-14 06:24 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-data-table/parts/panel/modus-data-table-dropdown-menu.tsx
> +    if (event.key.toLowerCase() === TabKey && !event.shiftKey) {
why do we  check shift key ?

2023-06-14 07:02 UTC, msankaran0712 requested changes

2023-06-14 07:02 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-data-table/parts/panel/modus-data-table-dropdown-menu.tsx
>    return (
Please always try to break up the code in the Render function and use functional components, constants. A good example for using constants, https://github.com/trimble-oss/modus-web-components/blob/main/stencil-workspace/src/components/modus-select/modus-select.tsx

2023-06-14 10:39 UTC, sankarNous commented on stencil-workspace/src/components/modus-data-table/parts/panel/modus-data-table-dropdown-menu.tsx
> +    if (event.key.toLowerCase() === TabKey && !event.shiftKey) {
When we use shiftkey + tab to go back, we shouldn't shut the dropdown 

2023-06-14 11:06 UTC, sankarNous commented on stencil-workspace/src/components/modus-data-table/parts/panel/modus-data-table-dropdown-menu.tsx
> +      if (typeof columnsVisibilityState[column.id] === 'boolean') {
My bad, I was testing the scenarios, forgot to update the condition

2023-06-15 10:29 UTC, sankarNous commented on stencil-workspace/src/components/modus-data-table/parts/panel/modus-data-table-panel/modus-data-table-panel.tsx
>    @Listen('click', { target: 'document' })
done

2023-06-15 10:31 UTC, sankarNous commented on stencil-workspace/src/components/modus-data-table/parts/panel/modus-data-table-dropdown-menu.tsx
>    return (
yeah I have refactored few

2023-06-15 10:31 UTC, sankarNous commented on stencil-workspace/src/components/modus-data-table/parts/panel/modus-data-table-dropdown-menu.tsx
> +              onKeyDown={(event) => closeDropdownIfFocusOut(event)}>
done

2023-06-15 10:33 UTC, sankarNous commented on stencil-workspace/src/components/modus-data-table/parts/panel/modus-data-table-dropdown-menu.tsx
> +  function applyColumnsVisibilityState() {
done

2023-06-15 10:33 UTC, sankarNous commented on stencil-workspace/src/components/modus-data-table/parts/panel/modus-data-table-dropdown-menu.tsx
> +    if (
done

2023-06-15 10:34 UTC, sankarNous commented on stencil-workspace/src/components/modus-data-table/parts/panel/modus-data-table-dropdown-menu.tsx
> +  function dropdownMenuOnKeyDown(
done

2023-06-15 10:34 UTC, sankarNous commented on stencil-workspace/src/components/modus-data-table/parts/panel/modus-data-table-dropdown-menu.tsx
> +      (event.key.toLowerCase() === EnterKey ||
done

2023-06-15 10:34 UTC, sankarNous commented on stencil-workspace/src/components/modus-data-table/parts/panel/modus-data-table-dropdown-menu.tsx
> +      if (typeof columnsVisibilityState[column.id] === 'boolean') {
Have updated the condition

2023-06-15 10:36 UTC, sankarNous commented on stencil-workspace/src/components/modus-data-table/parts/panel/modus-data-table-panel/modus-data-table-panel.tsx
> +  @State() columnsVisibilityState = {} as {
converted to Map

2023-06-15 10:36 UTC, sankarNous commented on stencil-workspace/src/components/modus-data-table/parts/panel/modus-data-table-panel/modus-data-table-panel.tsx
done

2023-06-15 10:36 UTC, sankarNous commented on stencil-workspace/src/components/modus-data-table/parts/panel/modus-data-table-panel/modus-data-table-panel.tsx
>    @State() showDropdownMenu = false;
done

2023-06-15 10:38 UTC, sankarNous commented on stencil-workspace/src/components/modus-data-table/parts/panel/modus-data-table-panel/modus-data-table-panel.tsx
>    handleClickOutside(event: MouseEvent): void {
Have tried and added this logic temporarily for you test it around if it works

2023-06-26 11:23 UTC, closed without merging

2023-06-26 11:29 UTC, sankarNous commented
We have renamed our table component. This PR might not be useful anymore.