Fix Navbar Main Menu height
trimble-oss/modus-web-components pull request #1400
Opened 2023-06-06 17:41 UTC by ryan-henness-trimble

## Description

The goal of this work was to modify the Main Menu to occupy the remaining portion of the screen. By implementing this change, the Main Menu is now positioned directly below the Navbar and occupies the rest of the viewport. This enhancement allows for the placement of items like notifications, messages, and other elements on top of the Navbar while maintaining the remaining screen height for the Main Menu

The main approach involved was to ensure that the Main Menu dynamically adjusts its container's layout. This layout is set when the component initially loads and also when any observed changes occur in the DOM. This work is done by the Main Menu itself

To address alignment issues within the Shadow DOM, I moved the Main Menu component outside of the navbar-button div. This adjustment resolved the problems caused by the misalignment of the Shadow DOM

References https://github.com/trimble-oss/modus-web-components/issues/1345

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Manually tested this in the Stencil playground, Storybook, and in our Work Center application

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules
- [X] I have checked my code and corrected any misspellings

2023-06-06 19:38 UTC, ryan-henness-trimble commented on stencil-workspace/src/components/modus-navbar/modus-navbar.spec.ts
> -    expect(root).toEqualHtml(`
Since the `componentId` generated in the navbar is random, this test was not stable
Since the test's purpose is to check whether the navbar is rendering, I think it is sufficient to check that we've got our `<nav>` element within the root's Shadow DOM

2023-06-06 21:04 UTC, leohaughton approved these changes
Looks good to me.

**Non-Blocking suggestion:**
I would have expected to see some unit tests corresponding to `modus-navbar-main-menu.tsx`. For example, update the `updateContainerLayout` method could probably be tested. However, I am not familiar with your test strategy in this repo so I will let you make the call.

2023-06-06 21:16 UTC, ryan-henness-trimble commented
> Looks good to me.
> 
> **Non-Blocking suggestion:** I would have expected to see some unit tests corresponding to `modus-navbar-main-menu.tsx`. For example, the `updateContainerLayout` method could probably be tested. However, I am not familiar with your test strategy in this repo so I will let you make the call.

Good idea! I'll take some more time to think about the testing

2023-06-07 20:21 UTC, ryan-henness-trimble commented
@msankaran0712 @coliff This PR is ready for review again after changes - I added tests around the main menu per Leo's suggestion

2023-06-09 07:30 UTC, msankaran0712 requested changes

2023-06-09 07:30 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-navbar/main-menu/modus-navbar-main-menu.tsx
> +    const positionStyle = {
const positionStyle = {...this.containerLayout} 
we could have used object destructuring?

2023-06-09 07:36 UTC, msankaran0712 commented
Am not sure how it should behave in the storybook docs tab, but it looks fine in Canvas tab though.

2023-06-09 16:30 UTC, ryan-henness-trimble commented
> @ryan-henness-trimble Am not sure how it should behave in the Storybook docs tab, but it looks fine in the Canvas tab though.

Oh yea I wasn't sure either. I made it so that the main menu can never exceed the height of the window. I don't think a relatively placed navbar will really be a use case outside of the storybook examples

2023-06-09 17:02 UTC, ryan-henness-trimble commented
@msankaran0712 I implemented your suggestion, I'm gonna merge this one in

2023-06-09 17:03 UTC, merged