Modus checkbox focus state corrections - focused exclusively on the checkbox and ignoring the label
trimble-oss/modus-web-components pull request #1401
Opened 2023-06-07 05:54 UTC by sankarNous

## Description

Modus checkbox focus state corrections - focused exclusively on the checkbox and ignoring the label

References [#1393](https://github.com/trimble-oss/modus-web-components/issues/1393)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

2023-06-07 12:03 UTC, msankaran0712 requested changes

2023-06-07 12:03 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-checkbox/modus-checkbox.tsx
> +          tabIndex={tabIndexValue as number}
`tabIndex` can take string and number, so the number conversion parsing is not required.

2023-06-09 07:57 UTC, sankarNous commented on stencil-workspace/src/components/modus-checkbox/modus-checkbox.tsx
> +          tabIndex={tabIndexValue as number}
I have removed it

2023-06-09 08:00 UTC, msankaran0712 approved these changes

2023-06-12 10:04 UTC, msankaran0712 approved these changes
@coliff @ryan-henness-trimble we can close this issue if no comments

2023-06-12 10:50 UTC, coliff commented on stencil-workspace/src/components/modus-checkbox/modus-checkbox.spec.tsx
> +            <div class="checkbox"  tabindex="0">
there's an extra space before tabindex property here. (you should run Prettier!)

2023-06-12 10:50 UTC, coliff commented on stencil-workspace/src/components/modus-checkbox/modus-checkbox.scss
> +      outline:0;
there's a missing space after there `:` here. (you should run Prettier!)

2023-06-13 05:49 UTC, sankarNous commented on stencil-workspace/src/components/modus-checkbox/modus-checkbox.scss
> +      outline:0;
Thanks for noticing! addressed the above by running prettier

2023-06-13 05:50 UTC, sankarNous commented on stencil-workspace/src/components/modus-checkbox/modus-checkbox.spec.tsx
> +            <div class="checkbox"  tabindex="0">
Have removed the extra space.

2023-06-13 06:19 UTC, coliff approved these changes

2023-06-13 06:20 UTC, merged