Fixed modus select issue: Using 'select native' instead of div and fixed keyboard navigation issue
trimble-oss/modus-web-components pull request #1407
Opened 2023-06-09 10:33 UTC by hemantk1325

## Description

Fixing modus select issue and using native select for select dropdown instead of div.

References #559 ,#1334

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

2023-06-09 10:50 UTC, msankaran0712 approved these changes

2023-06-12 08:16 UTC, msankaran0712 requested changes

2023-06-12 08:16 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-select/modus-select.tsx
> +    this.internalValue = option;
@hemantk1325 I would update the internal state only when the `value` changes, not on `valueChange` because it can lead to a stale state if the consumer decides not to update the `value`. Ideally, it should behave like https://codesandbox.io/s/happy-sunset-t6c8tg?file=/demo.tsx, where the consumer gets complete control over the `value`, and the input should always render the `value`.

@ryan-henness-trimble, please correct me if you think otherwise

2023-06-12 08:16 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-select/modus-select.tsx
> +    this.internalValue = option;
@hemantk1325 that means we should update the storybook examples to update the `value` inside `valueChange`

2023-06-12 15:32 UTC, ryan-henness-trimble approved these changes

2023-06-13 05:49 UTC, msankaran0712 approved these changes

2023-06-13 11:58 UTC, coliff approved these changes

2023-06-13 11:58 UTC, coliff commented
This is great - a huge improvement - thanks!

2023-06-13 11:58 UTC, merged