Added unit test cases for data table sorting
trimble-oss/modus-web-components pull request #1434
Opened 2023-06-16 06:34 UTC by hemantk1325

## Description

Adding unit test cases for modus data table sorting feature.

References #1169 

## How Has This Been Tested?

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

2023-06-16 10:35 UTC, msankaran0712 requested changes
- Verify ascending and descending sort icons are rendered in the correct order

2023-06-16 10:35 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-data-table/modus-data-table.e2e.ts
> +  it('renders with primitive columns and data', async () => {
We don't have to write test cases for "rendering with primitive columns and data". According to our column structure, `accessorKey` is a mandatory property. Though tanstack supports, we do not officially support primitive columns and data.
please remove all the primitive data/column test cases

2023-06-16 10:35 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-data-table/modus-data-table.e2e.ts
> +    await header.click();
I think validating one-click event is sufficient, though you can use multiple clicks to validate the tooltip message on each click.

2023-06-16 10:35 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-data-table/modus-data-table.e2e.ts
> +  });
- Please add a test case to verify if the sort is false.
- Add a test case for verifying `showSortIconOnHover`
- Add a test case to verify different sorting messages 
- Add a test case to verify sorting on numerical column

2023-06-16 10:35 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-data-table/modus-data-table.e2e.ts
> +  it('should output sort data on sort icon click with sort enabled', async () => {
verify sorting descending order too

2023-06-16 10:37 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-data-table/modus-data-table.e2e.ts
> +    await header.click();
In one test case, you can verify both the sort icon and tooltip message.

2023-06-21 06:31 UTC, Ankur-Koul commented on stencil-workspace/src/components/modus-data-table/modus-data-table.e2e.ts
> +    component.setProperty('columns', [
Put this data in a constant variable and then use it.

2023-06-26 08:59 UTC, hemantk1325 commented
closing this PR. Raised a new PR to `modus-table-main` branch
https://github.com/trimble-oss/modus-web-components/pull/1462

2023-06-26 08:59 UTC, closed without merging