Integrated modus select in data table
trimble-oss/modus-web-components pull request #1486
Opened 2023-07-05 06:28 UTC by hemantk1325

## Description

Integrated modus select in data table

References #

## How Has This Been Tested?

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

2023-07-11 10:16 UTC, msankaran0712 requested changes

2023-07-11 10:16 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-table/modus-table.tsx
> +  @Prop() pageSizeList: { display: number }[] = DefaultPageSizes;
Please keep the page sizes as a simple number array. Users do not have to choose the `display` config

2023-07-11 19:42 UTC, hemantk1325 commented on stencil-workspace/src/components/modus-table/modus-table.tsx
> +  @Prop() pageSizeList: { display: number }[] = DefaultPageSizes;
done

2023-07-12 06:39 UTC, msankaran0712 approved these changes

2023-07-12 06:39 UTC, merged