Modus table scrollbar development
trimble-oss/modus-web-components pull request #1538
Opened 2023-07-17 13:17 UTC by hemantk1325

## Description

implement vertical and horizontal scrollbar for modus table.

References #1307 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

2023-07-18 07:58 UTC, msankaran0712 requested changes
https://deploy-preview-1538--modus-webcomponents.netlify.app/?path=/story/components-table--borderless

When borderless is true, header should not have bottom shadow

2023-07-18 07:58 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-table/modus-table.tsx
> +  @Prop() scrollbarHeight: string;
It should be named "maxHeight" and please update the description to "To display a vertical scrollbar when the height is exceeded"

2023-07-18 07:58 UTC, msankaran0712 commented on stencil-workspace/src/global/themes.scss
> +  --modus-table-scrollbar-thumb-color: var(--modus-gray-6);
Did we add the variables for the light theme too?

2023-07-18 08:45 UTC, msankaran0712 commented
> Summary row border is missing ![image](https://user-images.githubusercontent.com/50131391/254190270-80104355-2b3c-42f8-9bf8-7f6272b19e12.png)

Summary row should not be scrollable

2023-07-19 05:59 UTC, msankaran0712 requested changes
Remove `undefined` css class
![image](https://github.com/trimble-oss/modus-web-components/assets/50131391/b6c64988-8092-4faa-844c-e3857a3efa8e)

2023-07-19 06:02 UTC, msankaran0712 requested changes
Column reordering - only one arrow is appearing

2023-07-19 06:12 UTC, msankaran0712 requested changes
Can you please investigate why a horizontal scroll appears even when the parent and table width are the same 850px?
![image](https://github.com/trimble-oss/modus-web-components/assets/50131391/c6c25c0b-7e0a-46ad-b175-bd4d1cde33cf)

2023-07-19 06:15 UTC, msankaran0712 requested changes
Should be updated

![image](https://github.com/trimble-oss/modus-web-components/assets/50131391/3d16576f-3e06-482f-9d3c-4e4b85fc6626)

2023-07-19 06:15 UTC, msankaran0712 commented on stencil-workspace/src/global/themes.scss
> +  --modus-table-scrollbar-thumb-color: var(--modus-gray-6);
I think the variables are still missing for the light theme

2023-07-19 12:10 UTC, hemantk1325 commented on stencil-workspace/src/global/themes.scss
> +  --modus-table-scrollbar-thumb-color: var(--modus-gray-6);
added variable for light theme

2023-07-19 13:55 UTC, HarshithaNous commented
Below are my observations:

Borderless - Keyboard navigation - To resize the column, hit on tab key and then hit on Enter key, the blue highlight that is displayed to proceed with the resizing does not appear for header row. After, the left or right arrow key is used to resize the blue highlight on the header row is displayed. Please refer the below screenshots:
![image](https://github.com/trimble-oss/modus-web-components/assets/129380495/8fd3582c-9548-44b6-9cbf-0dc32201313c)
![image](https://github.com/trimble-oss/modus-web-components/assets/129380495/651925d4-44c1-4c28-b63b-9a2390e9b19a)

2023-07-19 14:25 UTC, HarshithaNous commented
Need clarification on the below:
Style and color of scroll bar
Scroll appears for header
Keyboard interaction

2023-07-20 05:38 UTC, HarshithaNous commented
In order to verify the horizontal scroll bar when Full width is true.. we require max width control.

2023-07-21 07:22 UTC, msankaran0712 requested changes

2023-07-21 07:22 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-table/modus-table.tsx
> +          style={{
Can we move the below style to a constant?

2023-07-21 07:22 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-table/modus-table.scss
> +      &.row-header-bottom-shadow {
Instead of having "row-header-bottom-shadow", please use the existing CSS class `borderless` and `cell-borderless`. 

I think it will be something like below,

![image](https://github.com/trimble-oss/modus-web-components/assets/50131391/d83d9ac1-9ecb-4bb9-b877-9f5d8f835255)

![image](https://github.com/trimble-oss/modus-web-components/assets/50131391/282e0f3a-04b7-475a-a6ed-4e2ee1587373)

2023-07-21 07:22 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-table/modus-table.spec.tsx
> +      <table style="width: 0px; table-layout: fixed;">
Why is there a `0px` width? if possible, make the code change so if value is 0px/null, you do not need to add a `width` style

2023-07-21 07:22 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-table/modus-table.tsx
> +    const borderlessTableStyle = !this.displayOptions?.cellBorderless ? 'row-header-bottom-shadow' : '';
we need to avoid a new class if existing classes can be resused

2023-07-21 14:15 UTC, HarshithaNous commented
Below are my observations:
**Observation 1:**
On borderless example - when columns are resized there is no borderline on the right for data rows and header rows..
 Note- Summary row has the border on the right
![image](https://github.com/trimble-oss/modus-web-components/assets/129380495/48e1c7d5-5cae-4316-83c7-126f8e23d264)
Display Options on Controls section:
![image](https://github.com/trimble-oss/modus-web-components/assets/129380495/05f0cc8f-57cf-4d72-90cd-589e4d1e8da6)

**Observation 2:**
Border line on Summary row is missing on Default, Hover,  and Column Visibility examples
![image](https://github.com/trimble-oss/modus-web-components/assets/129380495/b8b2e2d6-92d1-4103-b177-a004d276c8c0)
![image](https://github.com/trimble-oss/modus-web-components/assets/129380495/0e355f2a-0b36-4d59-88a7-c4f9725738bf)
![image](https://github.com/trimble-oss/modus-web-components/assets/129380495/a9f26f7d-c696-4123-9223-a3224cec2a24)

2023-07-24 09:44 UTC, msankaran0712 commented
Column resize border seems to be beneath the row borders,

![image](https://github.com/trimble-oss/modus-web-components/assets/50131391/6577f6d3-cee9-4a04-87dd-cd6937e9e819)

2023-07-25 09:33 UTC, msankaran0712 requested changes

2023-07-25 09:33 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-table/parts/modus-table-summary-row.tsx
> +  borderLessTable,
rename the prop to `borderlessOptions`

2023-07-26 06:00 UTC, msankaran0712 approved these changes

2023-07-26 06:00 UTC, merged