Expandable rows in Modus Table
trimble-oss/modus-web-components pull request #1544
Opened 2023-07-18 10:45 UTC by Ankur-Koul

## Description

References #

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

2023-07-19 07:53 UTC, msankaran0712 requested changes
Able to hide first column 
![image](https://github.com/trimble-oss/modus-web-components/assets/50131391/43f93227-33d1-4445-b8a0-23f7f831dd5f)

2023-07-19 08:27 UTC, Ankur-Koul commented
> * Please increase the number of rows for the expandable row page,
Now there are 7 rows in total.
> * I feel we need a better name for nested rows, in place of `subRows`. Simply naming it `rows` sounds better.
`subRows` is a property of `tanstack`, we can not change this.
> * Show at least 4 levels
Done

2023-07-19 08:28 UTC, Ankur-Koul commented
> 1. Please increase the number of rows for the expandable row page,
> 2. I feel we need a better name for nested rows, in place of `subRows`. Simply naming it `rows` sounds better.
> 3. Show at least 4 levels

Hi

2023-07-19 09:29 UTC, HarshithaNous commented
Below are my observations:
**Scenario 1:**
When the page view is set to 2 or 5, and the parent row is expanded the child rows are moved to next page. We expect the child rows to be displayed along with the parent row. Please refer the below screenshots:
![image](https://github.com/trimble-oss/modus-web-components/assets/129380495/c92259db-9f63-40dd-b628-6a707c39e32b)
![image](https://github.com/trimble-oss/modus-web-components/assets/129380495/34ce8144-29e9-4560-ad81-9e351b2b0127)

**Scenario 2:**
Showing results displays an incorrect count as "Showing result1-20 of 7". The Total count should be more than the results displayed per page
![image](https://github.com/trimble-oss/modus-web-components/assets/129380495/ce91ef9f-df01-482a-9cb3-8a5bf8d2e4ce)

2023-07-19 13:44 UTC, HarshithaNous commented
There is no color code specified to verify the color of the expandable rows

2023-07-21 07:36 UTC, msankaran0712 requested changes

2023-07-21 07:36 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-table/modus-table.tsx
> +  @Watch('isExpand') onChangeOfIsExpand() {
I suggest keeping the option name `rowsExpandable`, as it is clear and easy to understand.

2023-07-21 07:36 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-table/utilities/drag-and-drop.utility.tsx
>    columnReorder = false;
I would suggest renaming the class name to "table-header-drag-drop", as the class is all about dragging only headers

2023-07-21 09:41 UTC, msankaran0712 approved these changes

2023-07-21 09:41 UTC, merged