Added functionality for hyperlink
trimble-oss/modus-web-components pull request #1575
Opened 2023-07-25 06:42 UTC by Ankur-Koul

## Description

Added a new column datatype to display hyperlinks.

References #1524 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

2023-07-25 11:08 UTC, msankaran0712 requested changes

2023-07-25 11:08 UTC, msankaran0712 commented on stencil-workspace/storybook/stories/components/modus-table/modus-table.stories.tsx
> +Hyperlink.args = { ...DefaultArgs, columns: updateColumnWithType(), data: makeData(true, 5) };
I would suggest adding Hyperlink specific code changes by iterating through the column and data objects here instead of making changes inside the helper methods for better code readability

Example, 
const columns = DefaultColumns.map(col => col.id === 'progress' ? {...col, dataType: 'link'} : col);
const data = makeData(5).map(....);
Hyperlink.args = { ...DefaultArgs, columns), data};

2023-07-25 11:08 UTC, msankaran0712 commented on stencil-workspace/storybook/stories/components/modus-table/modus-table.stories.tsx
> +    progress: link ? { display: 'Click me', url: 'https://modus.trimble.com/components/web/' } : Math.floor(rand * 100), // Link
I suggest adding conditions inside helper methods only if no other option exists. Instead, could you try to manipulate the columns and data objects from the example itself?

2023-07-25 11:15 UTC, msankaran0712 requested changes

2023-07-25 11:15 UTC, msankaran0712 commented on stencil-workspace/storybook/stories/components/modus-table/modus-table.stories.tsx
> +    progress: link ? { display: 'Click me', url: 'https://modus.trimble.com/components/web/' } : Math.floor(rand * 100), // Link
Also, once you have the option to set an open link in a new tab, please use it here.

2023-07-25 11:22 UTC, msankaran0712 commented on stencil-workspace/storybook/stories/components/modus-table/modus-table.stories.tsx
> +    progress: link ? { display: 'Click me', url: 'https://modus.trimble.com/components/web/' } : Math.floor(rand * 100), // Link
It would be good if you could add a link text like the below one, maybe include an `email` column
![image](https://github.com/trimble-oss/modus-web-components/assets/50131391/84de90cb-a1eb-432c-80f8-de390a05acb5)

2023-07-26 09:23 UTC, Ankur-Koul commented on stencil-workspace/src/components/modus-table/modus-table.tsx
> +  @Event() linkClick: EventEmitter<ModusTableCellLink>;
Done

2023-07-26 09:24 UTC, Ankur-Koul commented on stencil-workspace/src/components/modus-table/enums/modus-table-column-data-type.ts
> +  Boolean = 'boolean',
Cell formatter should take care of this

2023-07-26 09:24 UTC, Ankur-Koul commented on stencil-workspace/src/components/modus-table/parts/cell/modus-table-cell.tsx
> +            getCellType(cell.getValue()['_type'], cell.column.columnDef[PropertyDataType]) ===
Done

2023-07-26 09:24 UTC, Ankur-Koul commented on stencil-workspace/storybook/stories/components/modus-table/modus-table-storybook-docs.mdx
> +  _type: ModusTableColumnDataType.Link // Is used to override the column data type.
Yes

2023-07-26 09:24 UTC, Ankur-Koul commented on stencil-workspace/storybook/stories/components/modus-table/modus-table.stories.tsx
> +    progress: link ? { display: 'Click me', url: 'https://modus.trimble.com/components/web/' } : Math.floor(rand * 100), // Link
Done

2023-07-26 09:24 UTC, Ankur-Koul commented on stencil-workspace/storybook/stories/components/modus-table/modus-table.stories.tsx
> +Hyperlink.args = { ...DefaultArgs, columns: updateColumnWithType(), data: makeData(true, 5) };
Done

2023-07-26 09:36 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-table/enums/modus-table-column-data-type.ts
> +  Boolean = 'boolean',
How do we handle boolean data when there is no cell formatter available?

2023-07-26 09:43 UTC, msankaran0712 requested changes

2023-07-26 09:43 UTC, msankaran0712 commented on stencil-workspace/storybook/stories/components/modus-table/modus-table-storybook-docs.mdx
> +  _type: ModusTableColumnDataType.Link // Is used to override the column data type.
Please add `?` after `_type`

2023-07-26 09:43 UTC, msankaran0712 commented on stencil-workspace/storybook/stories/components/modus-table/modus-table.stories.tsx
> +const HyperlinkColumns = JSON.parse(JSON.stringify(DefaultColumns));
We should be able to use "DefaultColumns" directly instead of stringifying and parsing.

2023-07-27 05:12 UTC, Ankur-Koul commented on stencil-workspace/storybook/stories/components/modus-table/modus-table.stories.tsx
> +    progress: link ? { display: 'Click me', url: 'https://modus.trimble.com/components/web/' } : Math.floor(rand * 100), // Link
It is changed.

2023-07-27 05:52 UTC, msankaran0712 requested changes

2023-07-27 05:52 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-table/models/modus-table-cell-link.ts
> +export interface ModusTableCellLink {
Models must be exported as default inside each file.

2023-07-27 05:55 UTC, msankaran0712 requested changes

2023-07-27 05:55 UTC, msankaran0712 commented on stencil-workspace/storybook/stories/components/modus-table/modus-table.stories.tsx
> +  const rand = Math.random();
Could we remove `rand` variable and use `randomNumber` in its place.

2023-07-27 06:00 UTC, msankaran0712 requested changes

2023-07-27 06:00 UTC, msankaran0712 commented on stencil-workspace/storybook/stories/components/modus-table/modus-table.stories.tsx
>  // Helpers
Also, we can show events emitted through the actions tab,

Example: If you click on the email in the Modus Data Table page, it shows the event that is emitted under Actions tab

![image](https://github.com/trimble-oss/modus-web-components/assets/50131391/4e83b6bc-bcf3-49ea-8664-2a4cd4ce7556)

Result:
![image](https://github.com/trimble-oss/modus-web-components/assets/50131391/c41a36bf-a737-4a74-ae20-9af8da9ca765)

2023-07-27 06:15 UTC, msankaran0712 requested changes
1. Ellipsis not appearing for truncated text in the Email column
![image](https://github.com/trimble-oss/modus-web-components/assets/50131391/99b76355-6776-4777-bcb1-c19a3d72b3f0)

2. Hover cell border colour looks invisible in dark theme
3. Please fix the **dark theme colour code** for the column visibility icon at the top panel. You can find the dark theme color code from https://modus-icons.trimble.com/modus-solid/more-horizontal/

2023-07-27 07:09 UTC, Ankur-Koul commented on stencil-workspace/storybook/stories/components/modus-table/modus-table.stories.tsx
> +  const rand = Math.random();
There is already exists a function named `randomNumber`

2023-07-27 07:10 UTC, Ankur-Koul commented on stencil-workspace/storybook/stories/components/modus-table/modus-table.stories.tsx
>  // Helpers
Done

2023-07-27 07:11 UTC, Ankur-Koul commented on stencil-workspace/src/components/modus-table/models/modus-table-cell-link.ts
> +export interface ModusTableCellLink {
Done

2023-07-27 09:39 UTC, msankaran0712 commented on stencil-workspace/storybook/stories/components/modus-table/modus-table.stories.tsx
> +  const rand = Math.random();
I mean replace "rand" variable with "randomNumber"

so the code will be,
...
age: randomNumber(0,30),
visits: randomNumber(0,100),
....

2023-07-27 10:29 UTC, Ankur-Koul commented
> 1. Ellipsis not appearing for truncated text in the Email column
>    ![image](https://user-images.githubusercontent.com/50131391/256440694-99b76355-6776-4777-bcb1-c19a3d72b3f0.png)
> 2. Hover cell border colour looks invisible in dark theme
> 3. Please fix the **dark theme colour code** for the column visibility icon at the top panel. You can find the dark theme color code from https://modus-icons.trimble.com/modus-solid/more-horizontal/

Fixed all 3 connents

2023-07-27 10:29 UTC, Ankur-Koul commented on stencil-workspace/storybook/stories/components/modus-table/modus-table.stories.tsx
> +  const rand = Math.random();
Done

2023-07-28 04:19 UTC, HarshithaNous commented
Below are my observations:
1. Hyperlink color is not as per the styleguide. Please refer the below screenshots:
<img width="960" alt="image" src="https://github.com/trimble-oss/modus-web-components/assets/129380495/a67acb41-06a4-484d-8d36-51ea20b9be97">
<img width="908" alt="image" src="https://github.com/trimble-oss/modus-web-components/assets/129380495/49f7e805-6e77-4837-8f91-e5a65e808696">

2023-07-31 06:06 UTC, msankaran0712 requested changes
1. It looks like sorting is not working on the hyperlink column
![image](https://github.com/trimble-oss/modus-web-components/assets/50131391/7fa64da7-7b03-4b9f-9e61-5be59d2c2b01)

2023-07-31 06:16 UTC, msankaran0712 requested changes

2023-07-31 06:16 UTC, msankaran0712 commented on stencil-workspace/src/global/themes.scss
> +  --modus-menu-dropdown-icon-color: var(--modus-gray-10);
Can you please rename this to `--modus-icon-colour`? We can use it everywhere.

2023-07-31 06:16 UTC, msankaran0712 commented on stencil-workspace/src/global/themes.scss
> +  --modus-link-color: var(--modus-blue-4);
We need a separate variable for cell link color, please add `--modus-table-cell-link-colour: var(--modus-link-color)` under light theme and add `--modus-table-cell-link-colour: var(--modus-blue-4);` under dark theme

2023-07-31 06:24 UTC, msankaran0712 requested changes

2023-07-31 06:24 UTC, msankaran0712 commented on stencil-workspace/storybook/stories/components/modus-table/modus-table-storybook-docs.mdx
> +  _type: ModusTableColumnDataType.Link // Is used to override the column data type.
Please add `?` after `_type`

2023-08-01 07:17 UTC, Ankur-Koul commented on stencil-workspace/storybook/stories/components/modus-table/modus-table-storybook-docs.mdx
> +  _type: ModusTableColumnDataType.Link // Is used to override the column data type.
Done

2023-08-01 07:18 UTC, Ankur-Koul commented on stencil-workspace/src/global/themes.scss
> +  --modus-link-color: var(--modus-blue-4);
Done

2023-08-01 07:18 UTC, Ankur-Koul commented on stencil-workspace/src/global/themes.scss
> +  --modus-menu-dropdown-icon-color: var(--modus-gray-10);
Done

2023-08-01 10:55 UTC, msankaran0712 approved these changes

2023-08-01 10:55 UTC, merged