Dev/akoul/sticky column
trimble-oss/modus-web-components pull request #1587
Opened 2023-07-28 09:23 UTC by Ankur-Koul

## Description

References #

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

2023-08-01 10:19 UTC, HarshithaNous commented
Below is my observations:
1. Column Header is not freeze, please refer the below gif:
![2023-07-27_12h34_48](https://github.com/trimble-oss/modus-web-components/assets/129380495/accde7be-c35d-4655-ba16-cbd47d5a764f)

2023-08-03 06:56 UTC, msankaran0712 requested changes

2023-08-03 06:56 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-table/modus-table.scss
> +  border-collapse: separate; // `border-collapse:collapse` create an issue when use it with `possition: sticky`.
I would suggest to add a little more context/details about the issue

2023-08-03 06:56 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-table/parts/header/modus-table-header.tsx
> +        ${frozenColumns.includes(header.id) && !columnResizeEnabled && columnReorder ? 'can-reorder' : ''}
What is the purpose of this if clause?

2023-08-03 08:28 UTC, Ankur-Koul commented on stencil-workspace/src/components/modus-table/modus-table.scss
> +  border-collapse: separate; // `border-collapse:collapse` create an issue when use it with `possition: sticky`.
Done.

2023-08-03 08:28 UTC, Ankur-Koul commented on stencil-workspace/src/components/modus-table/parts/header/modus-table-header.tsx
> +        ${frozenColumns.includes(header.id) && !columnResizeEnabled && columnReorder ? 'can-reorder' : ''}
Done

2023-08-03 08:42 UTC, msankaran0712 approved these changes

2023-08-03 08:42 UTC, merged