Added inline edit functionality
trimble-oss/modus-web-components pull request #1608
Opened 2023-08-03 09:45 UTC by Ankur-Koul

## Description

This feature enabled inline cell editing.

References #742 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

2023-08-08 06:19 UTC, msankaran0712 requested changes
@Ankur-Koul 
triggering a text box for inline editing by typing valid characters does not show the character that was typed first

2023-08-08 13:06 UTC, HarshithaNous commented
Below are my observations:
1. Dark theme - When a cell is edited the background color is turned to white but the styleguide has no such specification. Please refer the below screenshots:

<img width="947" alt="image" src="https://github.com/trimble-oss/modus-web-components/assets/129380495/c0dfc2c9-4a7b-44c2-8adf-e79e0a39a82f">
<img width="920" alt="image" src="https://github.com/trimble-oss/modus-web-components/assets/129380495/80968523-038b-4b8c-805d-6f3c061f1cc2">

2023-08-09 06:54 UTC, msankaran0712 requested changes

2023-08-09 06:54 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-table/modus-table.scss
> +            color: $modus-table-cell-color;
why is this changed?

2023-08-09 06:54 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-table/modus-table.tsx
> +  /** Emits the link that was clicked */
Comments is not correct.

2023-08-09 06:54 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-table/modus-table.tsx
> +  @Event() updatedRowData: EventEmitter<unknown>;
Is it possible to also send the column key that was updated?

2023-08-09 06:54 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-table/modus-table.tsx
> +  @Event() updatedRowData: EventEmitter<unknown>;
Event name could be "rowUpdated"

2023-08-09 06:54 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-table/modus-table.tsx
> +            old.map((row: Row<unknown>, index: number) => {
We can directly use old[rowIndex] and add a null check instead of iterating each row.

2023-08-09 06:54 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-table/modus-table.tsx
> +            old.map((row: Row<unknown>, index: number) => {
I am a bit concerned about the performance here when there is a huge dataset.

2023-08-09 06:54 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-table/parts/cell/modus-table-cell.tsx
> +function handleKeyDown(
Can't we move this function to outside this file?

2023-08-09 06:54 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-table/modus-table.tsx
> +                            rowIndex={rowIndex}
We can handle the cell key-down event in this file or on a utility class and pass that function to the cell so it can invoke it, instead of passing cellindex, rowindex, and other props.

2023-08-09 07:09 UTC, msankaran0712 requested changes

2023-08-09 09:32 UTC, Ankur-Koul commented on stencil-workspace/src/components/modus-table/parts/cell/modus-table-editable-cell.tsx
> +export const ModusTableEditableCell: FunctionalComponent<ModusTableEditableCellProps> = ({ cell, onValueChange }) => {
Done

2023-08-09 09:42 UTC, msankaran0712 commented on stencil-workspace/src/global/themes.scss
> +  --modus-table-cell-colour: var(--modus-link-color);
Cell Link CSS variable should be kept separate, though it is the same color used for border

2023-08-09 09:42 UTC, msankaran0712 commented on stencil-workspace/src/global/themes.scss
> +  --modus-table-cell-colour: var(--modus-link-color);
@Ankur-Koul FYI

2023-08-09 10:41 UTC, Ankur-Koul commented on stencil-workspace/src/components/modus-table/modus-table.tsx
> +  @Event() updatedRowData: EventEmitter<unknown>;
Done

2023-08-09 10:41 UTC, Ankur-Koul commented on stencil-workspace/src/components/modus-table/modus-table.tsx
> +  /** Emits the link that was clicked */
Made correction

2023-08-09 10:48 UTC, Ankur-Koul commented on stencil-workspace/src/components/modus-table/modus-table.tsx
> +            old.map((row: Row<unknown>, index: number) => {
Done

2023-08-09 10:48 UTC, Ankur-Koul commented on stencil-workspace/src/components/modus-table/parts/cell/modus-table-cell.tsx
> +function handleKeyDown(
Not be implemented

2023-08-09 10:49 UTC, Ankur-Koul commented on stencil-workspace/src/components/modus-table/modus-table.tsx
> +                            rowIndex={rowIndex}
Not be implemented

2023-08-11 01:45 UTC, msankaran0712 commented
@Ankur-Koul, can we stop the click event from bubbling up when clicking on the expanding icon on the cell in edit mode?

2023-08-11 01:49 UTC, msankaran0712 commented
I can see we enabled the expandable row column for column to resize, but the blue line is not appearing while resizing @HarshithaNous @Ankur-Koul FYI

2023-08-11 01:53 UTC, msankaran0712 commented
When the column's minimum size is 80. Looks like the icon is not getting hidden, but the text does.
![image](https://github.com/trimble-oss/modus-web-components/assets/50131391/d2a97cc1-9a62-40e2-bb7d-3ea79ae0b78f)

2023-08-11 02:02 UTC, msankaran0712 commented
@HarshithaNous @Ankur-Koul We might have to fix the background color of a text box when the row has hovered

2023-08-11 02:05 UTC, msankaran0712 commented
@HarshithaNous @Ankur-Koul When I try to edit the sub-row data, the updated data is not getting saved.

2023-08-14 10:49 UTC, HarshithaNous commented
Below are my observations:
Large Dataset - When sorting is performed on Email column, sorting is not applied and any further actions performed is not responding. Please refer the below gif:
![2023-08-14_16h16_481](https://github.com/trimble-oss/modus-web-components/assets/129380495/7bc24ff6-1779-459e-ac00-7ab7849d79b2)

2023-08-14 16:45 UTC, HarshithaNous commented
Columns with numeric values should only accept integer values and user should not be able to enter alphabets or any special character in columns with integer data type.
<img width="923" alt="image" src="https://github.com/trimble-oss/modus-web-components/assets/129380495/6349cd8f-52c5-41f7-97eb-334dc937556a">

2023-08-14 17:03 UTC, HarshithaNous commented
Expandable rows - Inline edit is not working as expected, if the child data is edited it is moved to parent cell. Please refer the below GIF:
![2023-08-14_22h27_46](https://github.com/trimble-oss/modus-web-components/assets/129380495/a62d91aa-efbc-4883-8aa6-89922f166392)

2023-08-16 09:01 UTC, Ankur-Koul commented on stencil-workspace/src/global/themes.scss
> +  --modus-table-cell-colour: var(--modus-link-color);
Changed

2023-08-22 09:11 UTC, closed without merging