Checkbox row selection development
trimble-oss/modus-web-components pull request #1622
Opened 2023-08-09 08:42 UTC by hemantk1325

## Description

Implementation of checkbox row selection.

References #1502 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

2023-08-10 08:14 UTC, msankaran0712 requested changes

2023-08-10 08:14 UTC, msankaran0712 commented on stencil-workspace/storybook/stories/components/modus-table/modus-table-storybook-docs.mdx
> +Users can select rows by checking checkboxes associated with each row.
Update the description, "To select rows, users can use the checkbox provided on each row. Normally, the Modus Table permits selecting only one row at a time, but this can be modified to allow multiple selections by using the `multi-row-selection` option"

2023-08-10 08:14 UTC, msankaran0712 commented on stencil-workspace/storybook/stories/components/modus-table/modus-table-storybook-docs.mdx
> +| `rowSelectionChange` | An event that fires on click of the checkbox.| `{ string[] }`                                           |
Is the data emitted in `rowSelectionChange` an object array or a string array?

2023-08-10 08:16 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-table/modus-table.scss
> +      // box-sizing: border-box;
Please add comments explaining why the change was made

2023-08-11 04:47 UTC, hemantk1325 commented on stencil-workspace/src/components/modus-table/modus-table.tsx
> +  @Prop() multiRowSelection = false;
done

2023-08-11 04:47 UTC, hemantk1325 commented on stencil-workspace/src/components/modus-table/modus-table.tsx
> +  @Prop() singleRowSelection = false;
done

2023-08-11 04:47 UTC, hemantk1325 commented on stencil-workspace/src/components/modus-table/modus-table.tsx
> +  /** Emits event on row selection change */
done

2023-08-11 04:48 UTC, hemantk1325 commented on stencil-workspace/src/components/modus-table/modus-table.tsx
> +  @Prop() subRowSelection = false;
done

2023-08-11 04:48 UTC, hemantk1325 commented on stencil-workspace/src/components/modus-table/modus-table.tsx
> +      if (this.selectedRowId === row.id) {
done

2023-08-11 04:48 UTC, hemantk1325 commented on stencil-workspace/src/components/modus-table/modus-table.tsx
> +      enableRowSelection: true,
done

2023-08-11 04:48 UTC, hemantk1325 commented on stencil-workspace/src/components/modus-table/modus-table.tsx
> +      enableMultiRowSelection: this.multiRowSelection && true,
removed `&& true`

2023-08-11 04:48 UTC, hemantk1325 commented on stencil-workspace/src/components/modus-table/modus-table.tsx
> +    console.log(this.rowSelectionChange.emit(selectedRowData));
removed console

2023-08-11 04:49 UTC, hemantk1325 commented on stencil-workspace/src/components/modus-table/modus-table.tsx
> +    const selectedRows = this.table.getSelectedRowModel();
made the changes

2023-08-11 04:49 UTC, hemantk1325 commented on stencil-workspace/src/components/modus-table/modus-table.tsx
> +      this.rowSelectionChange.emit(this.table.getSelectedRowModel());
done

2023-08-11 04:49 UTC, hemantk1325 commented on stencil-workspace/storybook/stories/components/modus-table/modus-table-storybook-docs.mdx
> +Users can select rows by checking checkboxes associated with each row.
updated comments

2023-08-11 04:49 UTC, hemantk1325 commented on stencil-workspace/storybook/stories/components/modus-table/modus-table-storybook-docs.mdx
> +| `rowSelectionChange` | An event that fires on click of the checkbox.| `{ string[] }`                                           |
updated comments

2023-08-11 10:21 UTC, hemantk1325 commented on stencil-workspace/src/components/modus-table/modus-table.scss
> +      // box-sizing: border-box;
reverted back this change

2023-08-16 13:29 UTC, HarshithaNous commented
@hemantk1325 When we scroll vertically the checkbox header border is not aligned properly. Please refer the below screenshot:
<img width="935" alt="image" src="https://github.com/trimble-oss/modus-web-components/assets/129380495/4a6e9ff8-dc2a-4824-9675-31f63f17ef54">

2023-08-16 14:32 UTC, HarshithaNous commented
When Full width is true, there is additional space next to checkbox column. Please refer the below screenshot:

<img width="956" alt="image" src="https://github.com/trimble-oss/modus-web-components/assets/129380495/cf855d5d-222b-47ee-9467-3cbc9e66ed54">

2023-08-18 09:32 UTC, hemantk1325 commented on stencil-workspace/src/components/modus-table/modus-table.scss
> +      // box-sizing: border-box;
Added comment for this change

2023-08-18 09:33 UTC, hemantk1325 commented
Closing this PR.
New PR link : https://github.com/trimble-oss/modus-web-components/pull/1659

2023-08-18 09:33 UTC, hemantk1325 commented
Closing this PR.
New PR link : https://github.com/trimble-oss/modus-web-components/pull/1659

2023-08-18 09:33 UTC, closed without merging