add icons for the expand all and collapse all links.
trimble-oss/modus-web-components pull request #1673
Opened 2023-08-28 15:32 UTC by rjavier-trimbler

## Description

- expand all icon added (chevron double up icon)
- collapse all icon added (chevron double down icon)
- icons storybook section included to see all icons available

References #
https://e-builderinc.atlassian.net/browse/NAV-227

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

2023-08-28 18:12 UTC, bradley-eb approved these changes
LGTM, but you should get approval from owners of the modus-web-components before merging.

2023-08-30 07:29 UTC, msankaran0712 requested changes
@rjavier-trimbler, For every pull request, please ensure it is associated with a GitHub issue. Could you kindly create the issue and provide a link?

2023-08-30 17:38 UTC, jkendell89 commented
References https://github.com/trimble-oss/modus-web-components/issues/1098

2023-09-01 06:40 UTC, msankaran0712 requested changes
@rjavier-trimbler @jkendell89 Your contribution is greatly appreciated! Thank you. I have added comments, and please let me know if you have any questions.

2023-09-01 06:40 UTC, msankaran0712 commented on stencil-workspace/storybook/stories/components/modus-icons/modus-icons.stories.tsx
> +    options: {
@rjavier-trimbler, 
Please add `argTypes`, so it enables the controls on the storybook page. You can also refer to `stencil-workspace\storybook\stories\components\modus-button\modus-button.stories.tsx` for an example.

Example:
![image](https://github.com/trimble-oss/modus-web-components/assets/50131391/850c2f74-ebfa-49c8-a85d-6c0e02e713df)

![image](https://github.com/trimble-oss/modus-web-components/assets/50131391/e2dccc73-1ff2-40e3-8eb1-7ee232d25447)

![image](https://github.com/trimble-oss/modus-web-components/assets/50131391/1065ceb7-c641-4574-9924-63fc32c0fb6d)

2023-09-01 06:40 UTC, msankaran0712 commented on stencil-workspace/storybook/stories/components/modus-icons/modus-icons.stories.tsx
> +    options: {
Once this is done, we can test all the icons from this page.

2023-09-01 06:40 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-icons/modus-icons.tsx
> +  @Prop() size?: string;
I suggest adding a default size value of `16` for consistency with the icons.

2023-09-01 06:40 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-icons/modus-icons.tsx
> +  @Prop() color?: string;
Kindly, can you please identify and update icons like `icon-calendar.tsx` that don't use the `color` property?

2023-09-01 06:40 UTC, msankaran0712 commented on stencil-workspace/src/components/icons/icon-chevron-double-down.tsx
> +interface IconProps {
Can you please use the existing interface `IconProps` from `stencil-workspace\src\components\icons\IconMap.tsx` ?

2023-09-01 06:40 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-icons/modus-icons.tsx
> +  @Prop() icon: string | null;
Each property must have an appropriate description. 

![image](https://github.com/trimble-oss/modus-web-components/assets/50131391/0397bc67-da01-4d7a-addb-1eebaacb3f0c)

2023-09-01 06:40 UTC, msankaran0712 commented on stencil-workspace/storybook/stories/components/modus-icons/modus-icons-storybook-docs.mdx
> +[Modus Icon](https://modus-icons.trimble.com/modus-solid/) web components are referenced using the `<modus-icon>` custom HTML element.
Slightly rephrased for better clarity, 

"Modus Icon component is a wrapper for icons that are replicated from `https://modus-icons.trimble.com`. It is referenced using the `<modus-icon>` custom HTML element."

2023-09-01 06:40 UTC, msankaran0712 commented on stencil-workspace/storybook/stories/components/modus-icons/modus-icons-storybook-docs.mdx
> +
Kindly please add the code block here, you can refer to other pages, like `Buttons`

![image](https://github.com/trimble-oss/modus-web-components/assets/50131391/812b313d-46b5-4752-aa92-7777d233c71f)

2023-09-01 06:45 UTC, msankaran0712 commented
@rjavier-trimbler @jkendell89 Could you please create a new GitHub issue?  Modus needs more details for this issue for tracking purposes, and the existing Issue #1098 is a bigger story that might not be appropriate.

2023-09-04 13:53 UTC, msankaran0712 requested changes

2023-09-04 13:53 UTC, msankaran0712 commented on stencil-workspace/src/components.d.ts
> +        "size"?: string | '16';
Defaults must be passed like `size: string = '16';`. And why do we a postfix `?`? The properties with and without `?` are the same way I believe.

2023-09-04 13:53 UTC, msankaran0712 commented on stencil-workspace/storybook/stories/components/modus-icons/modus-icons-storybook-docs.mdx
> +| `color`       | (optional) The color of the Icon                | `string`  |                         |               |          |
@coliff That would become a manual work, because each time we must update it instead of just copying and pasting it from readme.md file

2023-09-04 14:01 UTC, msankaran0712 commented
@rjavier-trimbler Thank you for fixing other icons like the calendar icon. A couple of comments are pending.

2023-09-06 05:47 UTC, rjavier-trimbler commented on stencil-workspace/storybook/stories/components/modus-icons/modus-icons.stories.tsx
> +    options: {
done! argTypes has been added

2023-09-06 05:48 UTC, rjavier-trimbler commented on stencil-workspace/src/components.d.ts
> +        "size"?: string | '16';
done! default value has been added

2023-09-06 05:51 UTC, rjavier-trimbler commented on stencil-workspace/storybook/stories/components/modus-icons/modus-icons-storybook-docs.mdx
> +
Done! code block has been added

2023-09-06 07:02 UTC, msankaran0712 requested changes
Whichever icon is updated, kindly make sure the default colour as `currentcolor` not the hex code.

2023-09-07 10:03 UTC, msankaran0712 approved these changes

2023-09-07 10:06 UTC, coliff approved these changes

2023-09-07 10:06 UTC, merged

2023-09-07 10:06 UTC, coliff commented
Great PR - thanks for the contribution!

2023-09-07 10:06 UTC, coliff commented
Great PR - thanks for the contribution!