Fix for starting date within the week in the month view
trimble-oss/modus-web-components pull request #1682
Opened 2023-08-31 11:08 UTC by csrinivasan80

## Description
Fixes #1662 

References #

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

## Checklist

- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

2023-08-31 11:39 UTC, coliff commented on stencil-workspace/package-lock.json
I think you must be running a very old version of NodeJS/npm as it changed the `package-lock` file version to v1. Please use Node 16. It should be lock-version 3.
https://docs.npmjs.com/cli/v9/configuring-npm/package-lock-json#version

2023-08-31 11:40 UTC, coliff commented on stencil-workspace/src/components/modus-date-picker/modus-date-picker.scss
> +    &.disabled{
Please run prettier - there should be a space before the `{`

2023-08-31 11:43 UTC, coliff commented
FYI: CI/CD is failing because the package-lock version was changed.

```
8:10:19 PM: npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
8:10:19 PM: npm ERR!
8:10:19 PM: npm ERR! Invalid: lock file's postcss@8.3.11 does not satisfy postcss@8.4.29
npm ERR! Missing: postcss@8.3.11 from lock file
8:10:19 PM: npm ERR! Invalid: lock file's source-map-js@0.6.2 does not satisfy source-map-js@1.0.2
npm ERR! Missing: source-map-js@0.6.2 from lock file
```

2023-08-31 15:00 UTC, csrinivasan80 commented on stencil-workspace/package-lock.json
ok, will revert the package-lock and update the version.

2023-08-31 15:02 UTC, csrinivasan80 commented on stencil-workspace/src/components/modus-date-picker/modus-date-picker.scss
> +    &.disabled{
whether prettier included part of the configuration file and gets applied while saving the file?

2023-09-01 04:43 UTC, csrinivasan80 commented on stencil-workspace/package-lock.json
@coliff - updated the file now. Can you check it once?

2023-09-01 04:43 UTC, csrinivasan80 commented on stencil-workspace/src/components/modus-date-picker/modus-date-picker.scss
> +    &.disabled{
@coliff - its updated now

2023-09-01 06:43 UTC, coliff commented on stencil-workspace/src/components/modus-date-picker/modus-date-picker.scss
> +    &.disabled{
Prettier doesn't get applied as soon as you save the file unless you have that setup. No problem though, I need to upgrade Prettier to v3 and format everything in a different issue/PR anyway :-)

2023-09-01 06:47 UTC, coliff approved these changes
Nice job. looks good!
https://deploy-preview-1682--modus-webcomponents.netlify.app/?path=/docs/user-inputs-date-picker--default

2023-09-01 06:57 UTC, csrinivasan80 commented
> Nice job. looks good! https://deploy-preview-1682--modus-webcomponents.netlify.app/?path=/docs/user-inputs-date-picker--default

Can you help us in merging this PR?

2023-09-01 07:28 UTC, msankaran0712 requested changes

2023-09-01 07:28 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-date-picker/modus-date-picker.scss
> +        height: 170px;//Need to be adjusted to make it flexible based on child grid container height. Due to absolute position of the child we were not able to mark it as auto.
Thank you for the fix @csrinivasan80 A minor fix is needed for an UI issue,

Issue:
![image](https://github.com/trimble-oss/modus-web-components/assets/50131391/2db42460-6c4d-41c8-b537-d480630ea8ac)

Fix:
On the `.calendar-body` div, please add a standard height and width as 224px (taken from Modua Figma UI Kit) and remove the `justify-content`. Also please remove `170px` from `.calendar-month-container`

![image](https://github.com/trimble-oss/modus-web-components/assets/50131391/fd80af6a-9c8e-4583-8dcc-f0f32af6c590)

2023-09-01 08:14 UTC, msankaran0712 requested changes

2023-09-01 08:14 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-date-picker/modus-date-picker.tsx
> +                return <button
Also, please add tabIndex = -1 for the disabled dates

2023-09-01 08:20 UTC, msankaran0712 requested changes

2023-09-01 08:20 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-date-picker/modus-date-picker.scss
> +        height: 170px;//Need to be adjusted to make it flexible based on child grid container height. Due to absolute position of the child we were not able to mark it as auto.
As discussed, better to increase the height to 180px instead of standard height and width

2023-09-01 08:20 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-date-picker/modus-date-picker.scss
> +    &.disabled {
There should be an empty line before `&.disabled`. I think it will be fixed automatically if you execute `npm run full`

2023-09-01 08:40 UTC, msankaran0712 approved these changes

2023-09-01 08:46 UTC, merged

2023-09-01 08:47 UTC, coliff commented
We'll aim to make a release a bit later today - thanks!