Modus List : prop to make the list fixed to be able to see the menu items  outside the content
trimble-oss/modus-web-components pull request #1683
Opened 2023-08-31 18:30 UTC by rjavier-trimbler

## Description
new `modus-list` prop to make the list fixed in case we're using a dropdown inside an accordion 
and be able to see the menu-item list outside the content.

Ex: 
#### With Fixed 
<img width="635" alt="Screen Shot 2023-08-31 at 2 29 09 PM" src="https://github.com/trimble-oss/modus-web-components/assets/141681143/f5b58047-b009-44bf-bc8d-03b68f5a1b6b">

#### Without Fixed
<img width="641" alt="Screen Shot 2023-08-31 at 2 29 52 PM" src="https://github.com/trimble-oss/modus-web-components/assets/141681143/48f8c995-632a-40e9-8c8c-fb5ab50a062f">

References # 
https://github.com/trimble-oss/modus-web-components/issues/1663

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

2023-09-01 09:59 UTC, msankaran0712 requested changes

2023-09-01 09:59 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-list/modus-list.tsx
> +  @Prop() fixed : boolean;
@ryan-henness-trimble @coliff have any better ideas? I think we can use `::part` https://developer.mozilla.org/en-US/docs/Web/CSS/::part instead of passing it as config.

2023-09-01 09:59 UTC, msankaran0712 commented on stencil-workspace/storybook/stories/components/modus-dropdown/modus-dropdown.stories.tsx
> +const WithItemsFixedTemplate = () => html`
This is not necessary. Thoughts, please @coliff @ryan-henness-trimble

2023-09-01 09:59 UTC, msankaran0712 commented on stencil-workspace/storybook/stories/components/modus-list/modus-list-storybook-docs.mdx
> +##### Modus List
This section should be copied and pasted from the `readme.md` file in the `components/modus-list` folder. The file is automatically updated, eliminating the need for manual updates.

2023-09-01 16:22 UTC, rjavier-trimbler commented on stencil-workspace/src/components/modus-list/modus-list.tsx
> +  @Prop() fixed : boolean;
Earlier a research was done to try to use what you mentioned and it did not work that's why we had to do this way

`modus-list::part(ul) { .... } `

here's the link:
https://codepen.io/Roliver-Rodriguez-EXT/pen/NWeWxBj

2023-09-04 10:04 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-list/modus-list.tsx
> +  @Prop() fixed : boolean;
The code pen example won't work because the code currently does not support `part`. Like slots, we need to add the `part` attribute to `ul` element in `modus-list. tsx`. Was that tested ?

2023-09-04 11:09 UTC, coliff commented on stencil-workspace/storybook/stories/components/modus-dropdown/modus-dropdown.stories.tsx
> +const WithItemsFixedTemplate = () => html`
I don't understand exactly. Are you saying that 'https://modus-web-components.trimble.com/?path=/story/components-dropdown--default' is not needed? That page wasn't added in this PR so why would it be removed? It'd be good to keep it but it should have Actions so can test the options (animateList, disabled, customPlacement etc)

2023-09-04 20:11 UTC, rjavier-trimbler commented on stencil-workspace/src/components/modus-list/modus-list.tsx
> +  @Prop() fixed : boolean;
done! The part attribute has been added, thank you for the help!!!

2023-09-05 13:11 UTC, egunther39 submitted a review, later dismissed
Looks good

2023-09-05 14:33 UTC, msankaran0712 commented on stencil-workspace/storybook/stories/components/modus-list/modus-list-storybook-docs.mdx
> +##### Modus List
This section is no more required

2023-09-05 15:01 UTC, msankaran0712 approved these changes

2023-09-05 15:02 UTC, merged