date picker year aria labels reversed and year selection icons both have down arrow classes
trimble-oss/modus-web-components pull request #1721
Opened 2023-09-13 18:03 UTC by acomsto

## Description

- Fix issue where date picker aria labels are reversed, "Next Year" now corresponds to up, and "Previous Year" now corresponds with down
- Fix issue where both year selection icons had the same class name icon-triangle-down, these icons are now caret-up and caret-down
- Add `caret-up` icon to `IconMap.tsx`
- Fix styling to now account for caret icons instead of the arrow icons

References #1718

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

Ran all tests

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

2023-09-13 23:19 UTC, ryan-henness-trimble commented
@acomsto It's looking good to me. I will give @coliff and @msankaran0712 a change to take a look

2023-09-14 05:25 UTC, msankaran0712 requested changes

2023-09-14 05:25 UTC, msankaran0712 commented on stencil-workspace/src/components/icons/IconMap.tsx
> +    case 'caret-up':
Please add this icon to the storybook page `stencil-workspace\storybook\stories\components\modus-icons\modus-icons.stories.tsx` 
![image](https://github.com/trimble-oss/modus-web-components/assets/50131391/aed83274-90f1-45a9-baa7-fbbf20203a77)

2023-09-14 05:36 UTC, msankaran0712 requested changes
There seems to be more space between the caret-up and caret-down icons now 

![image](https://github.com/trimble-oss/modus-web-components/assets/50131391/89b0638b-88c9-41da-8056-933d5a413959)

2023-09-14 06:38 UTC, coliff commented
> There seems to be more space between the caret-up and caret-down icons now

I think that change is very welcome. The icon tap-target was far too small before (12px x 12px) and now it is 16px x 16px.

2023-09-14 06:41 UTC, msankaran0712 commented
> > There seems to be more space between the caret-up and caret-down icons now
> 
> I think that change is very welcome. The icon tap-target was far too small before (12px x 12px) and now it is 16px x 16px.

My only concern was in Figma, the space is less

2023-09-19 05:41 UTC, msankaran0712 submitted a review, later dismissed

2023-09-19 06:07 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-date-picker/modus-date-picker.scss
> +        button {
we can remove this margin so that there enough space between the icons and no accessibility issue
cc @coliff

2023-09-19 06:23 UTC, coliff submitted a review, later dismissed

2023-09-20 00:31 UTC, coliff approved these changes

2023-09-20 05:28 UTC, msankaran0712 approved these changes

2023-09-20 05:29 UTC, merged