Issue 1728/third button modal
trimble-oss/modus-web-components pull request #1754
Opened 2023-10-03 10:35 UTC by pchaudh18

## Description

Adding third button in modus modal
References #1728

## Type of change

- [Y] Bug fix (non-breaking change which fixes an issue)
- [Y] New feature (non-breaking change which adds functionality)
- [Y] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [Y] Documentation update

## How Has This Been Tested?

modus-modal.spec.ts
modus-modal.e2e.ts

## Checklist

- [Y ] My code follows the style guidelines of this project
- [Y ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [Y ] My changes generate no new warnings
- [Y] I have added tests that prove my fix is effective or that my feature works
- [Y ] New and existing unit tests pass locally with my changes
- [Y] Any dependent changes have been merged and published in downstream modules
- [Y ] I have checked my code and corrected any misspellings

2023-10-03 11:09 UTC, msankaran0712 requested changes
Missing updates on Storybook pages

2023-10-03 11:10 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-modal/modus-modal.scss
> +      modus-button:nth-of-type(2) {
is this tested?

2023-10-03 11:11 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-modal/readme.md
> -| Property                   | Attribute                     | Description                                                                                                                          | T
Please copy this file for updating the properties section on the Storybook.

2023-10-03 13:51 UTC, pchaudh18 commented on stencil-workspace/src/components/modus-modal/modus-modal.models.tsx
> +export interface ModusModalButtons {
updated with one change as one file created

2023-10-03 13:51 UTC, pchaudh18 commented on stencil-workspace/src/components/modus-modal/modus-modal.scss
> +      modus-button:nth-of-type(2) {
yes for space between the buttons

2023-10-03 13:51 UTC, pchaudh18 commented on stencil-workspace/src/components/modus-modal/readme.md
> -| Property                   | Attribute                     | Description                                                                                                                          | T
updated the storybook modus file

2023-10-03 13:53 UTC, msankaran0712 commented
@trimble-oss/mwc-maintainers @ryan-henness-trimble @coliff @cjwinsor, Please note that the PR will be a breaking change for Modal component

2023-10-18 05:48 UTC, msankaran0712 commented
A new PR https://github.com/trimble-oss/modus-web-components/pull/1786 is available hence closing this one

2023-10-18 05:48 UTC, closed without merging