issue 1770 / add optional icons to profile menu link items in the profile menu of the navbar
trimble-oss/modus-web-components pull request #1776
Opened 2023-10-11 21:22 UTC by acomsto

## Description

- Added the option to add an icon to the link items within the profile menu on the navbar.
- Updated Storybook to include added optional icon property on the `ModusNavbarProfileMenuLink` where all the interfaces are listed.

References #1770

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

## How Has This Been Tested?

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

2023-10-12 02:30 UTC, coliff commented on package-lock.json
this file isn't needed.

2023-10-12 05:42 UTC, msankaran0712 requested changes
1. Please update the type information in Storybook, 
![image](https://github.com/trimble-oss/modus-web-components/assets/50131391/0187ae32-77c6-4ee5-91b9-ce2fe9e468ba)

2. Please add a few example links with icon here too, It will be easier for to visualize the changes,
![image](https://github.com/trimble-oss/modus-web-components/assets/50131391/55112f1d-4500-421a-ad5f-7e24d6cfa75d)

2023-10-12 05:52 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-navbar/profile-menu/modus-navbar-profile-menu.tsx
> +                  {link.icon && (
Is it possible to add any unit test for the profile menu popup?

2023-10-12 14:11 UTC, cjwinsor commented
The link element is extending outside the profile menu
![image](https://github.com/trimble-oss/modus-web-components/assets/1130129/7043715c-2a14-483d-8f80-7794aa3b3495)

2023-10-13 07:25 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-navbar/profile-menu/modus-navbar-profile-menu.tsx
>              {this.links.map((link) => {
@acomsto I discussed the menu with @coliff. We believe it should be a borderless `modus-list` with links, such as https://modus-bootstrap.netlify.app/docs/v2/components/list-group/#links-and-buttons, and follow the same padding & spacing as the List guidelines https://modus.trimble.com/components/web/lists/styles/ and have a hand cursor
![image](https://github.com/trimble-oss/modus-web-components/assets/50131391/d3dce2ca-c18e-47e0-8c28-4de0065f07c2).

If you can add the borderless support for `modus-list` component, you can use or create a div list following the Modus guidelines for Lists.

@coliff Please correct me if am wrong.

cc @ryan-henness-trimble

2023-10-18 05:29 UTC, msankaran0712 commented
@acomsto did you get the prototype from @egunther39 ?

2023-10-18 13:15 UTC, egunther39 commented
@msankaran0712 - I didn't get to it yet. I'll take care of it this morning

2023-10-18 22:07 UTC, acomsto commented
![image](https://github.com/trimble-oss/modus-web-components/assets/107583407/8257ceea-1d52-4f4b-ad26-2ff9fd4517ac)


@egunther39 Looks like the list items and navbar menu backgrounds have different requirements for the dark mode theme. Should I just match the backgrounds to the list item background colors in dark mode?

2023-10-19 14:43 UTC, msankaran0712 commented
> ![image](https://user-images.githubusercontent.com/107583407/276416532-8257ceea-1d52-4f4b-ad26-2ff9fd4517ac.png)
> 
> @egunther39 Looks like the list items and navbar menu backgrounds have different requirements for the dark mode theme. Should I just match the backgrounds to the list item background colors in dark mode?

Stay tuned for another mockup for the dark theme. Meanwhile can you please change background color for all the popups in the Navbar to use `  --modus-gray-10: #171c1e;` for the dark mode, currently it is using a wrong color. Let me know if you need any help in how to do that, because you need to insert a new CSS variable here below and update it in all the popups in Navbar, profile menu pop-up, notifications pop-up, dynamic icon button pop-up, hamburger menu, etc.
![image](https://github.com/trimble-oss/modus-web-components/assets/50131391/8ff2e72d-1649-4aea-b2ef-682c759e2a0f)

2023-10-26 06:28 UTC, msankaran0712 approved these changes
@acomsto Thank you for the PR! The UI looks, just a few minor UI corrections needed,

- Dark theme - Pop up border color has to be Gray 8 (#464B52)
- Spacing between the leading icon and the text inside a list item is 16px ([Figma link](https://www.figma.com/file/wyfVJUHWRMkeCfdB38HFEE/Modus---Web?node-id=27038%3A32416&mode=dev))
- Yet to be confirmed, the leading icon size inside a list item is supposed to be 16px not 24px

2023-10-26 06:28 UTC, msankaran0712 requested changes
@acomsto Thank you for the PR! The UI looks good, just a few minor UI corrections needed,

Dark theme - Pop up border color has to be Gray 8 (#464B52)
Spacing between the leading icon and the text inside a list item is 16px ([Figma link](https://www.figma.com/file/wyfVJUHWRMkeCfdB38HFEE/Modus---Web?node-id=27038%3A32416&mode=dev))
Yet to be confirmed, the leading icon size inside a list item is supposed to be 16px not 24px

2023-10-31 14:10 UTC, msankaran0712 commented
@acomsto Kindly comment out the failing test 
![image](https://github.com/trimble-oss/modus-web-components/assets/50131391/6776b158-fb7e-4f3f-a317-32d0c1bce497)

2023-10-31 14:11 UTC, msankaran0712 commented
@acomsto, is there anything else pending from Modus' end?

2023-10-31 16:09 UTC, acomsto commented
@msankaran0712 I don't believe so

2023-11-01 05:27 UTC, msankaran0712 commented
> @msankaran0712 I don't believe so

Okay, I will be waiting for the PR comments to get fixed

2023-11-01 05:29 UTC, msankaran0712 commented
@acomsto Kindly squash the commits.

2023-11-01 17:32 UTC, ryan-henness-trimble commented
> @acomsto Kindly squash the commits.

@msankaran0712 
Should we allow devs to depend on the "Squash and merge" GitHub feature instead of requiring explicit squash?

2023-11-02 05:18 UTC, msankaran0712 commented
> > @acomsto Kindly squash the commits.
> 
> @msankaran0712 Should we allow devs to depend on the "Squash and merge" GitHub feature instead of requiring explicit squash?

I am okay with the GitHub feature. Explicitly squashing commits is optional, and we can do it if it is not too much effort.

2023-11-02 05:20 UTC, msankaran0712 requested changes

2023-11-02 05:21 UTC, msankaran0712 commented
@acomsto @ryan-henness-trimble  Apologies, I did not submit my review comments until now thinking that I already did.

2023-11-02 18:43 UTC, ryan-henness-trimble commented on stencil-workspace/src/components/modus-list-item/modus-list-item.tsx
> +  @Prop() type: 'standard' | 'icon'; // Future support for 'checkbox' | 'icon' | 'menu' | 'standard' | 'switchLeft' | 'switchRight'
In spirit of keeping this component generic and not assuming what the consumer would like to render in the list item, I don't think we should add the trailing and leading icons. I think the best approach is to add an `icon` property to the `ModusNavbarProfileMenuLink`. That way, we can add the icon within the list item next to its display text using the `<IconMap />`

2023-11-03 06:02 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-navbar/profile-menu/modus-navbar-profile-menu.spec.ts
> +    class MutationObserverMock {
why do we need to mock a Mutation observer for profile menu popup?

2023-11-03 06:19 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-navbar/profile-menu/modus-navbar-profile-menu.spec.ts
> +    class MutationObserverMock {
Also, the padding between the icon and the text is 16px, not 8px, ([Figma](https://www.figma.com/file/wyfVJUHWRMkeCfdB38HFEE/Modus---Web?node-id=27038%3A32394&mode=dev) for reference) It was incorrect on Modus Styleguide and raised a separate issue for fixing that.

2023-11-03 06:19 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-navbar/profile-menu/modus-navbar-profile-menu.spec.ts
> +    class MutationObserverMock {
@ryan-henness-trimble Please feel free to approve and merge the PR when the above two comments are fixed.

2023-11-03 16:20 UTC, ryan-henness-trimble approved these changes

2023-11-03 16:21 UTC, ryan-henness-trimble commented
@msankaran0712 Thanks for the help on this PR! 😄

2023-11-03 16:22 UTC, merged