Add custom footer slot for Modal component
trimble-oss/modus-web-components pull request #1786
Opened 2023-10-17 15:19 UTC by pchaudh18

## Description

References #1728

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

## How Has This Been Tested?

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

2023-10-18 08:09 UTC, msankaran0712 requested changes

2023-10-18 08:11 UTC, msankaran0712 requested changes
Please use the attachment files for the latest code

2023-10-18 14:54 UTC, coliff commented on stencil-workspace/src/components/modus-modal/modus-modal.spec.ts
> +                <div class="footer">
Can this be `<footer class="footer">` instead of a div?

2023-10-18 14:57 UTC, pchaudh18 commented
Hi
I have updated the branch with new changes for the modus-modal and some auto-updated files

2023-10-19 09:59 UTC, msankaran0712 approved these changes

2023-10-19 10:08 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-modal/modus-modal.spec.ts
> +                <div class="footer">
yes we can do that. @palakchaudhary18 Can you please replace the divs with header and footer HTML elements and remove the css classes 'header' and ''footer' too.

Expected:
![image](https://github.com/trimble-oss/modus-web-components/assets/50131391/e1ec3350-37c0-46c0-8385-2cfbed0b1f0d)
 
![image](https://github.com/trimble-oss/modus-web-components/assets/50131391/52a25225-dca9-471f-a120-50a572be0f2c)

2023-10-19 13:07 UTC, pchaudh18 commented on stencil-workspace/src/components/modus-modal/modus-modal.spec.ts
> +                <div class="footer">
updated the code

2023-10-19 14:48 UTC, msankaran0712 approved these changes

2023-10-19 14:48 UTC, coliff approved these changes

2023-10-19 14:50 UTC, merged