Table - Added Row Actions with code refactored
trimble-oss/modus-web-components pull request #1787
Opened 2023-10-17 16:03 UTC by leosole-trimble

## Description

References #

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

2023-10-18 10:00 UTC, msankaran0712 requested changes
Two things to fix,

1. failing unit test because of usage of a non-existent css class `.row-actions`, 
![image](https://github.com/trimble-oss/modus-web-components/assets/50131391/ec7cdb4f-01eb-4fd5-995d-7e2eb0ecede8)

2. We need a null check for `isVisible`, 
![image](https://github.com/trimble-oss/modus-web-components/assets/50131391/076c4a67-5c49-46f7-92b4-e9fdaf15ad1f)

2023-10-18 10:04 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-list/modus-list.tsx
> +      (this.element.children.item(index + 1) as HTMLElement)?.focus();
What happens when you press arrow keys when you reach the bottom or the top?

2023-10-18 10:06 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-table/parts/row/actions/modus-table-row-actions-menu/modus-table-row-actions-menu.tsx
> +                  <modus-list-item onItemClick={() => this.handleListItemClick(id)} class="hydrated" onKeyDown={e => this.handleListItemKeydown(e, id)} tabindex={0}>
I can see we now emit `itemClick` on the Enter key press on the list item,  do we still `handleListItemKeydown` ?

2023-10-18 10:08 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-table/parts/row/actions/modus-table-row-actions/modus-table-row-actions.tsx
> +      const { left, top, height } = this.overflowButtonRef.getBoundingClientRect();
we can reuse the code from `handleMoreButtonClick` or put the code in a common function, because it is the same code repeated inside `handleMoreButtonKeydown`

2023-10-18 10:09 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-table/parts/row/actions/modus-table-row-actions/modus-table-row-actions.tsx
> +    if (e.key.toLowerCase() === 'enter') {
same here, code is repeated on keydown handler

2023-10-18 10:10 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-table/modus-table.e2e.ts
> +    const rowActions = await page.findAll('modus-table >>> .row-actions');
I think there is no such CSS class `row-actions`

2023-10-18 11:05 UTC, leosole-trimble commented on stencil-workspace/src/components/modus-list/modus-list.tsx
> +      (this.element.children.item(index + 1) as HTMLElement)?.focus();
Currently nothing happens. I thought of adding a key like 'esc' or something else to close the menu

2023-10-18 11:10 UTC, leosole-trimble commented on stencil-workspace/src/components/modus-table/parts/row/actions/modus-table-row-actions-menu/modus-table-row-actions-menu.tsx
> +                  <modus-list-item onItemClick={() => this.handleListItemClick(id)} class="hydrated" onKeyDown={e => this.handleListItemKeydown(e, id)} tabindex={0}>
I forgot to remove this. But after removing, it's not working anymore. Did I forgot to do something in the list item keyDown event?

2023-10-18 11:24 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-table/parts/row/actions/modus-table-row-actions-menu/modus-table-row-actions-menu.tsx
> +                  <modus-list-item onItemClick={() => this.handleListItemClick(id)} class="hydrated" onKeyDown={e => this.handleListItemKeydown(e, id)} tabindex={0}>
It is good as long as it does not throw any error 👍🏼

2023-10-18 11:25 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-list/modus-list.tsx
> +      (this.element.children.item(index + 1) as HTMLElement)?.focus();
It is good as long as it does not throw any error 👍🏼

2023-10-18 11:27 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-list-item/modus-list-item.tsx
> +    if (e.key.toLowerCase() === 'enter') {
did you test whether this function is called? if yes, item click event handler on the row actions menu should work too

2023-10-18 14:39 UTC, msankaran0712 commented
I have fixed some issues with the Modus List and Modus List item. Please use the updated code from the attachment. 
[leosole-trimble.zip](https://github.com/trimble-oss/modus-web-components/files/13029882/leosole-trimble.zip)

2023-10-20 14:04 UTC, msankaran0712 commented
[Leo_branch.zip](https://github.com/trimble-oss/modus-web-components/files/13055047/Leo_branch.zip)

Hey Leo, I fixed the below issues and attached the code above.

2023-10-26 11:05 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-table/parts/row/actions/modus-table-row-actions-menu/modus-table-row-actions-menu.tsx
> +      transform: `translate(calc(${x}px + 33%), calc(${y}px))`,
I think this workaround not working on Storybook

2023-10-26 11:06 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-table/parts/row/actions/modus-table-row-actions-menu/modus-table-row-actions-menu.tsx
> +    };
Pressing Enter key on the overflow list item not closing the menu

2023-10-26 11:08 UTC, msankaran0712 commented on stencil-workspace/src/index.html
> +    <modus-table>
Kindly revert this code

2023-10-26 11:13 UTC, msankaran0712 commented
@leosole-trimble There was a hotfix made last week, I think that might be conflicting with our code a little bit

2023-10-31 15:20 UTC, closed without merging