feat: adding manual pagination for server side
trimble-oss/modus-web-components pull request #1820
Opened 2023-10-25 17:00 UTC by rjavier-trimbler

## Description
- Some attributes were added in order to set a manual pagination to be handled from the server side

References # [](https://github.com/trimble-oss/modus-web-components/issues/1153)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

2023-10-25 23:12 UTC, cjwinsor requested changes

2023-10-25 23:12 UTC, cjwinsor commented on stencil-workspace/src/components/modus-table/modus-table.tsx
>    }
I think the readability of this can be improved which can help prevent bugs later on

```js

renderPagination(table) {
  if (!this.pagination) {
    return null;
  }

  let paginationProps = {
    table,
    pageSizeList: this.pageSizeList,
  };

  if (this.manualPaginationOptions) {
    paginationProps = {
      ...paginationProps,
      totalCount: this.manualPaginationOptions.pageCount || 0,
      currentPageSize: this.manualPaginationOptions.currentPageSize || 0,
      currentPageIndex: this.manualPaginationOptions.currentPageIndex || 0,
    };
  } else {
    paginationProps = {
      ...paginationProps,
      totalCount: this.data?.length || 0,
    };
  }

  return <ModusTablePagination {...paginationProps} />;
}
```

The ideas are:
1. To exit quickly if they don't have pagination
2. Increase the readability  of the code with a simple if statement
3. Reduce duplication by creating a base props object with the shared properties
4. Spread those default props into the new object with the condition specific properties.
5. Simply final return statement.

Technically you could remove the else condition by setting `totalCount` initially to `this.data?.length || 0` but the else condition makes it a little more clear that we do expect to only use `this.data` when we aren't given `this.manualPaginationProperties` without the concern we might be incorrectly overriding. 

I'm favoring being more intentional and explicit over reducing lines of code.

2023-10-26 09:21 UTC, msankaran0712 commented on stencil-workspace/storybook/stories/components/modus-table/modus-table.stories.tsx
> +    cellEditable:true,
It might be because the branch is outdated.

2023-10-26 09:27 UTC, msankaran0712 commented on stencil-workspace/storybook/stories/components/modus-table/modus-table.stories.tsx
> +const ManualPaginationTemplate = ({
If you add the manual pagination options to the default Template, it will let users change the control from any example.

2023-10-26 09:29 UTC, msankaran0712 commented on stencil-workspace/storybook/stories/components/modus-table/modus-table.stories.tsx
> +const ManualPaginationTemplate = ({
Is there any reason not to reuse the default template and `initializeTable` function? If there are too many arguments on the javascript, compose them into a single object.

2023-10-26 09:32 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-table/models/modus-table.models.ts
> +export interface ManualPaginationOptions {
Any changes to the interfaces/types exposed on the components should be updated on Storybook, too.
![image](https://github.com/trimble-oss/modus-web-components/assets/50131391/8147b72c-8405-4c44-a024-11183a09c6d7)

2023-10-26 09:32 UTC, msankaran0712 commented on stencil-workspace/src/index.html
> +    <modus-table>
Kindly revert the changes done on this file.

2023-10-26 09:35 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-table/modus-table.tsx
> +  @Prop() manualPaginationOptions: ManualPaginationOptions;
Can we add some unit tests ?

2023-10-26 09:37 UTC, msankaran0712 commented on stencil-workspace/storybook/stories/components/modus-table/modus-table-storybook-docs.mdx
> +- [ManualPagination](#manual-pagination)
It could be moved to below the Pagination example for Table. Am not sure if we can have another level of folder structure in here.

2023-10-26 09:58 UTC, msankaran0712 reviewed
cc @cjwinsor I was more curious because this is a Table component PR and currently we have multiple PRs open for the same, it would be helpful to understand what code changes are being made.
@rjavier-trimbler Can you please add more explanation to the PR description about what kind of changes done and very important how to test the changes. Because I see on the example, the page size is 5 but there are more records on the table. 
![image](https://github.com/trimble-oss/modus-web-components/assets/50131391/cfed6fb0-c55d-433c-9df3-27fe268e69c9)

2023-10-30 17:01 UTC, rjavier-trimbler commented on stencil-workspace/storybook/stories/components/modus-table/modus-table.stories.tsx
> +const ManualPaginationTemplate = ({
done! put it in the default template!

2023-10-30 17:01 UTC, rjavier-trimbler commented on stencil-workspace/src/components/modus-table/modus-table.tsx
>    }
done!

2023-10-30 17:01 UTC, rjavier-trimbler commented on stencil-workspace/src/components/modus-table/parts/modus-table-pagination.tsx
> +          active-page={currentPageIndex ? currentPageIndex : 1}
done!j

2023-10-30 17:01 UTC, rjavier-trimbler commented on stencil-workspace/src/components/modus-table/parts/modus-table-pagination.tsx
> +  const pageSize =  (currentPageSize )? currentPageSize : paginationSize;
done! Thanks!

2023-10-30 17:01 UTC, rjavier-trimbler commented on stencil-workspace/storybook/stories/components/modus-table/modus-table-storybook-docs.mdx
> +
Changed! Thanks!

2023-10-30 17:01 UTC, rjavier-trimbler commented on stencil-workspace/storybook/stories/components/modus-table/modus-table-storybook-docs.mdx
> +- [ManualPagination](#manual-pagination)
Done!

2023-10-30 17:28 UTC, rjavier-trimbler commented on stencil-workspace/storybook/stories/components/modus-table/modus-table.stories.tsx
> +    cellEditable:true,
Now the branch is updated, thanks for the heads up!

2023-10-30 23:26 UTC, rjavier-trimbler commented on stencil-workspace/src/components/modus-table/models/modus-table.models.ts
> +export interface ManualPaginationOptions {
Done!

2023-10-30 23:31 UTC, rjavier-trimbler commented on stencil-workspace/src/index.html
> +    <modus-table>
Done!

2023-10-31 05:52 UTC, msankaran0712 commented on stencil-workspace/src/index.html
> +    <modus-table>
It never fails actually. What is the build error you are getting? @rjavier-trimbler

2023-10-31 05:55 UTC, msankaran0712 commented
@rjavier-trimbler Looks like one of the existing unit tests is failing, if you cannot fix it please feel free to comment it out for now.
![image](https://github.com/trimble-oss/modus-web-components/assets/50131391/47ecb9b8-c411-46d2-b288-9e4047066a43)

2023-10-31 06:04 UTC, msankaran0712 commented
> @cjwinsor I was curious as this is a Table component PR and we have multiple PRs open for the same, it would be helpful to understand what code changes are being made.
> 
> @rjavier-trimbler Can you please add more explanation to the PR description about what kind of changes are done and, very importantly how to test the changes? As I see in the example, the page size is 5, but there are more records on the table. ![image](https://user-images.githubusercontent.com/50131391/278290674-cfed6fb0-c55d-433c-9df3-27fe268e69c9.png)

@rjavier-trimbler On the page https://deploy-preview-1820--modus-webcomponents.netlify.app/?path=/story/components-table--manual-pagination I can see the page size selected is 5, but the table shows more records. What is the expected behavior ?

2023-10-31 18:02 UTC, rjavier-trimbler commented on stencil-workspace/src/index.html
> +    <modus-table>
I tried to fix it but I couldn't, it only passes the test with the lines of code that were removed in the `stencil-workpace/src/index.html` file, temporarily comment this code block for now.

2023-11-01 10:21 UTC, msankaran0712 commented on stencil-workspace/storybook/stories/components/modus-table/modus-table-storybook-docs.mdx
> +
> A little bit of language tweaking
> 
> ```
> Manual Pagination allows users to handle pagination in server-side mode.
> 
> - The Modus Table utilizes the `modus-pagination` component for navigating between pages. Based on the properties initially set, pagination can be managed from the server side.
> - Manual Pagination can be enabled using the `manualPaginationOptions` prop.
> - The `currentPageIndex` takes a number to specify the current page number, indicating which page should appear as selected from the server side.
> - The `currentPageSize` takes a number to specify the current page view number, determining how many records the table will display from the server side.
> - The `pageCount` takes a number to specify the total number of records, in order to display the corresponding number of pages in the table.
> ```

@rjavier-trimbler  I don't see this text anywhere on the Storybook page

2023-11-01 10:21 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-table/parts/modus-table-pagination.tsx
> +  const pageSize =  (currentPageSize )? currentPageSize : paginationSize;
I don't see any code changed

2023-11-01 10:23 UTC, msankaran0712 commented on stencil-workspace/src/index.html
> +    <modus-table>
@rjavier-trimbler Did you try copy pasting the code from https://github.com/trimble-oss/modus-web-components/blob/main/stencil-workspace/src/index.html

2023-11-01 10:24 UTC, msankaran0712 commented
> > @cjwinsor I was curious as this is a Table component PR and we have multiple PRs open for the same, it would be helpful to understand what code changes are being made.
> > @rjavier-trimbler Can you please add more explanation to the PR description about what kind of changes are done and, very importantly how to test the changes? As I see in the example, the page size is 5, but there are more records on the table. ![image](https://user-images.githubusercontent.com/50131391/278290674-cfed6fb0-c55d-433c-9df3-27fe268e69c9.png)
> 
> @rjavier-trimbler On the page [deploy-preview-1820--modus-webcomponents.netlify.app/?path=/story/components-table--manual-pagination](https://deploy-preview-1820--modus-webcomponents.netlify.app/?path=/story/components-table--manual-pagination) I can see the page size selected is 5, but the table shows more records and nothing happens when the page size and page index are changed. What is the expected behaviour? Let's simulate the server-side pagination for the example.

Will this issue be resolved?

2023-11-01 10:25 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-table/modus-table.tsx
> +  @Prop() manualPaginationOptions: ManualPaginationOptions;
Any updates?

2023-11-01 22:17 UTC, cjwinsor commented
@msankaran0712 I'll check with the teams tomorrow to see if I can get a big picture from them.  This particular feature has been discussed internally as one of the main blockers to fully adopting this table in the product given the often immense lists of rows.  I am going to be continuing my review tomorrow morning to see what has and has not been addressed and see if I can help move this along.

2023-11-02 01:19 UTC, cjwinsor commented on stencil-workspace/storybook/stories/components/modus-table/modus-table.stories.tsx
> +      description: 'To switch to manual pagiantion mode.',
Typo here: `pagiantion` -> `pagination`

2023-11-02 01:44 UTC, cjwinsor commented on stencil-workspace/storybook/stories/components/modus-table/modus-table-storybook-docs.mdx
> +
@rjavier-trimbler Looks like you removed the docs

2023-11-02 01:59 UTC, cjwinsor commented
> @cjwinsor I was curious as this is a Table component PR and we have multiple PRs open for the same, it would be helpful to understand what code changes are being made.
> 
> @rjavier-trimbler Can you please add more explanation to the PR description about what kind of changes are done and, very importantly how to test the changes? As I see in the example, the page size is 5, but there are more records on the table. ![image](https://user-images.githubusercontent.com/50131391/278290674-cfed6fb0-c55d-433c-9df3-27fe268e69c9.png)

@rjavier-trimbler I think the issue here is that we expect the manual pagination to control everything. You set the items per page to be 5, but are using `makeData(12)` so its adding 12 items to the grid.  You should be making 5 data rows.

2023-11-02 05:12 UTC, msankaran0712 commented
> > @cjwinsor I was curious as this is a Table component PR and we have multiple PRs open for the same, it would be helpful to understand what code changes are being made.
> > @rjavier-trimbler Can you please add more explanation to the PR description about what kind of changes are done and, very importantly how to test the changes? As I see in the example, the page size is 5, but there are more records on the table. ![image](https://user-images.githubusercontent.com/50131391/278290674-cfed6fb0-c55d-433c-9df3-27fe268e69c9.png)
> 
> @rjavier-trimbler I think the issue here is that we expect the manual pagination to control everything. You set the items per page to be 5, but are using `makeData(12)` so its adding 12 items to the grid. You should be making 5 data rows.

@cjwinsor @rjavier-trimbler As a user, I was expecting server-side pagination to be simulated in the example, the table should reflect when the page size and page index are changed. From the UI, there won't be any difference, and it will work the same way as client-side pagination.

2023-11-02 05:14 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-table/modus-table.tsx
> +  @Prop() manualPaginationOptions: ManualPaginationOptions;
@cjwinsor We need some basic unit tests for manual pagination

2023-11-02 12:17 UTC, cjwinsor commented
> > > @cjwinsor I was curious as this is a Table component PR and we have multiple PRs open for the same, it would be helpful to understand what code changes are being made.
> > > @rjavier-trimbler Can you please add more explanation to the PR description about what kind of changes are done and, very importantly how to test the changes? As I see in the example, the page size is 5, but there are more records on the table. ![image](https://user-images.githubusercontent.com/50131391/278290674-cfed6fb0-c55d-433c-9df3-27fe268e69c9.png)
> > 
> > 
> > @rjavier-trimbler I think the issue here is that we expect the manual pagination to control everything. You set the items per page to be 5, but are using `makeData(12)` so its adding 12 items to the grid. You should be making 5 data rows.
> 
> @cjwinsor @rjavier-trimbler As a user, I was expecting server-side pagination to be simulated in the example, the table should reflect when the page size and page index are changed. From the UI, there won't be any difference, and it will work the same way as client-side pagination.

@msankaran0712 I agree. This example needs to be 100% accurate to how it should be used.  Making sure the items per page match the items show, the number of pages are accurate for the example, and changing pages changes the data.

2023-11-02 18:34 UTC, cjwinsor commented on stencil-workspace/src/components/modus-table/modus-table.tsx
> +  @Prop() manualPaginationOptions: ManualPaginationOptions;
@msankaran0712 This has been communicated, and is expected

2023-11-03 05:53 UTC, rjavier-trimbler commented on stencil-workspace/src/components/modus-table/modus-table.tsx
> +  @Prop() manualPaginationOptions: ManualPaginationOptions;
the unit test has bee added !! now it test the manualPagination options and expect the output results in the table

2023-11-04 05:22 UTC, rjavier-trimbler commented on stencil-workspace/storybook/stories/components/modus-table/modus-table.stories.tsx
> +      description: 'To switch to manual pagiantion mode.',
done!

2023-11-04 05:24 UTC, rjavier-trimbler commented on stencil-workspace/storybook/stories/components/modus-table/modus-table-storybook-docs.mdx
> +
the Docs has been added again!!

2023-11-06 16:10 UTC, rjavier-trimbler commented
@msankaran0712 @coliff  
I need your help with the revision on these changes again please!

2023-11-07 11:04 UTC, msankaran0712 commented on stencil-workspace/storybook/stories/components/modus-table/modus-table.stories.tsx
> +        const manualPaginationData = ${JSON.stringify(makeData(manualPaginationOptions?.totalRecords))};
I think you don't have to invoke `makeData` again, can use the `data` instead.

2023-11-07 11:09 UTC, msankaran0712 submitted a review, later dismissed

2023-11-07 11:09 UTC, msankaran0712 commented on stencil-workspace/storybook/stories/components/modus-table/modus-table.stories.tsx
> +        const manualPaginationData = ${JSON.stringify(makeData(manualPaginationOptions?.totalRecords))};
@rjavier-trimbler @cjwinsor If this PR comment is not fixable, please go ahead with merging the PR after rebasing the branch.

2023-11-07 18:57 UTC, cjwinsor commented
Something doesn't seem correct with this branch, so I am reviewing. I'm worried it will introduce or remove something unintentionally.  I'll comment again after I finish my review.

2023-11-07 20:05 UTC, cjwinsor submitted a review, later dismissed

2023-11-07 21:55 UTC, cjwinsor commented on stencil-workspace/storybook/stories/components/modus-table/modus-table.stories.tsx
> +        const manualPaginationData = ${JSON.stringify(makeData(manualPaginationOptions?.totalRecords))};
The data would be static and only created once, so no issues that i can see.  However I requested changed (that have been made) to make sure the first page stays the same. It was changing after navigating to page 2 given the two different source datas being used.

2023-11-07 21:55 UTC, cjwinsor approved these changes

2023-11-07 21:56 UTC, merged