Modus Table - Add row actions
trimble-oss/modus-web-components pull request #1857
Opened 2023-11-06 15:12 UTC by leosole-trimble

## Description

- Added custom row actions to the Modus Table configuration with keyboard navigation.
- Up to four icons (including expandable and overflow icons) can be displayed for unlimited row actions.
- Enabled Keyboard navigation on Modus List component
- Refactored code to allow all child components to obtain details from a single context object.

References https://github.com/trimble-oss/modus-web-components/issues/1729

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

## How Has This Been Tested?

Storybook page

Go to [preview] and edit the rowActions control to add/remove row actions. Users should be able to use keyboard to select the row actions and press escape key to escape the overflow menu dropdown.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

2023-11-07 14:46 UTC, msankaran0712 requested changes
@leosole-trimble Nice work! 
Few issues, the first column is sticky even if expandable is set to false and the cell navigation using arrow keys is not enabled on the last column

2023-11-08 11:22 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-table/models/table-context.model.ts
> -  onRowActionsChange: (newVal: ModusTableRowAction[]) => void;
is this used somewhere?

2023-11-08 11:23 UTC, leosole-trimble commented on stencil-workspace/src/components/modus-table/models/table-context.model.ts
> -  onRowActionsChange: (newVal: ModusTableRowAction[]) => void;
No. I forgot to remove it from there.

2023-11-08 11:26 UTC, leosole-trimble commented on stencil-workspace/src/components/modus-table/models/table-context.model.ts
> -  onRowActionsChange: (newVal: ModusTableRowAction[]) => void;
Oh, that was a removal already hahaha. It's not being used anymore, because the row actions cell is always frozen. This was used to freeze the first cell if there are row actions

2023-11-08 11:29 UTC, msankaran0712 approved these changes

2023-11-08 11:29 UTC, merged