Issue 1877/modify radiobutton UI
trimble-oss/modus-web-components pull request #1895
Opened 2023-11-20 11:55 UTC by ElishaSamPeterPrabhu

## Description

References #

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

2023-11-21 07:28 UTC, coliff commented on stencil-workspace/src/components/modus-radio-group/modus-radio-button.vars.scss
> +$modus-radio-btn-focus-box-shadow-color: var(--modus-checkbox-focus-box-shadow-color, rgba(#217cbb, 0.6)) !default;
`rgba(#217cbb, 0.6)` is invalid CSS. The rgba() function in CSS expects three arguments for the red, green, and blue color values, and a fourth argument for the alpha channel.

2023-11-21 09:15 UTC, ElishaSamPeterPrabhu commented on stencil-workspace/src/components/modus-radio-group/modus-radio-button.vars.scss
> +$modus-radio-btn-focus-box-shadow-color: var(--modus-checkbox-focus-box-shadow-color, rgba(#217cbb, 0.6)) !default;
Modified to 
```
// Focus state
$modus-radio-btn-focus-box-shadow-color: var(--modus-checkbox-focus-box-shadow-color, #019aeb) !default;
```

2023-11-24 15:02 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-radio-group/modus-radio-button.tsx
> +  console.log('props', props.size),
remove console log

2023-11-24 15:04 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-radio-group/modus-radio-group.tsx
> +              size={radioButton.size}
each button in the radio group must not have a separate size property

2023-11-24 15:05 UTC, msankaran0712 commented on stencil-workspace/storybook/stories/components/modus-radio-group/modus-radio-group-storybook-docs.mdx
> +      size:'small'
each radio button in the group must not have a separate size

2023-11-24 15:06 UTC, msankaran0712 commented on stencil-workspace/storybook/stories/components/modus-radio-group/modus-radio-group-storybook-docs.mdx
> +      size:'small'
same, please remove size from the radio buttons in a group. Size must be set on the group component.

2023-11-24 15:07 UTC, msankaran0712 commented on stencil-workspace/storybook/stories/components/modus-radio-group/modus-radio-group.stories.tsx
> +        size:'small'
remove size from each button

2023-11-27 14:07 UTC, rthanga1 submitted a review, later dismissed

2023-11-28 06:34 UTC, ElishaSamPeterPrabhu commented on stencil-workspace/src/components/modus-radio-group/modus-radio-button.tsx
> +  console.log('props', props.size),
Removed

2023-11-28 07:50 UTC, ElishaSamPeterPrabhu commented on stencil-workspace/storybook/stories/components/modus-radio-group/modus-radio-group.stories.tsx
> +        size:'small'
Removed

2023-11-28 07:50 UTC, ElishaSamPeterPrabhu commented on stencil-workspace/storybook/stories/components/modus-radio-group/modus-radio-group-storybook-docs.mdx
> +      size:'small'
Removed

2023-11-28 07:50 UTC, ElishaSamPeterPrabhu commented on stencil-workspace/storybook/stories/components/modus-radio-group/modus-radio-group-storybook-docs.mdx
> +      size:'small'
changed now its a group property

2023-11-28 07:50 UTC, ElishaSamPeterPrabhu commented on stencil-workspace/src/components/modus-radio-group/modus-radio-group.tsx
> +              size={radioButton.size}
Changed now its a group property

2023-12-04 13:55 UTC, msankaran0712 requested changes
@ElishaSamPeterPrabhu On both light and dark themes, the focus state does not look exactly like in the Figma. Also, the inner dot looks slightly not centered (only a minor observation, no need to fix if it is difficult)

Storybook:
![image](https://github.com/trimble-oss/modus-web-components/assets/50131391/a0709040-b09a-4c7d-a267-6160420a77e2)
 
Figma:
![image](https://github.com/trimble-oss/modus-web-components/assets/50131391/85a28660-c649-42b0-b081-b63af0f622e6)

2023-12-04 14:05 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-radio-group/modus-radio-group.scss
> +    outline: 2px solid white;
White outline color is not expected on dark theme I guess

2023-12-05 11:13 UTC, ElishaSamPeterPrabhu commented
> (Optional) If possible can you please fix the bug which is about selecting the radio button when clicking outside ![RadioButtons](https://private-user-images.githubusercontent.com/50131391/287720896-36e83b6e-42b7-44b3-8583-38c707bbb797.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NzA2ODcsIm5iZiI6MTcwMTc3MDM4NywicGF0aCI6Ii81MDEzMTM5MS8yODc3MjA4OTYtMzZlODNiNmUtNDJiNy00NGIzLTg1ODMtMzhjNzA3YmJiNzk3LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDA5NTk0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhYzIwMGFkM2I5YjVlOTI0NDI0YzllY2I2Y2JiZGM2NDlmODc3MjNmMjZjMDZjYjU1YWFlNTE1MTI5MGQ1YzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ESvpGRTxKXk3QUlhED2KJy6tz2t1VLj-OHV7PWoT7_I) [ ![RadioButtons](https://private-user-images.githubusercontent.com/50131391/287720896-36e83b6e-42b7-44b3-8583-38c707bbb797.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NzA2ODcsIm5iZiI6MTcwMTc3MDM4NywicGF0aCI6Ii81MDEzMTM5MS8yODc3MjA4OTYtMzZlODNiNmUtNDJiNy00NGIzLTg1ODMtMzhjNzA3YmJiNzk3LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDA5NTk0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhYzIwMGFkM2I5YjVlOTI0NDI0YzllY2I2Y2JiZGM2NDlmODc3MjNmMjZjMDZjYjU1YWFlNTE1MTI5MGQ1YzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ESvpGRTxKXk3QUlhED2KJy6tz2t1VLj-OHV7PWoT7_I) ](https://private-user-images.githubusercontent.com/50131391/287720896-36e83b6e-42b7-44b3-8583-38c707bbb797.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NzA2ODcsIm5iZiI6MTcwMTc3MDM4NywicGF0aCI6Ii81MDEzMTM5MS8yODc3MjA4OTYtMzZlODNiNmUtNDJiNy00NGIzLTg1ODMtMzhjNzA3YmJiNzk3LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDA5NTk0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhYzIwMGFkM2I5YjVlOTI0NDI0YzllY2I2Y2JiZGM2NDlmODc3MjNmMjZjMDZjYjU1YWFlNTE1MTI5MGQ1YzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ESvpGRTxKXk3QUlhED2KJy6tz2t1VLj-OHV7PWoT7_I) [ ](https://private-user-images.githubusercontent.com/50131391/287720896-36e83b6e-42b7-44b3-8583-38c707bbb797.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE3NzA2ODcsIm5iZiI6MTcwMTc3MDM4NywicGF0aCI6Ii81MDEzMTM5MS8yODc3MjA4OTYtMzZlODNiNmUtNDJiNy00NGIzLTg1ODMtMzhjNzA3YmJiNzk3LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA1VDA5NTk0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhYzIwMGFkM2I5YjVlOTI0NDI0YzllY2I2Y2JiZGM2NDlmODc3MjNmMjZjMDZjYjU1YWFlNTE1MTI5MGQ1YzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ESvpGRTxKXk3QUlhED2KJy6tz2t1VLj-OHV7PWoT7_I)

Fixed

2023-12-05 11:14 UTC, ElishaSamPeterPrabhu commented on stencil-workspace/src/components/modus-radio-group/modus-radio-button.tsx
> +      <span class={`checkmark ${props.size}`}></span>
Moved to parent div

2023-12-05 11:14 UTC, ElishaSamPeterPrabhu commented on stencil-workspace/src/components/modus-radio-group/modus-radio-group.scss
> +    outline: 2px solid white;
Modified approach

2023-12-12 14:48 UTC, coliff commented
Radio buttons are too big. The white inner circle should be 12px height/width, but this PR has it at 14px. Can you reduce by 2px?

2023-12-13 05:38 UTC, coliff commented
Inner circle isn't centered:
![image](https://github.com/trimble-oss/modus-web-components/assets/1212885/2bb13358-f031-4d73-9fb4-19c39f5c0324)

Please squash commits and mark as ready for review when that's done - thanks!

2023-12-18 13:35 UTC, coliff approved these changes

2023-12-18 13:35 UTC, merged

2024-01-02 22:00 UTC, cjwinsor commented
@ElishaSamPeterPrabhu I see the index.html was updated. Is it possible to get a correction PR to clear it out?