Issue 1054/sentiment scale
trimble-oss/modus-web-components pull request #1905
Opened 2023-11-22 05:06 UTC by ElishaSamPeterPrabhu

## Description

References #

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

2023-11-23 05:58 UTC, coliff requested changes
This component is currently not accessible. Can we change the divs to use buttons instead? They should have hand cursor to show they can be clicked/tapped. They need aria-labels so screen readers will announce what happens when interacted with too.

2023-11-23 14:19 UTC, msankaran0712 commented on stencil-workspace/src/components/icons/IconMap.tsx
> +      return <IconSmileyNeutralOutline color={props.color} onClick={props.onClick} size={props.size} />;
For consistent naming of the icons, we can remove the suffix `solid` from all the sentiment scale icons. Example for a solid and outline icons,

![image](https://github.com/trimble-oss/modus-web-components/assets/50131391/8dd16696-745e-450b-9387-d8a4aff7c681)

2023-11-23 14:20 UTC, msankaran0712 commented on stencil-workspace/src/components/icons/icon-smiley-dissatisfied-outline.tsx
> +      fill={props.color ?? '#252A2E'}
fill should be `fill={props.color ?? 'currentColor'}`

2023-11-23 14:22 UTC, msankaran0712 commented on stencil-workspace/src/components/icons/icon-smiley-dissatisfied-outline.tsx
> +interface IconProps {
remove the interface and reuse the interface present in `IconMap.tsx`

2023-11-23 14:24 UTC, msankaran0712 commented on stencil-workspace/src/components/icons/icon-smiley-dissatisfied-solid.tsx
> +    class="icon-smiley-dissatistied-solid"
make sure the prefix `solid` is removed everywhere, including the css class

2023-11-23 14:25 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-sentiment-scale/modus-sentiment-scale.e2e.ts
> +    await page.setContent('<modus-sentiment-scale icons-type="smileys"></modus-sentiment-scale>');
change the property name `icon-type` to simply `type`

2023-11-23 14:38 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-sentiment-scale/modus-sentiment.constants.ts
> +export const MODUS_SENTIMENT_CONSTANTS = {
we do not require all these values. We need only the list if thumb scales and smiley scales. A simple Map object with a key value pair would suffice.

2023-11-24 06:41 UTC, ElishaSamPeterPrabhu commented on stencil-workspace/src/components/icons/IconMap.tsx
> +      return <IconSmileyNeutralOutline color={props.color} onClick={props.onClick} size={props.size} />;
Renamed

2023-11-24 06:49 UTC, ElishaSamPeterPrabhu commented on stencil-workspace/src/components/icons/icon-smiley-dissatisfied-outline.tsx
> +interface IconProps {
Changed

2023-11-24 06:53 UTC, ElishaSamPeterPrabhu commented on stencil-workspace/src/components/icons/icon-smiley-dissatisfied-outline.tsx
> +    width={props.size ?? '14'}
Changed

2023-11-24 06:53 UTC, ElishaSamPeterPrabhu commented on stencil-workspace/src/components/icons/icon-smiley-dissatisfied-solid.tsx
> +    class="icon-smiley-dissatistied-solid"
Removed

2023-11-24 06:55 UTC, ElishaSamPeterPrabhu commented on stencil-workspace/src/components/modus-sentiment-scale/modus-sentiment-scale.e2e.ts
> +    await page.setContent('<modus-sentiment-scale icons-type="smileys"></modus-sentiment-scale>');
changed

2023-11-24 06:56 UTC, ElishaSamPeterPrabhu commented on stencil-workspace/src/components/modus-sentiment-scale/modus-sentiment.constants.ts
> +export const MODUS_SENTIMENT_CONSTANTS = {
Yes, removed extra values

2023-11-24 09:06 UTC, coliff commented
Accessibility change requests:
- `.sentiment-scale-container` container div should have `role="group"`
- Aria-labels should be in English as they are read aloud... so for example 'aria-label="smiley-somewhat-dissatisfied"' should be `aria-label="Somewhat dissatisfied"`
- Add `cursor: pointer` CSS to the buttons

2023-11-29 14:59 UTC, coliff commented
Remaining issues from what I can see:

- Fix 'Whether the chip is disabled' text on Storybook Canvas tab
- Thumbs up/Thumbs down buttons are too big - can you make them 32 x 32 please
- Important: All the buttons need aria-labels. Thumbs up (aria-label="Helpful") and Thumbs down (aria-label="Not helpful").

2023-11-30 13:22 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-sentiment-scale/modus-sentiment-scale.tsx
> +                aria-label={this.labelMap.get(buttonIcon)}
I don't think the aria-label is getting rendered 
![image](https://github.com/trimble-oss/modus-web-components/assets/50131391/eb6c969c-5fed-4aa1-a153-9c445d9d17e5)

2023-11-30 15:53 UTC, ElishaSamPeterPrabhu commented on stencil-workspace/src/components/modus-sentiment-scale/modus-sentiment-scale.tsx
> +                aria-label={this.labelMap.get(buttonIcon)}
The aria label is added when selected should the container carry one too?
Tab index is set to -1 when disabled now

2023-12-05 05:46 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-sentiment-scale/modus-sentiment-scale.tsx
> +      console.log('type', type);
Please remove console logs

2023-12-05 05:50 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-sentiment-scale/modus-sentiment-scale.tsx
> +      console.log('type', type);
rename the watch to `typeChanged`
Coding Styleguide: https://stenciljs.com/docs/style-guide

2023-12-05 05:51 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-sentiment-scale/modus-sentiment-scale.tsx
> +    if (type) {
we don't require this extra condition `if (type)`, because `(type === THUMB_ICONS)` &  `(type === SMILEY_ICONS)` will handle nulls too

2023-12-05 06:00 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-sentiment-scale/modus-sentiment-scale.tsx
> +export interface ModusSentimentScaleItem {
- Please create a file `modus-sentiment-scale.models.tsx`  
- place all the types and interfaces in the file 
- add a new type `export type ModusSentimentScale = typeof SMILEY_ICONS | typeof THUMB_ICONS;` 
- use the above model for component property `type`
- export the model in `stencil-workspace\src\interfaces.d.ts`

2023-12-05 06:12 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-sentiment-scale/modus-sentiment.constants.ts
> +export const MODUS_SENTIMENT_CONSTANTS_THUMB = new Map([
Names for these constants could be more concise and descriptive, like `THUMBS_TYPE_MAP`

2023-12-05 06:19 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-sentiment-scale/modus-sentiment.constants.ts
> +export const MODUS_SENTIMENT_CONSTANTS_THUMB = new Map([
We don't require the prefix `Modus` unless it is exported in the `stencil-workspace\src\interfaces.d.ts` file. And, generally, it's a good practice to avoid using UI-specific terms like "icons", "buttons", etc., in your model names. Model names should ideally represent the data or the business logic of your application, and not be tied to specific UI implementations.

2023-12-05 06:34 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-sentiment-scale/modus-sentiment-scale.tsx
> +      const selectedSentiment = selectedOutlineIcon;
do we need this constant here?

2023-12-05 07:28 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-sentiment-scale/modus-sentiment-scale.tsx
> +@Component({
Refactored code:

``` js
import { Component, Prop, State, h, Event, EventEmitter } from '@stencil/core';
import { IconMap } from '../icons/IconMap';
import { SMILEYS_TYPE_MAP, SMILEY_SENTIMENT_TYPE, THUMBS_TYPE_MAP, THUMB_SENTIMENT_TYPE } from './modus-sentiment.constants';

@Component({
  tag: 'modus-sentiment-scale',
  styleUrl: 'modus-sentiment-scale.scss',
  shadow: true,
})
export class ModusSentimentScale {
  /** (optional) Tab Index for the checkbox */
  @Prop() tabIndexValue = 0;

  /** (optional) The input's aria-label. */
  @Prop() ariaLabel: string | null;

  /** The type of icons to be displayed. */
  @Prop() type: typeof SMILEY_SENTIMENT_TYPE | typeof THUMB_SENTIMENT_TYPE = 'smileys';

  /** (optional) Whether the sentiment scale is disabled. */
  @Prop() disabled?: boolean = false;

  /** An event that fires the selected sentiment. */
  @Event() sentimentSelection: EventEmitter;

  @State() selected: string;

  getSentimentScaleMap(): Map<string, string> {
    if (this.type === THUMB_SENTIMENT_TYPE) {
      return THUMBS_TYPE_MAP;
    } else if (this.type === SMILEY_SENTIMENT_TYPE) {
      return SMILEYS_TYPE_MAP;
    }
    return null;
  }

  handleSentimentClick(selected: string) {
    if (!this.disabled) {
      this.selected = selected;
      this.sentimentSelection.emit(selected);
    }
  }

  handleKeyDown(event: KeyboardEvent, id: string) {
    if (event.code.toUpperCase() !== 'ENTER') {
      return;
    }

    this.handleSentimentClick(id);
  }

  render() {
    const tabIndexValue = this.disabled ? -1 : this.tabIndexValue;
    const iconsMap = this.getSentimentScaleMap();

    let containerClass = `${this.type + '-container'} ${this.disabled ? ' disabled' : ''}`;

    return (
      <div class="sentiment-scale-container" role="group">
        {Array.from(iconsMap).map(([key, value]) => {
          const isIconSelected = key === this.selected;
          let iconName = key;
          if (isIconSelected) {
            iconName = `${key}-outlined`;
            containerClass = `${containerClass} selected`;
          }

          return (
            <div
              aria-label={value}
              aria-selected={isIconSelected}
              role="button"
              tabIndex={tabIndexValue}
              class={containerClass}
              onClick={() => this.handleSentimentClick(key)}
              onKeyDown={(event) => this.handleKeyDown(event, key)}>
              <IconMap icon={iconName} size={`${this.type === THUMB_SENTIMENT_TYPE ? '32' : '24'}`}></IconMap>
            </div>
          );
        })}
      </div>
    );
  }
}

```

2023-12-05 07:30 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-sentiment-scale/modus-sentiment-scale.tsx
> +@Component({
constants:

``` js
export const SMILEY_SENTIMENT_TYPE = 'smileys';
export const THUMB_SENTIMENT_TYPE = 'thumbs';

export const THUMBS_TYPE_MAP = new Map([
  ['thumbs-up', 'Helpful'],
  ['thumbs-down', 'Not helpful'],
]);

export const SMILEYS_TYPE_MAP = new Map([
  ['smiley-dissatisfied', 'Smiley Dissatisfied'],
  ['smiley-somewhat-dissatisfied', 'Smiley Somewhat Dissatisfied'],
  ['smiley-neutral', 'Smiley Neutral'],
  ['smiley-somewhat-satisfied', 'Smiley Somewhat Satisfied'],
  ['smiley-satisfied', 'Smiley Satisfied'],
]);

```

models:
``` js
import { SMILEY_SENTIMENT_TYPE, THUMB_SENTIMENT_TYPE } from "./modus-sentiment.constants";

export type ModusSentimentScaleType = typeof SMILEY_SENTIMENT_TYPE  | typeof THUMB_SENTIMENT_TYPE ;
```

2023-12-05 07:31 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-sentiment-scale/modus-sentiment-scale.tsx
> +@Component({
@ElishaSamPeterPrabhu I have removed the `icon-container` in the refactored code as we already have `smileys-container` & `thumbs-container`

2023-12-05 07:31 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-sentiment-scale/modus-sentiment-scale.tsx
> +@Component({
Please update the CSS accordingly

2023-12-05 07:33 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-sentiment-scale/modus-sentiment-scale.scss
> +  .smileys-container {
I have removed the `icon-container` in the refactored code as we already have `smileys-container ` & `thumbs-container`. There are some common styles for smiley and thumbs like, `align-items`, `display`... etc, put the common styles under one selector.

2023-12-05 07:47 UTC, msankaran0712 commented on stencil-workspace/storybook/stories/components/modus-sentiment-scale/modus-sentiment-scale-storybook-docs.mdx
> +The `modus-sentiment-scale` component provides a customizable sentiment scale that allows users to select a sentiment from a predefined set using icons. It supports both smiley and thumb icons.
Please rewrite it as,

The [Modus Sentiment Scale](https://modus.trimble.com/components/web/sentiment-scale/) component offers a configurable sentiment scale for users to choose a sentiment from predefined options. This component supports both smiley and thumb icon types. They are referenced using the `<modus-sentiment-scale>` custom HTML element.

2023-12-05 07:48 UTC, msankaran0712 commented on stencil-workspace/storybook/stories/components/modus-sentiment-scale/modus-sentiment-scale-storybook-docs.mdx
> +| States                | Description                                                  | Type                            |
Please remove `states` API section

2023-12-05 07:49 UTC, msankaran0712 commented on stencil-workspace/storybook/stories/components/modus-sentiment-scale/modus-sentiment-scale-storybook-docs.mdx
> +| Methods                  | Description                                             | Parameters                           |
Please remove `Methods` API section

2023-12-06 10:10 UTC, ElishaSamPeterPrabhu commented on stencil-workspace/src/components/modus-sentiment-scale/modus-sentiment-scale.tsx
> +export interface ModusSentimentScaleItem {
Done

2023-12-06 10:10 UTC, ElishaSamPeterPrabhu commented on stencil-workspace/src/components/modus-sentiment-scale/modus-sentiment-scale.tsx
> +    if (type) {
Removed and refactored according to the below code

2023-12-06 10:10 UTC, ElishaSamPeterPrabhu commented on stencil-workspace/src/components/modus-sentiment-scale/modus-sentiment-scale.tsx
> +      console.log('type', type);
Removed and refactored according to the below code

2023-12-06 10:11 UTC, ElishaSamPeterPrabhu commented on stencil-workspace/src/components/modus-sentiment-scale/modus-sentiment-scale.tsx
> +      const selectedSentiment = selectedOutlineIcon;
No, Removed and refactored according to the below code

2023-12-06 10:11 UTC, ElishaSamPeterPrabhu commented on stencil-workspace/src/components/modus-sentiment-scale/modus-sentiment-scale.tsx
> +@Component({
Applied changes and modifed css

2023-12-06 10:11 UTC, ElishaSamPeterPrabhu commented on stencil-workspace/src/components/modus-sentiment-scale/modus-sentiment-scale.scss
> +  .smileys-container {
Applied changes and modifed css

2023-12-06 10:11 UTC, ElishaSamPeterPrabhu commented on stencil-workspace/storybook/stories/components/modus-sentiment-scale/modus-sentiment-scale-storybook-docs.mdx
> +The `modus-sentiment-scale` component provides a customizable sentiment scale that allows users to select a sentiment from a predefined set using icons. It supports both smiley and thumb icons.
Done

2023-12-06 10:11 UTC, ElishaSamPeterPrabhu commented on stencil-workspace/storybook/stories/components/modus-sentiment-scale/modus-sentiment-scale-storybook-docs.mdx
> +| States                | Description                                                  | Type                            |
Removed

2023-12-06 10:11 UTC, ElishaSamPeterPrabhu commented on stencil-workspace/storybook/stories/components/modus-sentiment-scale/modus-sentiment-scale-storybook-docs.mdx
> +| Methods                  | Description                                             | Parameters                           |
Removed

2023-12-07 10:16 UTC, msankaran0712 commented
> This component is currently not accessible. Can we change the divs to use buttons instead? They should have hand cursor to show they can be clicked/tapped. They need aria-labels so screen readers will announce what happens when interacted with too.

@coliff is this resolved?

2023-12-07 10:27 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-sentiment-scale/modus-sentiment.constants.ts
> +export const THUMB_SENTIMENT_TYPE = 'thumbs';
file name is not consistent

2023-12-07 10:29 UTC, msankaran0712 commented on stencil-workspace/src/interfaces.d.ts
> +export { ModusSentimentScale } from './components/modus-sentiment-scale/modus-sentiment-scale';
I think the import path is not correct. Please check if the VS code is able to navigate to the file by clicking F12

2023-12-07 10:33 UTC, msankaran0712 requested changes
![image](https://github.com/trimble-oss/modus-web-components/assets/50131391/3611e159-2216-4e9e-96bc-621e516bf2cc)

2023-12-07 10:42 UTC, msankaran0712 commented
@ElishaSamPeterPrabhu once you rebase your branch, you should be able to see `https://github.com/trimble-oss/modus-web-components/tree/main/angular-workspace/test-web-components`. Use `npm pack` on Stencil Workspace to generate a `.tgz`, an installable file and install it on the angular test web components project and build that project.

2023-12-07 12:36 UTC, ElishaSamPeterPrabhu commented
> In focus border is visible, the smiley is not centered. Same issue with Thumbs up & down
> 
> ![image](https://private-user-images.githubusercontent.com/50131391/288727758-88c06b5d-a6e5-4f09-8057-0d695587969e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5NTI4NTEsIm5iZiI6MTcwMTk1MjU1MSwicGF0aCI6Ii81MDEzMTM5MS8yODg3Mjc3NTgtODhjMDZiNWQtYTZlNS00ZjA5LTgwNTctMGQ2OTU1ODc5NjllLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA3VDEyMzU1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmNTY4NTlhZWNhODE3ZmM4MTM5MzRkNWEwZGMyNGViNWQzZjQ4ZmM3OWE0YjI4NDliOGQ4MDM5YmY5OWViZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.T5_9FwHxlim4btpPHt_9OIkYuDbQFGITTX8SvUPDvXU)

Centered

2023-12-07 15:46 UTC, ElishaSamPeterPrabhu commented on stencil-workspace/storybook/stories/components/modus-sentiment-scale/modus-sentiment-scale-storybook-docs.mdx
> +
Added headers

2023-12-07 16:45 UTC, ElishaSamPeterPrabhu commented
> ![image](https://private-user-images.githubusercontent.com/50131391/288726645-3611e159-2216-4e9e-96bc-621e516bf2cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5NTgyNDgsIm5iZiI6MTcwMTk1Nzk0OCwicGF0aCI6Ii81MDEzMTM5MS8yODg3MjY2NDUtMzYxMWUxNTktMjIxNi00ZTllLTk2YmMtNjIxZTUxNmJmMmNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA3VDE0MDU0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJjMjQ5YWU2NGZjNGZmYzZlYTM1YTk0ZTQ2ZjM2ODhiOGM1NzFkMDMyYTQyMDU0N2YzZWU5YWQ4MDllYzgwYTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hZs_z2556w5spOdmAjWLhhxE9V_EceEa5e_SVvhy-Tw)

Replaced with aria-checked and values are passed to them as "true" or "false"

2023-12-08 08:42 UTC, coliff submitted a review, later dismissed

2023-12-08 15:00 UTC, msankaran0712 commented on stencil-workspace/src/global/themes.scss
> +  --modus-sentiment-scale-bg: #252a2e;
Generally, try to reuse the css color variables. For example, `#252a2e` is replaceable by `--modus-trimble-gray`. Reuse the variables from Line 1 - Line 71 for the light theme and from line 423 - line 439 for the dark theme.

2023-12-08 15:05 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-sentiment-scale/modus-sentiment-scale.tsx
> +  /** (optional) Tab Index for the checkbox */
Incorrect description

2023-12-08 15:06 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-sentiment-scale/modus-sentiment-scale.tsx
> +  @Prop() tabIndexValue = 0;
I don't think we need this property

2023-12-08 16:50 UTC, ElishaSamPeterPrabhu commented on stencil-workspace/src/components/modus-sentiment-scale/modus-sentiment-scale.tsx
> +  /** (optional) Tab Index for the checkbox */
Removed the Prop

2023-12-08 16:50 UTC, ElishaSamPeterPrabhu commented on stencil-workspace/src/components/modus-sentiment-scale/modus-sentiment-scale.tsx
> +  @Prop() tabIndexValue = 0;
Removed the Prop

2023-12-08 17:14 UTC, ElishaSamPeterPrabhu commented on stencil-workspace/src/global/themes.scss
> +  --modus-sentiment-scale-bg: #252a2e;
Renamed to modus-gray and modus blue for other colors

2023-12-11 09:24 UTC, msankaran0712 commented on stencil-workspace/src/global/themes.scss
> +  --modus-sentiment-scale-bg: #90939f;
Please do the same for dark theme, for reusing the CSS variables

2023-12-11 09:33 UTC, ElishaSamPeterPrabhu commented on stencil-workspace/src/global/themes.scss
> +  --modus-sentiment-scale-bg: #90939f;
Modfied

2023-12-11 09:36 UTC, msankaran0712 approved these changes

2023-12-11 09:45 UTC, msankaran0712 approved these changes

2023-12-11 09:46 UTC, merged