Ability to render Table with pre selected rows
trimble-oss/modus-web-components pull request #1906
Opened 2023-11-22 13:42 UTC by leosole-trimble

## Description

References #

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

2023-11-23 14:47 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-table/modus-table.tsx
> +  @Prop() preSelectedRows: string[];
I would suggest moving this to rowSelectionOptions

2023-11-23 15:43 UTC, msankaran0712 requested changes

2023-11-23 15:43 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-table/modus-table.tsx
> +    if (parent) return `${parent.id}.${index}`;
did you test the nested rows with more than two levels?

2023-11-23 15:43 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-table/modus-table.tsx
> +    if (parent) return `${parent.id}.${index}`;
also, should test `handleCellValueChange` on the modus-table-body component since it uses row id for data update

2023-11-23 15:48 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-table/modus-table.tsx
> +    this.preSelectedRows?.forEach((row) => (selection[row] = true));
We can achieve the result using map function too I think, any reason for using foreach?

2023-11-23 15:59 UTC, leosole-trimble commented on stencil-workspace/src/components/modus-table/modus-table.tsx
> +    this.preSelectedRows?.forEach((row) => (selection[row] = true));
I used forEach, because the map would return an array and I needed an object like `{"id": true}`

2023-11-23 16:00 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-table/modus-table.tsx
> +  getPreselectedState(): RowSelectionState {
method can be renamed to getPreselectedRowState

2023-11-23 16:04 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-table/modus-table.e2e.ts
>  ];
can we have unit test for pre selection rows?

2023-11-23 16:24 UTC, leosole-trimble commented on stencil-workspace/src/components/modus-table/modus-table.tsx
> +    if (parent) return `${parent.id}.${index}`;
if the row id is not set, `handleCellValueChange` works, but it stops working if the id is set by the user.

2023-11-24 14:40 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-table/modus-table.e2e.ts
> +    const rowsSelected = await page.findAll('modus-table >>> row-selected');
is the css selector missing a `.` for row-selected css class?

2023-11-24 14:43 UTC, msankaran0712 commented on stencil-workspace/storybook/stories/components/modus-table/modus-table.stories.tsx
> +  modusTable.preSelectedRows = ${JSON.stringify(preSelectedRows)};
Now that the property is moved into rowSelectionOptions, this needs to be changed too

2023-11-24 14:43 UTC, msankaran0712 commented on stencil-workspace/storybook/stories/components/modus-table/modus-table.stories.tsx
> +    preSelectedRows: {
here too

2023-11-24 14:46 UTC, msankaran0712 commented
@leosole-trimble Please fix the review comments and test the row selection and inline editing for nested rows on a large dataset before merging the PR. Please check with @coliff or @cjwinsor to review and approve, I will be on leave on Monday.

2023-11-24 14:55 UTC, leosole-trimble commented on stencil-workspace/src/components/modus-table/modus-table.e2e.ts
> +    const rowsSelected = await page.findAll('modus-table >>> row-selected');
you are right, but it still doesn't work with the `.`

2023-11-30 14:23 UTC, msankaran0712 submitted a review, later dismissed

2023-11-30 14:28 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-table/modus-table.tsx
> +        .flatRows.map((row) => {
Thank you @leosole-trimble

2023-11-30 14:29 UTC, msankaran0712 approved these changes

2023-11-30 14:30 UTC, msankaran0712 approved these changes

2023-12-01 05:44 UTC, merged