Autocomplete: Add chip support
trimble-oss/modus-web-components pull request #1927
Opened 2023-12-04 02:53 UTC by ElishaSamPeterPrabhu

## Description

- Added multiple selection feature when enabled adds chips inside the new input container
- Modified the text container ("chips-container") which will have the modus text input and before it to fold the chips and search icon is positioned. the clearable icon is also positioned inside the "chips-container" at the end.
- Error text label holder is present below the "chips-container"

References #1543

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

2023-12-18 05:25 UTC, rthanga1 commented
Please add a space between chips

2023-12-19 05:10 UTC, ElishaSamPeterPrabhu commented
Figma referred : https://www.figma.com/file/7yC5vYgdbzqaEJDr566xAL/SUBMISSION-V1---Work-in-Progress?type=design&node-id=5-9125&mode=design&t=FZ2VUIsHXfwjIBvX-0

2023-12-20 14:41 UTC, rthanga1 commented
@ElishaSamPeterPrabhu Can you resolve the conflicts?

2023-12-22 14:07 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-checkbox/modus-checkbox.scss
> +      margin-right: 4px;
Why is a checkbox changed? if this is not related to the current PR, please create a separate PR linking the respective issue

2023-12-22 14:10 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
> +  @Prop() showOptionsOnFocus: boolean;
Is the branch rebased from `main` ? If yes, `showOptionsOnFocus` should not be listed as a new change

2023-12-22 14:17 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
> +  @Prop() addChip: boolean;
@cjwinsor, any thoughts on the prop name? I would say, simply `chips`

2023-12-22 14:18 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
> +  @Prop() includeSearchIcon = false;
why is the default changed?

2023-12-22 14:24 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
> +  handleCloseClick(chipValue: string) {
In Storybook, the close icon is only visible when something is typed into the search box. It doesn't appear when options are selected and shown as chips. This means that I have to type something to make the close icon visible and clear the chips. However, in Material UI, the focus remains on the search box after every selection, so the close icon is always visible. Our Autocomplete component does not currently work this way. Should we consider bringing the focus back to the search box after a selection is made? @cjwinsor @rthanga1

2023-12-22 14:27 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.spec.ts
>        <mock:shadow-root>
Please remember to add End-to-end unit tests for any component update. I don't see this file `stencil-workspace\src\components\modus-autocomplete` committed. @rthanga1 @ElishaSamPeterPrabhu

2023-12-22 14:27 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.spec.ts
>        <mock:shadow-root>
As we don't have a `QA` unit, tests are the only way the components are tested every time a release is made.

2023-12-22 14:29 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
> +  @Prop() showOptionsOnFocus: boolean;
Please order the props alphabetically

2023-12-22 14:40 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
> +  @Prop() includeSearchIcon = false;
On Storybook, changing the value for `includeSearchIcon` is doing nothing. Please thoroughly test all the properties and whether it is breaking any existing functionality. @rthanga1 @ElishaSamPeterPrabhu

2023-12-22 14:43 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
> +  @Prop() addChip: boolean;
The description of this property is different on Storybook API documentation. Please make sure every time you copy the API sections from `modus-autocomplete/readme.md` and paste it on Storybook pages; otherwise, it won't be consistent. It applies to all the components. @rthanga1 @ElishaSamPeterPrabhu

2023-12-22 14:44 UTC, msankaran0712 commented on stencil-workspace/storybook/stories/components/modus-autocomplete/modus-autocomplete-storybook-docs.mdx
> +|`addChip`                    | `add-chip`                      | Whether to add a chip when an option is selected. | `boolean`                            | `false`
This description is better than what is written inside the component.

2023-12-22 14:44 UTC, msankaran0712 commented on stencil-workspace/storybook/stories/components/modus-autocomplete/modus-autocomplete.stories.tsx
> +      description: "Adds chips functionality to the autocomplete",
Not a clear description, better to stick with the component API description

2023-12-22 14:48 UTC, msankaran0712 commented on stencil-workspace/storybook/stories/components/modus-autocomplete/modus-autocomplete.stories.tsx
> +export const WithChips = ({
Please refer to `modus-table.stories` file for how a template is reused on each example. Could you move away from the way of manually rewriting the entire sample code and encourage reusability?  When we start doing it on the components we work on, other contributors will follow the same. @rthanga1 @ElishaSamPeterPrabhu

2023-12-22 14:50 UTC, msankaran0712 commented on stencil-workspace/storybook/stories/components/modus-autocomplete/modus-autocomplete.stories.tsx
> +export const WithChips = ({
And also, any new property must be added to all the example codes because the person who is checking out the docs might try out any of the controls on any of the examples. By updating/adding a prop only on one example, will not make the prop usable on other examples. @rthanga1 @ElishaSamPeterPrabhu

2023-12-22 14:53 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
> +  @Prop() includeSearchIcon = false;
It can become a breaking change because the teams must be assuming the search icon is true by default @rthanga1 @ElishaSamPeterPrabhu

2024-01-02 05:32 UTC, ElishaSamPeterPrabhu commented on stencil-workspace/src/components/modus-checkbox/modus-checkbox.scss
> +      margin-right: 4px;
Okay, removed

2024-01-02 05:37 UTC, ElishaSamPeterPrabhu commented on stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
> +  @Prop() addChip: boolean;
Modified to what is present in the storybooks

2024-01-02 05:37 UTC, ElishaSamPeterPrabhu commented on stencil-workspace/storybook/stories/components/modus-autocomplete/modus-autocomplete-storybook-docs.mdx
> +|`addChip`                    | `add-chip`                      | Whether to add a chip when an option is selected. | `boolean`                            | `false`
Modified in the autocompelete.tsx

2024-01-02 05:38 UTC, ElishaSamPeterPrabhu commented on stencil-workspace/storybook/stories/components/modus-autocomplete/modus-autocomplete.stories.tsx
> +      description: "Adds chips functionality to the autocomplete",
Modified to this "Whether to add a chip when an option is selected."

2024-01-02 09:45 UTC, ElishaSamPeterPrabhu commented on stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
> +  @Prop() showOptionsOnFocus: boolean;
Arranged alphabetically

2024-01-02 09:45 UTC, ElishaSamPeterPrabhu commented on stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
> +  @Prop() includeSearchIcon = false;
Modified by adding search icon

2024-01-02 10:02 UTC, ElishaSamPeterPrabhu commented on stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.spec.ts
>        <mock:shadow-root>
Test cases are committed now

2024-01-03 07:44 UTC, ElishaSamPeterPrabhu commented on stencil-workspace/storybook/stories/components/modus-autocomplete/modus-autocomplete.stories.tsx
> +export const WithChips = ({
1. Modified code to use templates.
2. Question: What are the properties we need to show in the docs ? and which of the require a separate page?

2024-01-03 07:44 UTC, ElishaSamPeterPrabhu commented on stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
> +  @Prop() includeSearchIcon = false;
Set back to true

2024-01-05 09:06 UTC, rthanga1 commented on stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
> +  @Prop() addChip: boolean;
Material UI autocomplete uses the 'multiple'. I think that suits well. @ElishaSamPeterPrabhu Can you use that?

2024-01-05 09:10 UTC, rthanga1 commented on stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
> +  handleCloseClick(chipValue: string) {
We discussed about this before. And we agreed to show the clear button during hover and focus events. We will address it as part of another ticket. There are few other improvements were also discussed during our call. I will udpate them in the issue,
 @ElishaSamPeterPrabhu Please create an issue and resolve this convo

2024-01-05 09:11 UTC, rthanga1 commented on stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
> +  @Prop() addChip: boolean;
Update this
"When enabled, multiple options can be selected in the component. And selected options are shown as chips in the input."

2024-01-05 09:13 UTC, rthanga1 commented on stencil-workspace/storybook/stories/components/modus-autocomplete/modus-autocomplete.stories.tsx
> +      description: "Adds chips functionality to the autocomplete",
Change to 'multiple'

2024-01-08 05:29 UTC, ElishaSamPeterPrabhu commented on stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
> +  @Prop() addChip: boolean;
Changed to mutiple

2024-01-08 06:21 UTC, rthanga1 requested changes

2024-01-08 06:21 UTC, rthanga1 commented on stencil-workspace/src/components/modus-autocomplete/readme.md
> +| `addChip`                   | `add-chip`                      | Whether to add a chip when an option is selected.  | `boolean`                               | `undefined`
To be updated

2024-01-08 06:21 UTC, rthanga1 commented on stencil-workspace/storybook/stories/components/modus-autocomplete/modus-autocomplete.stories.tsx
> +export const WithChips = Template.bind({});
Should be 'Multiple Selection'

2024-01-08 13:05 UTC, rthanga1 submitted a review, later dismissed

2024-01-08 14:57 UTC, apaddock commented
https://modus.ideas.aha.io/ideas/MOD-I-7 

This is still under "Needs Review" in Aha...

2024-01-18 19:16 UTC, apaddock commented
<img width="709" alt="image" src="https://github.com/trimble-oss/modus-web-components/assets/4574058/324658c7-ee08-40f3-996f-905d536f762c">

Appears broken. duplicating the search icon and the label

2024-01-19 05:10 UTC, ElishaSamPeterPrabhu commented
> https://deploy-preview-1927--moduswebcomponents.netlify.app

@apaddock 
For some reason https://deploy-preview-1927--moduswebcomponents.netlify.app/ this link commented by the netifly bot just above the recent commit is working properly.
![image](https://github.com/trimble-oss/modus-web-components/assets/122255626/88faecdb-5d69-45e2-b00b-55d0f2cb4cd8)

2024-02-15 04:40 UTC, cjwinsor commented
@ElishaSamPeterPrabhu My only comment is why the Label text is smaller now, i'm not sure if this was discussed in the PR and I overlooked it or if it was part of some figma or other documentation.

PR:
![image](https://github.com/trimble-oss/modus-web-components/assets/1130129/7294b865-62f0-494a-908e-1adb930a5b57)

Previous:
![image](https://github.com/trimble-oss/modus-web-components/assets/1130129/5f1dead1-950e-41e3-b631-f74d6d1602c0)

2024-02-15 10:15 UTC, ElishaSamPeterPrabhu commented
> @ElishaSamPeterPrabhu My only comment is that it doesn't look like we are marking the items that were selected when the options list is opened back up.

 @cjwinsor Its unmarked in figma, I can update the list if that's were we are headed.

2024-02-20 23:25 UTC, cjwinsor commented
Last thing we need for this story is that the selected items are highlighted like a list item would be.  So today it looks like this with `disable-close-on-select` enabled

![image](https://github.com/trimble-oss/modus-web-components/assets/1130129/8eb4755f-70f6-41df-bad5-a36a0f2b9971)

But if you close and reopen its not still marked as selected.

We want any selected items to be marked like the condensed and selected example for list
![image](https://github.com/trimble-oss/modus-web-components/assets/1130129/434788a4-80b8-4ae7-a517-0ed997eaf8a4)

For custom options, just set the background color.. don't worry about the check mark for those.  We may need to consider that differently in the future

2024-02-21 13:13 UTC, ElishaSamPeterPrabhu commented
> @ElishaSamPeterPrabhu Last thing we need for this story is that the selected items are highlighted like a list item would be. So today it looks like this with `disable-close-on-select` enabled
> 
> ![image](https://private-user-images.githubusercontent.com/1130129/306444021-8eb4755f-70f6-41df-bad5-a36a0f2b9971.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1MjA5MDcsIm5iZiI6MTcwODUyMDYwNywicGF0aCI6Ii8xMTMwMTI5LzMwNjQ0NDAyMS04ZWI0NzU1Zi03MGY2LTQxZGYtYmFkNS1hMzZhMGYyYjk5NzEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjFUMTMwMzI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTk5NGE0YmFjMTIxNWMyMTEwOGI3NjdhYjMwYzlhYzcwOWRlMTQzODZhNzQ0NDMzZTRjZmQyOGE0OGE4MDJjNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.5knX2oxafU7B4wmd_q76z6tIwaheSKZllby71nNoNb0)
> 
> But if you close and reopen its not still marked as selected.
> 
> We want any selected items to be marked like the condensed and selected example for list ![image](https://private-user-images.githubusercontent.com/1130129/306444492-d75ebfd6-43c2-4696-a714-51bad61711e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1MjA5MDcsIm5iZiI6MTcwODUyMDYwNywicGF0aCI6Ii8xMTMwMTI5LzMwNjQ0NDQ5Mi1kNzVlYmZkNi00M2MyLTQ2OTYtYTcxNC01MWJhZDYxNzExZTkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjFUMTMwMzI3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDc2Y2JhZGQ3NWMwODUxZjIwNjQxODRkNmY4OWFhMDgxMGI1MmY2NjFkMmIwOTEyMTFjM2I3OTgyM2UzOGZmZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.lz4t99_QrlT6cXG_kFVjAApg5jkiVacrrbhbAX4-Lig) Don't worry about the padding/height at this time, just get that checkmark and background color correct. Consider dark theme as well.
> 
> For custom options, just set the background color.. don't worry about the check mark for those. We may need to consider that differently in the future

Updated the selected option

2024-02-21 15:04 UTC, cjwinsor approved these changes

2024-02-21 20:39 UTC, merged