Fixed exception trying to access oldVal.pageCount in manual pagination
trimble-oss/modus-web-components pull request #1932
Opened 2023-12-05 22:42 UTC by rjavier-trimbler

## Description

- Fixed issue when the manualPaginationOptions value is undefined and the property is set to something else. Code was throwing an exception trying to access oldVal.pageCount value in the conditional statement.

- Fixed typo setting manualPagination option instead of manualSorting in the onManualSortOptionsChange watch.

References #1908 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

2023-12-05 22:44 UTC, rjavier-trimbler commented on stencil-workspace/src/components/modus-table/modus-table.tsx
> -        this.tableCore.setOptions('manualPagination', true);
we found this issue when testing the manual sorting in our product.

2023-12-05 22:45 UTC, rjavier-trimbler commented on stencil-workspace/src/components/modus-table/parts/modus-table-pagination.tsx
> +    pageIndex = activePage - 1;
fixing issue showing always the range 1-{pageSize} with manual pagination

2023-12-05 22:45 UTC, rjavier-trimbler commented on stencil-workspace/storybook/stories/components/modus-table/modus-table.stories.tsx
> +  var globalData = ${JSON.stringify(data)};
Using 50 rows of input to test manual pagination properly. Updating code below to load only the first page.

2023-12-06 18:26 UTC, cjwinsor requested changes

2023-12-06 18:26 UTC, cjwinsor commented on stencil-workspace/storybook/stories/components/modus-table/modus-table.stories.tsx
> +    subRowSelection: true
Is this change intentional?

2023-12-06 18:26 UTC, cjwinsor commented on stencil-workspace/storybook/stories/components/modus-table/modus-table.stories.tsx
> +  data: makeData(50),
Are these changes intentional

2023-12-06 18:28 UTC, cjwinsor commented
@rjavier-trimbler Given that this issue wasn't uncovered due to missing test scenarios. I am asking that more test scenarios be added to cover various cases with manual pagination.  Most specifically, any tests that would have caught this issue.

2023-12-08 05:15 UTC, rjavier-trimbler commented on stencil-workspace/src/components/modus-table/modus-table.tsx
> +  )  {
done!

2023-12-08 05:15 UTC, rjavier-trimbler commented on stencil-workspace/src/components/modus-table/modus-table.tsx
> +        pageSize: newVal.currentPageSize
done!

2023-12-11 23:44 UTC, cjwinsor requested changes
Manually testing the property changes expressed in the e2e tests exposes something strange
```html
    <modus-table></modus-table>
    <script>
      function sleep(ms) {
          return new Promise(resolve => setTimeout(resolve, ms));
      }

      async function updateTableProperties() {
          const table = document.querySelector('modus-table');

          table.columns = [
              {
                header: 'Mock Column One',
                accessorKey: 'mockColumnOne',
                id: 'mock-column-one',
                dataType: 'text',
                footer: 'Total',
              },
              {
                header: 'Mock Column Two',
                accessorKey: 'mockColumnTwo',
                id: 'mock-column-two',
                dataType: 'integer',
                showTotal: true,
              },
            ];
            table.data = [
              {
                mockColumnOne: 'Mock Data One 1',
                mockColumnTwo: 330160,
              },
              {
                mockColumnOne: 'Mock Data One 2',
                mockColumnTwo: 900293,
              },
            ];
          table.manualPaginationOptions = {};
          table.pagination = false;

          // Wait for 5 seconds
          await sleep(5000);

          table.pagination = true;
      }
      document.addEventListener('DOMContentLoaded', updateTableProperties);
    </script>
```

![image](https://github.com/trimble-oss/modus-web-components/assets/1130129/231f2c4f-79c0-4238-962f-11daed77e003)

Same result if I do this after the sleep
```js
          table.manualPaginationOptions = {
              currentPageIndex: undefined,
              currentPageSize: undefined,
              pageCount: undefined,
              totalRecords: undefined,
          };
          table.pageSizeList = [5, 10, 50];
          table.pagination = true;
```

I'll need to consider how this should behave and I still need to test this same scenario with the `main` branch to see if it will cause the original issue the bug was opened for.

2023-12-12 14:14 UTC, rjavier-trimbler commented
> Manually testing the property changes expressed in the e2e tests exposes something strange
> 
> ```
>     <modus-table></modus-table>
>     <script>
>       function sleep(ms) {
>           return new Promise(resolve => setTimeout(resolve, ms));
>       }
> 
>       async function updateTableProperties() {
>           const table = document.querySelector('modus-table');
> 
>           table.columns = [
>               {
>                 header: 'Mock Column One',
>                 accessorKey: 'mockColumnOne',
>                 id: 'mock-column-one',
>                 dataType: 'text',
>                 footer: 'Total',
>               },
>               {
>                 header: 'Mock Column Two',
>                 accessorKey: 'mockColumnTwo',
>                 id: 'mock-column-two',
>                 dataType: 'integer',
>                 showTotal: true,
>               },
>             ];
>             table.data = [
>               {
>                 mockColumnOne: 'Mock Data One 1',
>                 mockColumnTwo: 330160,
>               },
>               {
>                 mockColumnOne: 'Mock Data One 2',
>                 mockColumnTwo: 900293,
>               },
>             ];
>           table.manualPaginationOptions = {};
>           table.pagination = false;
> 
>           // Wait for 5 seconds
>           await sleep(5000);
> 
>           table.pagination = true;
>       }
>       document.addEventListener('DOMContentLoaded', updateTableProperties);
>     </script>
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/1130129/289701723-231f2c4f-79c0-4238-962f-11daed77e003.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzOTA1NTEsIm5iZiI6MTcwMjM5MDI1MSwicGF0aCI6Ii8xMTMwMTI5LzI4OTcwMTcyMy0yMzFmMmM0Zi03OWMwLTQyMzgtOTYyZi0xMWRhZWQ3N2UwMDMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMTJUMTQxMDUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2YzY2JlMzVkMzNjOGEyNWIyNThjMTQ3MjhmNGM3ZGVkYzdjOGMwMDFhNjQ1ZGIyMjlhMjVmOTdmMzA2NWM1NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.vkgyEI1hTPik1jyoTl1aoVa7W2nJsRqoMnkqaSARGeU)
> 
> Same result if I do this after the sleep
> 
> ```js
>           table.manualPaginationOptions = {
>               currentPageIndex: undefined,
>               currentPageSize: undefined,
>               pageCount: undefined,
>               totalRecords: undefined,
>           };
>           table.pageSizeList = [5, 10, 50];
>           table.pagination = true;
> ```
> 
> I'll need to consider how this should behave and I still need to test this same scenario with the `main` branch to see if it will cause the original issue the bug was opened for.

In this case  we're setting an empty object and then changing to the correct properties after the timeout is over, for this particular case we have included to re-render the table again.

2023-12-14 21:32 UTC, cjwinsor approved these changes

2023-12-14 21:33 UTC, merged