Add density property to Modus Table
trimble-oss/modus-web-components pull request #1948
Opened 2023-12-12 17:12 UTC by yohernandez

## Description

- Add density property to Modus Table component.
- Update SCSS files to set the row height based on the property value: 
    - Relaxed (default) -> 3rem
    - Comfortable -> 2rem
    - Compact -> 1.5rem
- Add unit and e2e tests.
- Update Storybook

References #1930

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] Documentation update

## How Has This Been Tested?

Added a unit test and a e2e test to verify that a change in the density property update the table class properly. All tests passed sucessfully. 
Manually tested different scenarios in Storybook like badge, column resize and reorder, inline editing, row actions, expandable rows, row selection, etc.

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [X] I have checked my code and corrected any misspellings

2023-12-14 22:57 UTC, cjwinsor requested changes

2023-12-14 22:57 UTC, cjwinsor commented on stencil-workspace/src/components/modus-table/modus-table.scss
> +        padding-bottom: 0.125rem;
when i ran `npm run lint` it corrected this and ordered them alphabetically

2023-12-14 22:57 UTC, cjwinsor commented on stencil-workspace/src/components/modus-table/modus-table.scss
> +      height: 3rem;
We should probably be using the helper variables here instead of hardcoding
```scss
$rem-2px: 0.125rem;
$rem-24px: 1.5rem;
$rem-32px: 2rem;
$rem-48px: 3rem;
```

2023-12-14 22:57 UTC, cjwinsor commented on stencil-workspace/src/components/modus-table/modus-table.scss
> +      height: 3rem;
this applies to each place these are referenced.  I don't think we have to go so far to make this a variable in the global file at this time

2023-12-14 22:57 UTC, cjwinsor commented on stencil-workspace/src/components/modus-table/modus-table.scss
Taking a look at these with checkboxes... it looks like if you applied compact's padding around the checkbox in comfortable then it would better align with the row height... which suggests you could reduce some for compacts as well.  Not sure the modus decision on this.  

The header height for compact and comfortable are the same, while relaxed is bigger.

The header height with sorting is one pixel more than without, but probably an issue prior to your change so not as big of an issue.

![image](https://github.com/trimble-oss/modus-web-components/assets/1130129/4bba5413-cd22-4b1c-85aa-57d6444f0e2e)

2023-12-14 22:57 UTC, cjwinsor commented on stencil-workspace/src/components/modus-table/modus-table.scss
This was my test script
```html
    <h3>Compact</h3>
    <div style="display:flex; gap:1rem">
      <modus-table density="compact" sort="true" full-width="true"></modus-table>
      <modus-table density="compact" sort="false" full-width="true"></modus-table>
      <modus-table density="compact" sort="false" full-width="true" row-selection="true"></modus-table>
    </div>
    <h3>Comfortable</h3>
    <div style="display:flex; gap:1rem; margin-top:1rem;">
      <modus-table density="comfortable" sort="true" full-width="true"></modus-table>
      <modus-table density="comfortable" sort="false" full-width="true"></modus-table>
      <modus-table density="comfortable" sort="false" full-width="true" row-selection="true"></modus-table>
    </div>
    <h3>Relaxed</h3>
    <div style="display:flex; gap:1rem; margin-top:1rem;">
      <modus-table density="relaxed" sort="true" full-width="true"></modus-table>
      <modus-table density="relaxed" sort="false" full-width="true"></modus-table>
      <modus-table density="relaxed" sort="false" full-width="true" row-selection="true"></modus-table>
    </div>
      <script>
        const columns = [
          {
            header: 'First Name',
            accessorKey: 'firstName',
            id: 'first-name',
            dataType: 'text',
            size: 150,
            minSize: 80,
            footer: 'Total',
          },
        ];
        const data = [
          {
            firstName: 'Fred',
          },
          {
            firstName: 'Bugs',
          },
          {
            firstName: 'Daffy',
          },
          {
            firstName: 'Tom',
          },
          {
            firstName: 'Daffy',
          },
        ];
        
        document.querySelectorAll('modus-table').forEach((table) => {
          table.columns = columns;
          table.data = data;
        });
    </script>
```

2023-12-15 16:32 UTC, yohernandez commented on stencil-workspace/src/components/modus-table/modus-table.scss
Added the compact's padding in comfortable.
The table header must be the same for all density options. Updated the CSS to override the height for body rows only. 

![image](https://github.com/trimble-oss/modus-web-components/assets/48927186/bebd38cf-63f7-45e0-8921-64e641c280d9)

The table row heights should be the same with and without the checkbox column for relaxed and comfortable. The case of compact is different because the table component uses the regular size version of the checkbox which is $rem-24px. UX wants a 2px padding top and bottom.

2023-12-15 16:38 UTC, yohernandez commented on stencil-workspace/src/components/modus-table/modus-table.scss
Also, we plan to allow users to select the checkbox size. This will allow us to use the small version for compact.

2023-12-15 22:19 UTC, cjwinsor approved these changes

2023-12-15 22:20 UTC, merged