Add tabindex on help icon and Sign out, handle enter key event on Sign out
trimble-oss/modus-web-components pull request #1953
Opened 2023-12-13 13:05 UTC by hsoni177

## Description

- Add the tabindex on the help icon
- Handle enter key event on Signout.

References #1945

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

2023-12-14 23:41 UTC, cjwinsor requested changes

2023-12-14 23:41 UTC, cjwinsor commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +  signOutClickHandler(event: MouseEvent | KeyboardEvent): void {
This is `KeyboardEvent | MouseEvent` everywhere else in the file, can you switch these around?  This is my only change request.

2023-12-15 05:53 UTC, hsoni177 commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +  signOutClickHandler(event: MouseEvent | KeyboardEvent): void {
> This is `KeyboardEvent | MouseEvent` everywhere else in the file, can you switch these around? This is my only change request.

@cjwinsor Updated the code please verify it.

2023-12-15 13:38 UTC, cjwinsor approved these changes

2023-12-15 13:38 UTC, merged