Add Slot in user profile menu for custom content
trimble-oss/modus-web-components pull request #1954
Opened 2023-12-13 16:41 UTC by Sanket8793

## Description

Add slot area to User Profile Menu

References #1269 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] Documentation update

## How Has This Been Tested?

we have to enable user context and then render the html you want to show using slot userCustomContext

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules
- [X] I have checked my code and corrected any misspellings

2023-12-14 23:35 UTC, cjwinsor requested changes

2023-12-14 23:35 UTC, cjwinsor commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +                    >
When i ran `npm run lint` it corrected this to 
```
                      variant={this.variant}>
                      {this.enableUserContent && <slot name={this.SLOT_USERCUSTOMCONTENT}></slot>}
```

2023-12-14 23:35 UTC, cjwinsor commented on stencil-workspace/src/components/modus-navbar/modus-navbar.e2e.ts
> +
When i ran `npm run lint` it found 4 issues in the test file and fixed them.  Lines 403, 420, 422, and 438 all have an extra space character.

2023-12-14 23:35 UTC, cjwinsor commented on stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar.stories.tsx
> +    <div slot="userCustomContent">Render your own custom content.</div>
This doesn't actually show up in the example, and i think in this case it should.

2023-12-14 23:35 UTC, cjwinsor commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +  @Prop() enableUserContent: boolean;
Do we need a property for this? It seems like if they don't provide the slot, it doesn't produce any side affects.  If we need to have the property for some reason, lets discuss the property name.

2023-12-15 10:38 UTC, Sanket8793 commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +  @Prop() enableUserContent: boolean;
@cjwinsor I've used this property as a flag to hide and show the slot in the profile menu, but I'll remove this if it's not necessary. Want your opinion on this

2023-12-15 14:04 UTC, cjwinsor commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +  @Prop() enableUserContent: boolean;
@Sanket8793 I think we can remove the property. It will function the same as the slot for notifications.  We can always add it in the future if there is a strong need, harder to remove it when there wasn't any need. The extra elements aren't that costly and we benefit from a simpler implementation and usage.

2023-12-15 15:08 UTC, cjwinsor commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +  readonly SLOT_USERCUSTOMCONTENT = 'userCustomContent';
can we instead name this `SLOT_PROFILE_MENU` and have the value be `profileMenu`

2023-12-15 16:40 UTC, Sanket8793 commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +  readonly SLOT_USERCUSTOMCONTENT = 'userCustomContent';
Yes I updated the name

2023-12-15 17:09 UTC, cjwinsor approved these changes

2023-12-15 17:09 UTC, merged