autocomplete - feat: disable close onselect
trimble-oss/modus-web-components pull request #1972
Opened 2023-12-20 18:26 UTC by rjavier-trimbler

## Description

References #1947 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

2023-12-27 18:41 UTC, yohernandez commented on angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts
> +  inputs: ['ariaLabel', 'checked', 'disabled', 'indeterminate', 'label', 'size', 'stopPropagation', 'tabIndexValue'],
These changes are not related to your ticket. Probably, they were missing in a previous PR. Could you remove them, please?

2023-12-27 18:41 UTC, yohernandez commented on angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts
> +  inputs: ['ariaLabel', 'checked', 'disabled', 'indeterminate', 'label', 'size', 'stopPropagation', 'tabIndexValue'],
Same here

2023-12-27 18:41 UTC, yohernandez commented on angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts
> +  profileMenuSignOutClick: EventEmitter<CustomEvent<KeyboardEvent | MouseEvent>>;
Same here

2023-12-27 18:41 UTC, yohernandez commented on angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts
> +  inputs: ['ariaLabel', 'checked', 'disabled', 'label', 'size']
Same here

2023-12-27 18:42 UTC, yohernandez commented on angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts
> +  inputs: ['ariaLabel', 'checked', 'disabled', 'label', 'size'],
Same here

2023-12-27 18:43 UTC, yohernandez commented on stencil-workspace/src/components/modus-radio-group/readme.md
> +| `size`         | `size`       | (optional) The size of the radiobutton. | `"medium" \| "small"` | `'medium'`  |
These changes are not related to your ticket. Probably, they were missing in a previous PR. Could you remove them, please?

2023-12-27 19:09 UTC, rjavier-trimbler commented on angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts
> +  inputs: ['ariaLabel', 'checked', 'disabled', 'indeterminate', 'label', 'size', 'stopPropagation', 'tabIndexValue'],
done

2023-12-27 19:09 UTC, rjavier-trimbler commented on angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts
> +  inputs: ['ariaLabel', 'checked', 'disabled', 'indeterminate', 'label', 'size', 'stopPropagation', 'tabIndexValue'],
done

2023-12-27 19:09 UTC, rjavier-trimbler commented on angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts
> +  profileMenuSignOutClick: EventEmitter<CustomEvent<KeyboardEvent | MouseEvent>>;
done

2023-12-27 19:09 UTC, rjavier-trimbler commented on angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts
> +  inputs: ['ariaLabel', 'checked', 'disabled', 'label', 'size']
done

2023-12-27 19:09 UTC, rjavier-trimbler commented on stencil-workspace/src/components/modus-radio-group/readme.md
> +| `size`         | `size`       | (optional) The size of the radiobutton. | `"medium" \| "small"` | `'medium'`  |
done

2023-12-27 19:09 UTC, rjavier-trimbler commented on angular-workspace/projects/trimble-oss/modus-angular-components/src/lib/stencil-generated/components.ts
> +  inputs: ['ariaLabel', 'checked', 'disabled', 'label', 'size'],
done

2024-01-04 23:30 UTC, cjwinsor requested changes
I wasn't able to complete my review today, but I will submit what I have so far.

2024-01-04 23:30 UTC, cjwinsor commented on stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
> +        onFocusin={() => {
This should be moved to a function instead of inline logic

2024-01-04 23:30 UTC, cjwinsor commented on stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
> +    this.value = optionValue;
Can you explain the purpose of these changes?

2024-01-04 23:30 UTC, cjwinsor commented on stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.scss
> +      &#selected,
should be a class name, not an id

2024-01-04 23:30 UTC, cjwinsor commented on stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
> +    const slotted = this.el.children;
This logic was in `updateVisibleCustomOptions` before and could still make sense there. Did you move it out because it was affecting the other calls to this function?

2024-01-08 20:04 UTC, rjavier-trimbler commented on stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
> +      this.clearable = true;
done! I've removed the 'isSelected' highlight

2024-01-08 20:05 UTC, rjavier-trimbler commented on stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
> +  isSelected?: boolean;
yes, but I've removed, there's another issue for this already

2024-01-08 20:21 UTC, rjavier-trimbler commented on stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
> +        if (this.disableCloseOnSelect) {
done!

2024-01-08 20:21 UTC, rjavier-trimbler commented on stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
> +      onFocus={() => {
done!

2024-01-08 20:21 UTC, rjavier-trimbler commented on stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
> +        onFocusin={() => {
done!

2024-01-08 20:21 UTC, rjavier-trimbler commented on stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.scss
> +      &#selected,
I've removed this because another issue about options highlighted

2024-01-08 20:21 UTC, rjavier-trimbler commented on stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
> +                      id: `${option.isSelected ? 'selected' : ''}`,
I've removed this because another issue about options highlighted

2024-01-08 21:11 UTC, rjavier-trimbler commented on stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
> +  handleFilterOptions = (search: string) => {
This issue has been solved in this PR (about the @ watch  for the value)

https://github.com/trimble-oss/modus-web-components/pull/1993

2024-01-10 13:13 UTC, rjavier-trimbler commented on stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
> +    const slotted = this.el.children;
I think it makes more sense in the componentDidLoad function, if we rely on single responsibility this line should not be within a function whose responsibility is to update the visible customizable options, this line refers more to know if it is customizable or not and this is something that can be known during the life cycle.

2024-01-10 14:08 UTC, rjavier-trimbler commented on stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
> +    this.value = optionValue;
sure, there's some validations I added inside handleSearchChange to be able to display the options always and for that I have to be aware if its a custom autocomplete  and  if there's no disableCloseOnSelect to update the visibleoptions otherwise I would want to ignore it. (why? well if I always showing all the options at the begining I dont have to update the options again if that control is set to true and I have to always shows them)

2024-01-11 04:30 UTC, cjwinsor commented on stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
> +      this.clearable = true;
I don't want the `this.clearable` to be enabled like this.  If the consumer wants to have the clear option present, the will need to set `clearable=true` on the autocomplete component themselves.

2024-01-11 04:31 UTC, cjwinsor requested changes
Aside from removing this this.clearable addition I did notice a bug from our last PR.  Can you update `updateVisibleCustomOptions` and `updateVisibleOptions` to have the line of 

```js
search = search || '';
```
somewhere before `search.length` is called.  When the clear button is clicked, it sends a null value and not undefined like we saw in other places.  This should be a good enough patch for now.

2024-01-11 05:00 UTC, rjavier-trimbler commented on stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
> +      this.clearable = true;
fair enough, `clearable=true` has been removed!

2024-01-11 15:36 UTC, cjwinsor approved these changes

2024-01-11 15:37 UTC, merged