Add default sort to Table component
trimble-oss/modus-web-components pull request #1980
Opened 2023-12-22 11:17 UTC by leosole-trimble

## Description

Expose a property to set a default column to be used to sort the data

References #1975 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

In storybook

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

2023-12-22 13:46 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-table/modus-table.tsx
> +    console.log(newVal);
Please remove console logs

2023-12-22 13:50 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-table/modus-table.tsx
> +  @Prop() defaultSort: ColumnSort;
We need a new type created from `ColumnSort`, it could be named as `ModusTableColumnSort`. Example, `export type ModusTableSortingState = SortingState;` 
And it must be exported in `stencil-workspace\src\components\modus-table\models\modus-table.models.ts`

2023-12-22 13:51 UTC, msankaran0712 commented on stencil-workspace/storybook/stories/components/modus-table/modus-table-storybook-docs.mdx
> +- A default sorting can be set by setting `defaultSort` with the column `id` and sorting direction.
Once the `ModusTableColumnSort` is added, it should be added in the documentation under interfaces section

2023-12-22 13:54 UTC, msankaran0712 commented on stencil-workspace/storybook/stories/components/modus-table/modus-table.stories.tsx
> +  ${initializeTable(columns, data, pageSizeList, toolbarOptions, displayOptions, rowSelectionOptions, rowActions, manualPaginationOptions, manualSortingOptions, defaultSort)}
The number of arguments passed here has increased drastically. Would you be able to create an object type so that there is only one argument to be passed?

2023-12-22 14:03 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-table/modus-table.tsx
> +    this.tableCore?.setState('sorting', [newVal]);
I think the `defaultSort` is overriding the manual sorting state when it is changed. I was able to see it happening on Storybook @leosole-trimble. Please set the state only when manual sorting is not enabled.

2024-01-03 16:12 UTC, rthanga1 approved these changes

2024-01-03 23:05 UTC, cjwinsor requested changes
Only found one thing missing, the rest seems good.  Once we add the property to the `Properties` section of the storybook we should be good to merge.

2024-01-04 12:29 UTC, leosole-trimble commented
@cjwinsor @rthanga1 if everything is ok, could one of you guys merge this for me?

2024-01-04 14:44 UTC, cjwinsor approved these changes

2024-01-04 14:45 UTC, merged