Modus Table: Add checkboxSize to rowSelectionOption
trimble-oss/modus-web-components pull request #1981
Opened 2023-12-22 19:13 UTC by yohernandez

## Description

Adding a new property to rowSelectionOptions to handle checkbox size.
Fixing also https://github.com/trimble-oss/modus-web-components/issues/1969

References #1964

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

Added e2e test to check if a small checkbox is rendered.

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [X] I have checked my code and corrected any misspellings

2023-12-27 18:18 UTC, yohernandez commented on stencil-workspace/src/components/modus-table/models/modus-table.models.ts
> +  checkboxSize: 'small' | 'medium';
Adding a new property to control the checkbox's size.

2023-12-27 18:20 UTC, yohernandez commented on stencil-workspace/src/components/modus-table/modus-table.e2e.ts
> +  it('Renders small size checkboxes', async () => {
This test is checking that the checkbox's size is small when the `checkboxSize` property is set to 'small'

2023-12-27 18:22 UTC, yohernandez commented on stencil-workspace/src/components/modus-table/modus-table.scss
> +      &.small {
set the column width to 38px when the checkbox's size is small

2023-12-27 18:23 UTC, yohernandez commented on stencil-workspace/src/components/modus-table/modus-table.scss
> +    tfoot {
this is fixing https://github.com/trimble-oss/modus-web-components/issues/1969

2023-12-27 18:23 UTC, yohernandez commented on stencil-workspace/src/components/modus-table/modus-table.scss
> +    tbody,
this is fixing https://github.com/trimble-oss/modus-web-components/issues/1969

2023-12-27 18:24 UTC, yohernandez commented on stencil-workspace/src/components/modus-table/modus-table.tsx
> +    checkboxSize: 'medium',
setting default value to medium

2023-12-27 18:24 UTC, yohernandez commented on stencil-workspace/src/components/modus-table/modus-table.tsx
> +      newVal.checkboxSize !== oldVal.checkboxSize
react to a change on the new property

2023-12-27 18:25 UTC, yohernandez commented on stencil-workspace/src/components/modus-table/parts/modus-table-body.tsx
> +                checkboxSize={checkboxSize}></ModusTableCellCheckbox>
propagate the checkboxSize property to ModusTableCellCheckbox component

2023-12-27 18:27 UTC, yohernandez commented on stencil-workspace/src/components/modus-table/parts/modus-table-footer.tsx
> +              class={COLUMN_DEF_ROW_SELECTION_CSS + ' ' + (rowSelectionOptions?.checkboxSize ?? '')}></td>
adding the classes small or medium to the table td for the footer.

2023-12-27 18:28 UTC, yohernandez commented on stencil-workspace/src/components/modus-table/parts/row/selection/modus-table-cell-checkbox.tsx
> +      class={'row-checkbox sticky-left ' + (checkboxSize ?? '')}
adding the classes small or medium to the table td for the body.

2023-12-27 18:28 UTC, yohernandez commented on stencil-workspace/src/components/modus-table/parts/row/selection/modus-table-cell-checkbox.tsx
> +        size={checkboxSize}
set checkbox size property

2023-12-27 18:29 UTC, yohernandez commented on stencil-workspace/src/components/modus-table/parts/row/selection/modus-table-header-checkbox.tsx
> +          size={rowSelectionOptions?.checkboxSize}
set the checkbox size property in the header

2023-12-27 18:29 UTC, yohernandez commented on stencil-workspace/src/components/modus-table/parts/row/selection/modus-table-header-checkbox.tsx
> +    <th class={'row-checkbox sticky-left ' + (rowSelectionOptions?.checkboxSize ?? '')}>
adding the classes small or medium to the table td for the header.

2023-12-27 18:30 UTC, yohernandez commented on stencil-workspace/storybook/stories/components/modus-table/modus-table-storybook-docs.mdx
> +  - To use a different size for the checkboxes, set `checkboxSize` to `small`. Default: `medium`.
updating Storybook

2024-01-03 15:28 UTC, rthanga1 commented
We have to apply the same fix to the header row as well.

2024-01-03 23:24 UTC, cjwinsor requested changes
@yohernandez Can we discuss the need for the checkbox to switch to the small size?

2024-01-03 23:24 UTC, cjwinsor commented on stencil-workspace/src/components/modus-table/modus-table.scss
> +    tfoot {
@yohernandez After discussing with Modus team, we don't see any reason why the header shouldn't honor the density settings. If you want to include that issue fix in this PR, you'll need to address the header.  Feel free to point me to your UX if there is a disagreement.

2024-01-03 23:24 UTC, cjwinsor commented on stencil-workspace/src/components/modus-table/models/modus-table.models.ts
> +  checkboxSize: 'small' | 'medium';
@yohernandez I am going to ask a few resources, but the general thought so far with Modus is that the user shouldn't have control of the textbox size.  If we are to make it a standard that we use the small checkbox for the compact density, then that shouldn't be configurable.  Can you ping me so we can discuss?

2024-01-03 23:24 UTC, cjwinsor commented on stencil-workspace/src/components/modus-table/parts/row/selection/modus-table-header-checkbox.tsx
> +          size={rowSelectionOptions?.checkboxSize}
This is also why the header density came up, as the small checkbox looks out of place with the standard header size.

2024-01-04 16:03 UTC, yohernandez commented on stencil-workspace/src/components/modus-table/modus-table.scss
> +    tfoot {
We had a first design where the density affects the body and footer only. We are double-checking. In the mean time, we'll pull out this change from this PR. Thanks.

2024-01-04 16:06 UTC, yohernandez commented
@cjwinsor We'll go with your suggestion: "we use the small checkbox for the compact density". We'll update this PR properly.

2024-01-05 16:56 UTC, yohernandez commented on stencil-workspace/src/components/modus-table/modus-table.e2e.ts
> +  it('Renders small size checkboxes for compact density', async () => {
This test changes the table density to compact and verifies that the checkbox's size is small.

2024-01-05 16:57 UTC, yohernandez commented on stencil-workspace/src/components/modus-table/parts/modus-table-body.tsx
> +  if(density === 'compact') {
change the checkbox's size to small for compact density

2024-01-05 16:58 UTC, yohernandez commented on stencil-workspace/storybook/stories/components/modus-table/modus-table-storybook-docs.mdx
> +  preSelectedRows?: string[];
Noticed that this property was missed in a previous PR

2024-01-05 16:58 UTC, yohernandez commented on stencil-workspace/src/components/modus-table/parts/row/selection/modus-table-header-checkbox.tsx
> +  let checkboxSize: 'medium' | 'small' = 'medium';
Same for the header.

2024-01-05 17:00 UTC, yohernandez commented
@cjwinsor The PR is ready for review. The property checkboxSize was removed. The checkbox size will change to small for compact density. The footer changes were removed too.

2024-01-17 16:17 UTC, dnarey commented
@cjwinsor Resolved conflicts with modus-table.e2e.tx.  PR is ready for review.

2024-01-17 18:45 UTC, cjwinsor approved these changes

2024-01-17 21:15 UTC, merged