Update activePage default value
trimble-oss/modus-web-components pull request #2053
Opened 2024-01-22 09:48 UTC by ElishaSamPeterPrabhu

## Description

References #

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

2024-01-23 09:38 UTC, rthanga1 commented
@ElishaSamPeterPrabhu This works if we leave the active page like this
`    <modus-pagination
    max-page="32"
    min-page="1"
    size="medium"></modus-pagination>
`
But if the user passes a invalid or undefined active page, the issue still occurs. Like this
`    <modus-pagination
    active-page
    max-page="32"
    min-page="1"
    size="medium"></modus-pagination>
`

Try opening this link 
https://deploy-preview-2053--moduswebcomponents.netlify.app/?path=/story/components-pagination--default&args=activePage:

**Possible fix:**
Along with the current fix, if the active page is not a valid value, then set it to '1'.

2024-01-23 09:38 UTC, rthanga1 requested changes
Try opening this link
https://deploy-preview-2053--moduswebcomponents.netlify.app/?path=/story/components-pagination--default&args=activePage:

**Possible fix:**
Along with the current fix, if the active page is not a valid value, then set it to '1'.

2024-01-24 06:24 UTC, rthanga1 approved these changes

2024-01-24 08:35 UTC, yshnaviganapathi commented
@ElishaSamPeterPrabhu , Pr is good to merge.

2024-01-24 08:57 UTC, merged