Change border radius from 2px to 4px for components
trimble-oss/modus-web-components pull request #2065
Opened 2024-01-25 08:35 UTC by coliff

## Description

Change border radius from 2px to 4px for components

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

Locally with Edge v120 on Windows 11

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

2024-01-25 13:55 UTC, rthanga1 approved these changes

2024-01-25 14:02 UTC, rthanga1 submitted a review, later dismissed

2024-01-30 15:25 UTC, cjwinsor approved these changes

2024-01-30 15:28 UTC, cjwinsor requested changes

2024-01-30 15:28 UTC, cjwinsor commented on stencil-workspace/src/components/modus-file-dropzone/modus-file-dropzone.scss
> +    border: $rem-2px dashed $modus-file-upload-dropzone-border-color;
@coliff this is border thickness, not radius

2024-01-30 15:42 UTC, coliff commented on stencil-workspace/src/components/modus-file-dropzone/modus-file-dropzone.scss
> +    border: $rem-2px dashed $modus-file-upload-dropzone-border-color;
yep. the change was intentional (though I realize I should have mentioned that!). It should be 2px as per the Figma.
https://www.figma.com/file/wyfVJUHWRMkeCfdB38HFEE/Modus---Web?node-id=27038%3A16143&mode=dev
![image](https://github.com/trimble-oss/modus-web-components/assets/1212885/420a1536-3f6c-4403-b2b8-33c4daae03f1)

2024-01-30 20:59 UTC, cjwinsor approved these changes

2024-01-30 20:59 UTC, merged