EPD-11997 Autocomplete: Hitting Space should also select a focused option as well as hitting Enter
trimble-oss/modus-web-components pull request #2067
Opened 2024-01-25 15:37 UTC by yevhenkravets

## Description

Space/ Enter Key: Selects the option from the dropdown and adds the text to the textbox.
This is a part of the approved Modus submission: https://modus.ideas.aha.io/ideas/MOD-I-14

Also added accessibility attributes following these specifications:
https://w3c.github.io/aria/#combobox
https://w3c.github.io/aria/#aria-autocomplete
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/combobox_role

References #2066

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

Added relevant integration tests and it will be tested also by the e-builder QA through the storybook.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

2024-01-25 15:41 UTC, yevhenkravets commented on stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
> +      aria-expanded={this.displayOptions()}
Added accessibility attributes following specifications I added in the description.

2024-01-25 15:41 UTC, yevhenkravets commented on stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
> +    if (!allowedKeys.includes(event.key)) {
Hitting Space also selects an option now.

2024-01-29 04:54 UTC, rthanga1 commented
@yevhenkravets Can you explain what this PR does? 
1. I opened up the auto complete component in the storybook
2. Used tab to focus the component
3. And tried using 'Space' and 'Enter' key which doesn't seem to do anything

My understanding is, when the 'Enter' key is pressed, it should open up the options, right?

2024-01-29 04:54 UTC, rthanga1 commented on stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
> +  private listId = `autocomplete-${Math.random().toString().slice(2, 7)}`;
Can you explain what this does?

2024-01-29 12:41 UTC, yevhenkravets commented
> @yevhenkravets Can you explain what this PR does?
> 
> 1. I opened up the auto complete component in the storybook
> 2. Used tab to focus the component
> 3. And tried using 'Space' and 'Enter' key which doesn't seem to do anything
> 
> My understanding is, when the 'Enter' key is pressed, it should open up the options, right?

No, the expectation here is when you go through the list of options and press Enter/Space then the currently focused option gets selected.

2024-01-29 12:46 UTC, yevhenkravets commented on stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
> +  private listId = `autocomplete-${Math.random().toString().slice(2, 7)}`;
It generates a dynamic ID for the list element. It's not static to be able to use multiple autocomplete components on the page and every list element has a unique ID.
But, the main reason why we need the ID is for accessibility specifications. We use it in aria-controls attribute here https://github.com/trimble-oss/modus-web-components/pull/2067/files#diff-fd75ee2b4254f5561ecb52008b06050dc5ce305354677d36d07caed91e29be61R271
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-controls

2024-01-29 23:11 UTC, cjwinsor requested changes

2024-01-29 23:11 UTC, cjwinsor commented on stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
> +  private listId = `autocomplete-${Math.random().toString().slice(2, 7)}`;
@yevhenkravets This doesn't work as it doesn't guarantee uniqueness.  

You'll need to create a utility function for generating IDs.  My suggestions are 

- create IDs with the prefix of `mwc_id_` following by the next value
- start at 0
- import utility function into component to create the ID
- test for utility function

This will have a lot of value as we start doing accessibility work.  

Take this generated id and append `_list` after it to further clarify. 

We do have a `createGuid()` utility as well.. but that will create very verbose IDs and ideally for our purposes a count is all that is required as we don't' have or need persistence.

2024-01-30 14:56 UTC, yevhenkravets commented on stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
> +  private listId = `autocomplete-${Math.random().toString().slice(2, 7)}`;
@cjwinsor Updated the code as you suggested.
<img width="520" alt="Screenshot 2024-01-30 at 16 47 53" src="https://github.com/trimble-oss/modus-web-components/assets/35339097/c9de50ee-4c03-4616-bd42-92a419102100">

2024-01-30 22:01 UTC, cjwinsor approved these changes

2024-01-30 22:02 UTC, merged