Issue 2081 Allow user to scroll through items in the dropdown
trimble-oss/modus-web-components pull request #2087
Opened 2024-01-29 18:49 UTC by mltejada

## Description

References #

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

2024-01-30 22:25 UTC, cjwinsor requested changes
There is an issue when mixing tabs and arrow keys due to tabbing not updating the focus index.   For the example of Apples, Banana, Orange: 

- Type a then tab 3 times to highlight Orange
- Press the down arrow once
- Banana gets highlighted since the focus index incremented from 0 to 1

2024-01-30 22:25 UTC, cjwinsor commented on stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
> +      >
This formatting would be changed when `npm run lint` is run.  Can you run that command and ensure all lint formatting is standardized?   It'll move the `>` back to the end of the line.

2024-01-30 22:25 UTC, cjwinsor commented on stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
> +                    role="option"
I think this was just added in another PR which may be one of the sources of conflict with the main branch.  Try bringing in main to resolve.

2024-01-30 22:25 UTC, cjwinsor commented on stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
> +    if (!this.hasFocus || event.defaultPrevented || event.altKey) {
I'm curious the use case for the `alt` key here.  What is the scenario being avoided?

2024-01-31 16:22 UTC, mltejada commented on stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
> +      >
Done. I'll have to check my settings as every time I save it auto formats to this.

2024-01-31 18:47 UTC, mltejada commented on stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
> +    if (!this.hasFocus || event.defaultPrevented || event.altKey) {
I forgot to remove this. Validated is not needed .

2024-01-31 21:40 UTC, cjwinsor commented
@mltejada We still need to support Tabs in addition to Up an Down.

2024-01-31 21:44 UTC, mltejada commented
> @mltejada We still need to support Tabs in addition to Up and Down.

I meet with Carlos and confirmed this is the expected behavior from https://modus.ideas.aha.io/ideas/MOD-I-14

Note: We have another story to support tab on the "X" icon but tab won't be used for the dropdown options.

2024-01-31 22:30 UTC, cjwinsor commented
> > @mltejada We still need to support Tabs in addition to Up and Down.
> 
> I meet with Carlos and confirmed this is the expected behavior from https://modus.ideas.aha.io/ideas/MOD-I-14
> 
> The tab will move focus to the next component, but will not scroll down or up through the options.
> 
> Note: We have another story to support tab on the "X" icon (currently not working).

Let me check with the team.  Upon review of at least two other component library I see it functioning as you describe.  The modus submission did not make clear that tabbing through the items would be removed (In the approved writeup).

2024-02-01 21:00 UTC, mltejada commented
> Let me check with the team. Upon review of at least two other component library I see it functioning as you describe. The modus submission did not make clear that tabbing through the items would be removed (In the approved writeup).

Thanks Chris. Let me know. I didn't originally work on the tab because we have another story for it, but since it was conflicting then I confirmed the behavior with Carlos. 
Note: I added tests for the custom options scenario.

2024-02-02 22:12 UTC, cjwinsor requested changes

2024-02-02 22:12 UTC, cjwinsor commented on stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.e2e.ts
> +    expect(optionSelected).toHaveReceivedEventDetail("1");
@mltejada Use single quotes

2024-02-02 22:12 UTC, cjwinsor commented on stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.e2e.ts
> +    expect(optionSelected).toHaveReceivedEventDetail("2");
@mltejada Use single quotes

2024-02-02 22:12 UTC, cjwinsor commented on stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.e2e.ts
> +    expect(optionSelected).toHaveReceivedEventDetail("1");
@mltejada Use single quotes

2024-02-02 22:26 UTC, mltejada commented on stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.e2e.ts
> +    expect(optionSelected).toHaveReceivedEventDetail("1");
Updated

2024-02-02 22:26 UTC, mltejada commented on stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.e2e.ts
> +    expect(optionSelected).toHaveReceivedEventDetail("2");
Updated

2024-02-02 22:26 UTC, mltejada commented on stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.e2e.ts
> +    expect(optionSelected).toHaveReceivedEventDetail("1");
Updated

2024-02-02 22:28 UTC, cjwinsor approved these changes

2024-02-02 22:28 UTC, merged