Changes in Sentiment-scale accessibility issues
trimble-oss/modus-web-components pull request #2121
Opened 2024-02-06 10:06 UTC by HarieshPugazhendhi

## Description

So in the sentiment-scale component made a customizable aria-label for the smileys and thumbs-up tag. And added a aria-label control in stories, so that user can give their own custom description for the component. And added the testcases for the smiley in testing file(modus-sentiment-scale.spec.ts).

References #
#1976 
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

In the Sentiment-scale component added a control option for aria-label in stories and typed a custom label in it. And inspected it in the browser's built-in Developer Tools. So to check whether the label I have typed have passed to the component and received it to place it in the right property. 

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] My changes generate no new warnings
- [ ] New and existing unit tests pass locally with my changes
- [ ] I have checked my code and corrected any misspellings

2024-02-07 10:08 UTC, ElishaSamPeterPrabhu submitted a review, later dismissed

2024-02-07 10:55 UTC, coliff commented
Good PR - thanks! There is a remaining issue with the Storybook canvas page:

- The buttons here (https://modus-web-components.trimble.com/?path=/docs/user-inputs-select--default) are disabled. We need to remove `disabled="false"` from `modus-sentiment-scale`.
![image](https://github.com/trimble-oss/modus-web-components/assets/1212885/cd07f888-467b-419e-ba5b-2344db192962)

- Not a problem, but the `aria-disabled="false"` which is on by default is unnecessary. Can it be removed? ``aria-disabled="true"`` should be set when it's disabled, but if it's not disabled then `aria-disabled` attribute should removed altogether.

2024-02-08 01:49 UTC, cjwinsor requested changes

2024-02-08 01:49 UTC, cjwinsor commented on stencil-workspace/src/components/modus-sentiment-scale/modus-sentiment-scale.tsx
> +                <SentimentIconMap icon={iconName} size={`${this.type === 'thumbs' ? '32' : '24'}`} />
This should still use the constant `THUMB_SENTIMENT_TYPE` for maintainability.

2024-02-08 04:38 UTC, HarieshPugazhendhi commented on stencil-workspace/src/components/modus-sentiment-scale/modus-sentiment-scale.tsx
> +                <SentimentIconMap icon={iconName} size={`${this.type === 'thumbs' ? '32' : '24'}`} />
Modified the code to still use the constant for maintainability.

2024-02-08 15:11 UTC, cjwinsor commented
@HarieshPugazhendhi Just checking if you meant to push latest changes after that last comment or it was just a confirmation of approach.

2024-02-13 13:49 UTC, HarieshPugazhendhi commented
> Good PR - thanks! There is a remaining issue with the Storybook canvas page:
> 
> * The buttons here (https://modus-web-components.trimble.com/?path=/docs/user-inputs-select--default) are disabled. We need to remove `disabled="false"` from `modus-sentiment-scale`. This is important because `disabled="false"` actually just means disabled (i.e. it's the same as `disabled="true"`!)
>   ![image](https://private-user-images.githubusercontent.com/1212885/302952743-cd07f888-467b-419e-ba5b-2344db192962.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc4MTQ1NDQsIm5iZiI6MTcwNzgxNDI0NCwicGF0aCI6Ii8xMjEyODg1LzMwMjk1Mjc0My1jZDA3Zjg4OC00NjdiLTQxOWUtYmE1Yi0yMzQ0ZGIxOTI5NjIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTNUMDg1MDQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9M2ZjYzVhZGY0Y2VmOTAxODBlYjMxY2FhZGFiZTQxMzVjZWY2ODFiODgyNjQwN2RiYzBlNjBmNTc1YTUxYzNmNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.GorYLn9zAnUgpoDvqKCAmzXUWWQR90OCVm6qX4q67Tc)
> * Not a problem, but the `aria-disabled="false"` which is on by default is unnecessary. Can it be removed? `aria-disabled="true"` should be set when it's disabled, but if it's not disabled then `aria-disabled` attribute should removed altogether.

Hey Coliff,
                The changes that you mentioned to remove disabled="false" from modus-sentiment-scale is complicated. Removing this parameter will affect the component's toggle functionality. Furthermore, other parameters rely on the disabled attribute, making its presence important. So what else could be done either?

2024-02-14 12:37 UTC, coliff approved these changes
The Canvas demo has accessibility issues (it's ALWAYS announced as disabled - even is disabled if set as False)... but the main functionality on Docs tab is working good so I'll approve.

2024-02-15 04:49 UTC, cjwinsor commented on stencil-workspace/storybook/stories/components/modus-sentiment-scale/modus-sentiment-scale.stories.tsx
> +<modus-sentiment-scale  aria-label=${ariaLabel} type="${iconsType}" disabled="${disabled}"></modus-sentiment-scale>
@HarieshPugazhendhi I think you can update this to `?disabled=$"{disabled}"` to satisfy the need to only add the property when it's true.

Here is how attributes are handled in the html templating
https://lit.dev/docs/templates/expressions/#boolean-attribute-expressions

2024-02-15 19:26 UTC, cjwinsor approved these changes

2024-02-15 19:26 UTC, merged