Add keydown accessibility to navbar
trimble-oss/modus-web-components pull request #2139
Opened 2024-02-12 06:57 UTC by ElishaSamPeterPrabhu

## Description

- The addMenu is set via slot method and is part of the modus-dropdown. So the keydown features are added from modus-dropdown to navbar-button-lust to the modus-navbar
- Space and enter toggle the menu and escape hides it

References #
#1628 
## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

2024-02-13 16:32 UTC, cjwinsor requested changes

2024-02-14 06:09 UTC, ElishaSamPeterPrabhu commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +      }
Refactored

2024-02-14 06:09 UTC, ElishaSamPeterPrabhu commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +  buttonMenuKeydownHandler(event: KeyboardEvent, button: ModusNavbarButton) {
Renamed

2024-02-14 06:11 UTC, ElishaSamPeterPrabhu commented on stencil-workspace/src/components/modus-dropdown/modus-dropdown.tsx
> +  }
There is room for refactoring with the `hideDropdown()` but `showDropdown()` has different cases with the current logic, hence refactored with `hideDropdown()`.

2024-02-20 23:21 UTC, cjwinsor commented
@ElishaSamPeterPrabhu Can you add some tests around this functionality, to ensure the key handling is as we expect?

2024-02-21 11:48 UTC, ElishaSamPeterPrabhu commented
> @ElishaSamPeterPrabhu Can you add some tests around this functionality, to ensure the key handling is as we expect?

Added test cases for the added keyboard events

2024-02-27 04:08 UTC, cjwinsor commented
@ElishaSamPeterPrabhu Can you see if you can find a solution for closing the menus when you tab out of them.  Currently all the keyboard interactions you added are working, but if i open the menu with the keyboard, then tab through it and onto the next, i can open that one and the previous is not closed.

2024-02-27 06:59 UTC, ElishaSamPeterPrabhu commented
> @ElishaSamPeterPrabhu Can you see if you can find a solution for closing the menus when you tab out of them. Currently all the keyboard interactions you added are working, but if i open the menu with the keyboard, then tab through it and onto the next, i can open that one and the previous is not closed.
> 
> ![image](https://private-user-images.githubusercontent.com/1130129/308033529-ce0f2923-344d-4e3d-8acc-74cd48bd3d51.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMTU3OTksIm5iZiI6MTcwOTAxNTQ5OSwicGF0aCI6Ii8xMTMwMTI5LzMwODAzMzUyOS1jZTBmMjkyMy0zNDRkLTRlM2QtOGFjYy03NGNkNDhiZDNkNTEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjdUMDYzMTM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWU3NzY3MWQ4NmUyZTNiYjYyMWZkZTQ2YjBiNzM5ZGQxZjQ4ODI1M2Y3OGU5NzBkYzg4NWQ3ODQzODY1NWQzZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.P7cKixqSWCQW5S-pJ4lgmZ2C4i20pA8eIZx-rHBBjxw)

Fixed

2024-02-27 22:57 UTC, cjwinsor approved these changes

2024-02-27 22:58 UTC, merged