Add aria-label attribute to navbar
trimble-oss/modus-web-components pull request #2379
Opened 2024-03-30 03:11 UTC by austinoneil

## Description

Add `aria-label` attribute to navbar.

References #2212

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

e2e tests, inspect element on storybook

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

2024-04-01 10:51 UTC, coliff requested changes

2024-04-01 10:51 UTC, coliff commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +        <nav class={`${direction} ${shadow} ${variant}`} aria-label={this.ariaLabel}>
If no aria-label is set then it renders as `<nav class aria-label>` - however it shouldn't show aria-label at all if not specified. Can you fix that please? By default it shouldn't have an aria-label at all.

2024-04-01 19:27 UTC, austinoneil commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +        <nav class={`${direction} ${shadow} ${variant}`} aria-label={this.ariaLabel}>
I was not able to reproduce this locally.  When running locally, I got desired behavior.  I added some unit tests for these user journeys.

2024-04-02 08:33 UTC, coliff commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +        <nav class={`${direction} ${shadow} ${variant}`} aria-label={this.ariaLabel}>
![image](https://github.com/trimble-oss/modus-web-components/assets/1212885/e7cf8a3d-6f88-4555-a0bb-e796c8a6fa02)

Adding `aria-label` to the modus-navbar is problematic, I think it should be on the nav only.

2024-04-02 23:22 UTC, austinoneil commented
I changed the prop name to `navAriaLabel` and update documentation/tests.

2024-04-04 07:20 UTC, coliff commented
It's still rendering empty aria-label if no aria-label is specified but it shouldn't. See code here:

![image](https://github.com/trimble-oss/modus-web-components/assets/1212885/1ee3c3f1-7117-405a-9d96-6624b944c0b6)

2024-05-02 07:40 UTC, coliff commented
Hi @austinoneil - the outstanding issue on this has been resolved now with your merged PR (empty aria-label fix) so once the conflicts are resolved here we can merge too. thanks :-)

2024-05-05 12:26 UTC, coliff commented
doesn't seem to work:
https://deploy-preview-2379--moduswebcomponents.netlify.app/?path=/story/components-navbar--default&args=ariaLabel:default
This link should give the navbar an aria-label with default value but no value is given... its just rendered as `<nav class="" aria-label="">`

2024-05-07 01:01 UTC, austinoneil commented
@coliff fixed.

2024-05-10 06:46 UTC, coliff approved these changes

2024-05-10 06:46 UTC, merged