Tabs:Fix issue where selecting a tab in a set with no active tab errors out
trimble-oss/modus-web-components pull request #2383
Opened 2024-04-01 04:18 UTC by austinoneil

## Description

Fix issue where selecting a tab in a set with no active tab errors out.

References #2197

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

Added E2E test, manually tested using provided HTML (thank you, reporter)

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

2024-04-02 20:31 UTC, cjwinsor requested changes

2024-04-02 20:31 UTC, cjwinsor commented on stencil-workspace/src/components/modus-tabs/modus-tabs.tsx
> +    if (activeTab != undefined && activeTab.id) {
@austinoneil This can be simplified a bit further with
```js
if (activeTab?.id != null) {
    return;
}
```

We can leverage optional chaining and `!= null` for nullish coalescing.  If you can make this small change I will go ahead and merge afterwards.

2024-04-02 21:01 UTC, austinoneil commented on stencil-workspace/src/components/modus-tabs/modus-tabs.tsx
> +    if (activeTab != undefined && activeTab.id) {
This change was fixing an issue with an `if` statement that appeared to avoid emitting if the active tab was clicked.  This change breaks some tests.  That said, it looks like my change breaks some functionality.  I'll fix it and add a test and push.

2024-04-02 21:46 UTC, austinoneil commented on stencil-workspace/src/components/modus-tabs/modus-tabs.tsx
> +    if (activeTab != undefined && activeTab.id) {
Done, though adding a test proved to be difficult (it uses `spyOn` for event emitters, which seems to be causing test issues in `main` with other tests as well)

2024-04-05 00:57 UTC, cjwinsor commented on stencil-workspace/src/components/modus-tabs/modus-tabs.tsx
> +    if (activeTab != undefined && activeTab.id) {
@austinoneil Can you go more into detail about what you mean by "seems to be causing test issues in `main`"?

2024-04-05 01:07 UTC, austinoneil commented on stencil-workspace/src/components/modus-tabs/modus-tabs.tsx
> +    if (activeTab != undefined && activeTab.id) {
@cjwinsor When I run `npm run test` locally on main, I get the failures for the following tests:

* [`modus-select emits "valueChange" event`](https://github.com/trimble-oss/modus-web-components/blob/main/stencil-workspace/src/components/modus-select/modus-select.e2e.ts#L149)
* [`modus-table Display items per page list when pageSizeList is enabled`](https://github.com/trimble-oss/modus-web-components/blob/main/stencil-workspace/src/components/modus-table/modus-table.e2e.ts#L190)

Both are related to using the `spyOn` method and both are failing on my machine on `main`.  I do not know whether this is an issue with my setup or if it's failing across the board.  I am running `nvm use 18.17.0` when opening my IDE.

2024-04-25 01:13 UTC, cjwinsor commented
@austinoneil Very peculiar, I switched to 18.17.0 and ran tests against main without issue on my windows laptop.  I'm going to keep my eye on this and get I get a chance try to run within a sandbox and wsl.

2024-04-25 01:13 UTC, cjwinsor approved these changes

2024-04-25 01:13 UTC, merged