Navbar : Help Icon tab navigation
trimble-oss/modus-web-components pull request #2417
Opened 2024-04-05 11:08 UTC by ElishaSamPeterPrabhu

## Description

References
 Fixes: #1945

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

2024-04-09 17:57 UTC, cjwinsor commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +    if (event.code !== 'Enter') {
Can we also add support for `space`

2024-04-09 17:59 UTC, cjwinsor requested changes

2024-04-09 17:59 UTC, cjwinsor commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
>                          <IconHelp size="24" onClick={(event) => this.helpMenuClickHandler(event)} />
It might make sense to move the handling for `onclick` to the `span` to keep things organized.

2024-04-09 17:59 UTC, cjwinsor commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +    this.helpOpen.emit();
Since these lines are duplicated, does it make sense to make an `openHelp()` function that can be called from mouse and key press events?

2024-04-10 06:54 UTC, ElishaSamPeterPrabhu commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +    if (event.code !== 'Enter') {
Yes

2024-04-10 07:01 UTC, ElishaSamPeterPrabhu commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +    this.helpOpen.emit();
Formatted

2024-04-10 07:01 UTC, ElishaSamPeterPrabhu commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
>                          <IconHelp size="24" onClick={(event) => this.helpMenuClickHandler(event)} />
Modified

2024-04-10 21:22 UTC, cjwinsor approved these changes

2024-04-10 21:23 UTC, merged