Navbar: Add Badge icon to Notification Button
trimble-oss/modus-web-components pull request #2424
Opened 2024-04-09 10:28 UTC by ElishaSamPeterPrabhu

## Description

- Added prop counter as a badge to the notification icon button

References #
Fixes: #1011 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

## How Has This Been Tested?

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

2024-04-09 17:50 UTC, cjwinsor requested changes

2024-04-09 17:50 UTC, cjwinsor commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +  @Prop() counter: string;
Can we make this `notificationCount` as a number?

2024-04-09 17:50 UTC, cjwinsor commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +    console.log('countervalue', counterValue);
Remove `console` logs

Also this above logic can probably be simplified if the `prop` is a `number`

Also break this into a separate function, render is getting a little heavy with all this logic.  something like 
```js
const notificationCount = getNotificationCount()`
```
That can return a string value

2024-04-09 17:50 UTC, cjwinsor commented on stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar.stories.tsx
> +const Template = ({ buttons,counter, enableSearchOverlay, helpTooltip, profileMenuOptions, searchTooltip, showHelp, showProfile, showSearch }) => html`
missing a space after the `,` and before `counter`

2024-04-09 17:50 UTC, cjwinsor commented on stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar.stories.tsx
> +const FailedToLoadAvatarTemplate = ({ buttons,counter, enableSearchOverlay, helpTooltip, profileMenuOptions, searchTooltip, showHelp, showProfile, showSearch }) => html`
missing a space after the , and before counter

2024-04-09 17:51 UTC, cjwinsor commented
@coliff @egunther39 Can you take a look and let me know if the size of this notification badge is too small in the deploy preveiw?...

2024-04-09 17:53 UTC, cjwinsor commented on stencil-workspace/src/components/modus-navbar/modus-navbar.vars.scss
> +$modus-navbar-badge-bg: var(--modus-navbar-badge-bg, #da212c) !default;
Badge is showing as blue in deploy preview

2024-04-09 18:03 UTC, egunther39 commented
@cjwinsor - It's a bit small. Here is an example of the red badge we use in our application. The badge is 20x20 inside/overlaid above the 48x48 navbar button/icon. I'd suggest, doing the same.
![image](https://github.com/trimble-oss/modus-web-components/assets/98049598/d599d18c-6949-448f-bd87-27313da2e559)

2024-04-09 18:14 UTC, cjwinsor commented
Here is a shot with a medium badge
![image](https://github.com/trimble-oss/modus-web-components/assets/1130129/2a8e048a-3f59-42cd-8323-df2b3d005ecc)

2024-04-10 05:38 UTC, ElishaSamPeterPrabhu commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +  @Prop() counter: string;
Isn't string preferable so in the future we can allow up to 3 character string

2024-04-10 06:54 UTC, ElishaSamPeterPrabhu commented on stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar.stories.tsx
> +const FailedToLoadAvatarTemplate = ({ buttons,counter, enableSearchOverlay, helpTooltip, profileMenuOptions, searchTooltip, showHelp, showProfile, showSearch }) => html`
Formatted

2024-04-10 06:54 UTC, ElishaSamPeterPrabhu commented on stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar.stories.tsx
> +const Template = ({ buttons,counter, enableSearchOverlay, helpTooltip, profileMenuOptions, searchTooltip, showHelp, showProfile, showSearch }) => html`
Formatted

2024-04-10 06:55 UTC, ElishaSamPeterPrabhu commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +    console.log('countervalue', counterValue);
Modified

2024-04-10 06:55 UTC, ElishaSamPeterPrabhu commented on stencil-workspace/src/components/modus-navbar/modus-navbar.tsx
> +  @Prop() counter: string;
Made it to be a number for now

2024-04-10 21:31 UTC, cjwinsor requested changes

2024-04-10 21:36 UTC, cjwinsor commented
@ElishaSamPeterPrabhu Notifications are still blue in the deploy preview as well.

2024-04-11 13:07 UTC, ElishaSamPeterPrabhu commented on stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar-storybook-docs.mdx
> +| `notificationCount`    | `notification-count`     | (optional) To add the counter value to the notification icon.
Updated

2024-04-11 13:07 UTC, ElishaSamPeterPrabhu commented on stencil-workspace/storybook/stories/components/modus-navbar/modus-navbar.stories.tsx
> +        type: { summary: 'string' },
Updated

2024-04-11 13:21 UTC, ElishaSamPeterPrabhu commented
> @ElishaSamPeterPrabhu Notifications are still blue in the deploy preview as well.

Now its red

> @ElishaSamPeterPrabhu Notifications are still blue in the deploy preview as well.

Its red now

2024-04-12 01:10 UTC, cjwinsor approved these changes

2024-04-12 01:11 UTC, merged