Blank aria label fixes
trimble-oss/modus-web-components pull request #2447
Opened 2024-04-18 01:09 UTC by austinoneil

## Description

Fix issue where, when a blank aria label is passed in, the attribute would render on the inner elements for most elements.

References #2409

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

Many, many e2e tests

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

2024-04-18 06:16 UTC, coliff commented
This looks great - thanks! Don't worry about the failed [accessibility-lint GitHub Action](https://github.com/dequelabs/axe-linter-action). This was something we recently added but it's a bit buggy and hasn't been updated in a while and has many deprecation warnings.

2024-04-18 16:05 UTC, coliff submitted a review, later dismissed

2024-04-25 01:32 UTC, cjwinsor requested changes

2024-04-25 01:32 UTC, cjwinsor commented on stencil-workspace/src/components/modus-alert/modus-alert.tsx
> +      className[typeClass] = typeClass;
Can you set `className[typeClass] = true`.  I feel this is working as typeClass is truthy, but `true` should avoid any confusion about what the value should be (true/false)

2024-04-25 01:32 UTC, cjwinsor commented on stencil-workspace/src/components/modus-alert/modus-alert.tsx
> +      <div aria-label={this.ariaLabel == '' ? null : this.ariaLabel} class={className} role="alert">
Later on you switch to `this.ariaLabel || undefined`, can we  update all locations to use the same optimized convention?

2024-04-27 06:30 UTC, austinoneil commented on stencil-workspace/src/components/modus-alert/modus-alert.tsx
> +      <div aria-label={this.ariaLabel == '' ? null : this.ariaLabel} class={className} role="alert">
Done.

2024-04-30 03:58 UTC, austinoneil commented on stencil-workspace/src/components/modus-alert/modus-alert.tsx
> +      className[typeClass] = typeClass;
done

2024-05-02 02:35 UTC, cjwinsor approved these changes

2024-05-02 02:35 UTC, merged