Content Tree: Add event emitter when item's label being updated
trimble-oss/modus-web-components pull request #2478
Opened 2024-04-24 06:55 UTC by ElishaSamPeterPrabhu

## Description

- Added an event emitter `itemLabelChange` when item's label being updated

References #2476 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

2024-04-25 00:56 UTC, cjwinsor requested changes
@ElishaSamPeterPrabhu I'm good with the event name.  This needs a test to validate that when the label is changed, that the event is fired and contains the new label value.

2024-04-25 00:56 UTC, cjwinsor commented on stencil-workspace/src/components/modus-switch/readme.md
> +| `checked`   | `checked`    | (optional) Whether the switch is checked.  | `boolean`             | `false`     |
@ElishaSamPeterPrabhu This is a string

2024-04-25 06:22 UTC, ElishaSamPeterPrabhu commented on stencil-workspace/src/components/modus-switch/readme.md
> +| `checked`   | `checked`    | (optional) Whether the switch is checked.  | `boolean`             | `false`     |
set it back to undefined

2024-05-02 21:52 UTC, cjwinsor approved these changes

2024-05-02 21:52 UTC, merged