Autocomplete: show all items Behavior
trimble-oss/modus-web-components pull request #2484
Opened 2024-04-26 04:14 UTC by rjavier-trimbler

## Description
Behavior here:
**Default:**
1- it shows all options when focus
2- if you click an option it will highlight it and hide the combo box
3- if you click on the autocomplete again it will show all the options with the selected option 
4- if you're typing, it will filter the options 
5- if there's no matches then it will show the "no found message" and when you focusOut it will place the previous option selected
6- if you clear the autocomplete then it will remove the highlighted option selected 

**disableCloseOnSelect**
the same behavior as Default but the step 2 it wont hide the combo box

**showOptionsOnFocus**
 the same behavior as Default but the step 3 it only show all the options if there's no option selected

A good reference of what we're following on this PR:
https://mui.com/material-ui/react-autocomplete/#combo-box

TODO: THIS A DRAFT PR FOR NOW, THE FOLLOWING THINGS ARE MISSING:
- add unit test
- make this improvements for custom autcomplete

References #2282 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

2024-05-07 22:55 UTC, cjwinsor commented on stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
> +    if (!this.hasOptionMatched(this.value)) {
Nesting if statements makes the code harder to read.  Can you switch this to something like 
```js
if (this.hasOptionsMatched(this.value) || 
    this.selectedOption === '' || 
    this.value === '' || 
    this.hasFocus) {
  return;
}

this.value = this.selectedOption;
this.disableFiltering = true;
```

This makes it easier to tell what conditions cause it to not continue.

2024-05-07 22:57 UTC, cjwinsor commented on stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
> +    if (isSearchEmpty) this.selectedOption = '';
one liners generally make code harder to read as it puts the action at a variable distance from the left depending on the condition.  Update to: 

```js
if (isSearchEmpty) {
  this.selectionOption = '';
}
```

2024-05-07 22:58 UTC, cjwinsor requested changes
I haven't functionally validated this works.  Has this been QA'd by your team?

2024-05-07 23:51 UTC, rjavier-trimbler commented on stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
> +    if (!this.hasOptionMatched(this.value)) {
done!

2024-05-07 23:51 UTC, rjavier-trimbler commented on stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
> +    if (isSearchEmpty) this.selectedOption = '';
done!

2024-05-16 19:03 UTC, J-Ruiz1 commented
@cjwinsor this has already been tested for the following scenarios [in this user story](https://e-builderinc.atlassian.net/browse/NAV-589):

**Scenario 1**: Validate that the Process Filter shows all available options when focused

**Scenario 2**: Validate that the Process Filter is able to filter based on search criteria via adding characters

**Scenario 3**: Validate that the Process Filter is able to filter based on search criteria via removing characters. An empty again Process filter must show all available options

**Scenario 4**: Validate that the Process Filter clears all characters and show the placeholder text "search processes" when characters are entered but the filter loses focus without a selection

**Scenario 5**: Validate that the Process Filter shows all available options when refocusing on the filter after an option was previously selected. The already selected item item shows with a checkmark on the right and is the second one from the bottom of the list  (when able)

**Scenario 6**: Validate that when there are no matches when searching with no previous selection the dropdown will show a “not found” message.

**Scenario 7**: Validate that when there are no matches when searching with a previous selection the dropdown will show a “not found” message. Focusing out will show the previously selected option

**Scenario 8**: Validate that clearing the autocomplete removes the highlighted selection.

2024-05-30 16:01 UTC, cjwinsor requested changes
Things I noticed:

A flicker was introduced when picking an item (in my case, I didn't set any props, only set `options`) that wasn't there before. The text goes blank, then shows new value.

It now behaves as if `show-options-on-focus` is always enabled.  It should not show the items on focus until that prop is set to true.  There seems to be a previous bug where once there is a selection it opens the autocomplete on focus even when `show-options-on-focus` is not set to `true`, that isn't correct either.  

If I have a value selected, and while focused on the textbox, click the down arrow, it erases the text and the selection.  The down arrow should not remove the value/selection.

2024-06-06 13:18 UTC, rjavier-trimbler commented on stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
> +    if (selectedOption) {
I did but there's a requirement that says 

`The already selected item item shows with a checkmark on the right and is the second one from the bottom of the list`.

So I had to play around with the offset position to achieve that.  I added it anyway.

2024-06-06 21:56 UTC, cjwinsor commented on stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
> +    if (selectedOption) {
Why is there such a super specific requirement that "is the second one from the bottom"... seems arbitrary and over complicates.  The key is that the item is visible. if its the first x number of items, it can never be second from bottom... and if it is the last item as well... very arbitrary and I don't agree with that aspect of this.

2024-06-07 15:59 UTC, rjavier-trimbler commented on stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
> +    if (selectedOption) {
the requirement is this:



This autocomplete has 16 options:

If i click on the option 10 which it cant be displayed because of the max-height then the scroll position will be moved to show the selected option as the second from bottom only if this is not the last item. This wont happen if you select the first option or any of the options that are displayed without the help of scrolling.
<img width="279" alt="Screen Shot 2024-06-07 at 11 53 54 AM" src="https://github.com/trimble-oss/modus-web-components/assets/141681143/a1f5fc05-c109-4aee-80ab-5486d211ff35">

<img width="312" alt="Screen Shot 2024-06-07 at 11 59 25 AM" src="https://github.com/trimble-oss/modus-web-components/assets/141681143/cd3dc678-571e-470f-bdc8-244077e3adec">

2024-06-07 22:41 UTC, cjwinsor commented on stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
> +    if (selectedOption) {
@rjavier-trimbler I understood the requirements, I just didn't agree with them. I will have to talk to UX on Monday on this one.  There are no modus guidelines around where the selection is positioned and this particular aspect was not in the Aha submission that was approved.  It increases the complexity of the code with no basis of support from the Modus Design System.  My issue is you were given this as a requirement when it was outside the scope of what was approved.

2024-06-12 19:23 UTC, J-Ruiz1 commented
Validated that the autocomplete complies with the following scenarios

Scenario 1: Validate that the Process Filter shows all available options when focused

Scenario 2: Validate that the Process Filter is able to filter based on search criteria via adding characters

Scenario 3: Validate that the Process Filter is able to filter based on search criteria via removing characters. An empty again Process filter must show all available options

Scenario 4: Validate that the Process Filter shows all available options when refocusing on the filter after an option was previously selected. 

Scenario 5: Validate that when there are no matches when searching with no previous selection the dropdown will show a “not found” message.

Scenario 6: Validate that when there are no matches when searching with a previous selection the dropdown will show a “not found” message. 

Scenario 7: Validate that clearing the autocomplete removes the highlighted selection.

2024-06-14 17:56 UTC, cjwinsor requested changes

2024-06-14 17:56 UTC, cjwinsor commented on stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
> +    console.log(this.value);
Can you remove this console.log

2024-06-14 18:35 UTC, cjwinsor approved these changes

2024-06-14 18:35 UTC, merged