1505 modus utility panel component bare bones
trimble-oss/modus-web-components pull request #2536
Opened 2024-05-29 07:38 UTC by ElishaSamPeterPrabhu

## Description

- Developed an Utility component based on the guidelines from https://modus.trimble.com/components/web/utility-panel/

References 
Fixes #1505 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

2024-05-29 08:16 UTC, coliff commented on stencil-workspace/src/components/modus-utility-panel/modus-utility-panel.scss
need to run stylelint on this (will auto-sort the properties alphabetically)

2024-05-29 08:17 UTC, coliff commented on stencil-workspace/src/components/modus-utility-panel/modus-utility-panel.tsx
needs `// eslint-disable-next-line @typescript-eslint/no-unused-vars` on the first line.

2024-05-29 08:18 UTC, coliff commented on stencil-workspace/storybook/stories/components/modus-utility-panel/modus-utility-panel.stories.tsx
> +const setEventListeners = (containerId) => {
`'containerId' is defined but never used` - is that intentional?

2024-05-29 09:55 UTC, ElishaSamPeterPrabhu commented on stencil-workspace/storybook/stories/components/modus-utility-panel/modus-utility-panel.stories.tsx
> +const setEventListeners = (containerId) => {
Its not and removed

2024-05-29 09:55 UTC, ElishaSamPeterPrabhu commented on stencil-workspace/src/components/modus-utility-panel/modus-utility-panel.tsx
Added eslint

2024-05-29 09:55 UTC, ElishaSamPeterPrabhu commented on stencil-workspace/src/components/modus-utility-panel/modus-utility-panel.scss
Ran and changes the order

2024-06-14 18:00 UTC, cjwinsor requested changes

2024-06-14 21:46 UTC, cjwinsor commented
Once my final 2 comments are resolved, this is good to merge. @ElishaSamPeterPrabhu @prashanthr6383 @coliff

2024-06-17 06:32 UTC, ElishaSamPeterPrabhu commented on stencil-workspace/storybook/stories/components/modus-utility-panel/modus-utility-panel-storybook-docs.mdx
> +</script>`
Removed

2024-06-17 13:09 UTC, coliff requested changes
There is an accessibilty violation so we can't merge it as it is.
![image](https://github.com/trimble-oss/modus-web-components/assets/1212885/7c3b92ea-8860-41dc-afe9-8a994163db82)

Can you fix it please?

2024-06-19 15:45 UTC, ElishaSamPeterPrabhu commented
> There is an accessibilty violation so we can't merge it as it is. ![image](https://private-user-images.githubusercontent.com/1212885/340315631-7c3b92ea-8860-41dc-afe9-8a994163db82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4MTE2MzIsIm5iZiI6MTcxODgxMTMzMiwicGF0aCI6Ii8xMjEyODg1LzM0MDMxNTYzMS03YzNiOTJlYS04ODYwLTQxZGMtYWZlOS04YTk5NDE2M2RiODIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTlUMTUzNTMyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDM3Y2E3ZmI1OWE0ZTk2ZjliYjY2YzA2NTBlNDU5MjY1ZWYyZDJkYjE0MzkzNzk5MzI2MjEwNmE3ZmMwZDQyZiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Yn_1MoRGUOnQJjRYfN7uodP3U4bFasDM2ofNrc7cFxs)
> 
> Can you fix it please?

@coliff 
This issue is present in navbar 
we can remove the navbar and add a button to trigger the uility panel or fix it in navbar

2024-06-20 06:38 UTC, coliff commented
@ElishaSamPeterPrabhu if you can fix that a11y issue on the navbar separaetly then that'd be great!

2024-06-20 06:39 UTC, coliff approved these changes

2024-06-20 06:39 UTC, merged