Table - Api for handling cell edit
trimble-oss/modus-web-components pull request #2568
Opened 2024-06-06 13:01 UTC by prashanthr6383

## Description

References 
Fix #2541  

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

2024-06-14 22:23 UTC, cjwinsor requested changes

2024-06-14 22:23 UTC, cjwinsor commented on stencil-workspace/src/components/modus-table/parts/cell/modus-table-cell-main/readme.md
> +| `rowIndex` | `string` |             |
Can you set the comments above the variables so this is autogenerated with the same description as you have in storybook?

2024-06-14 22:23 UTC, cjwinsor commented on stencil-workspace/src/components/modus-table/modus-table.tsx
> +  async getCellEditable(rowIndex: string, columnId: string): Promise<void> {
Looking at various libraries we have the following implementation.  

@coliff @prashanthr6383 @ElishaSamPeterPrabhu 
Seems like its all over the place.  Perhaps if we had the API also support getting cells, the `.edit()` seems the most straightforward.  But for now I am leaning towards the function being `toggleCellEdit` and have the function be able to toggle.  Ultimately I leave it up to the group to decide but I don't think it should be `getCellEditable` as that makes it sound like its going to return a `boolean` that says if the cell is currently editable or not.  Once this decision is made, this PR can be merged.

| Library           | Function Name       | Example Code Snippet                                            |
|-------------------|---------------------|-----------------------------------------------------------------|
| AG Grid           | `startEditingCell`  | `gridOptions.api.startEditingCell({ rowIndex: 1, colKey: 'fieldName' });` |
| Handsontable      | `beginEditing`  | `hot.selectCell(rowIndex, colIndex); hot.getActiveEditor().beginEditing();` |
| Tabulator         | `edit`          | `var cell = table.getCell(rowIndex, colIndex); cell.edit();`    |
| jqGrid            | `editCell`          | `$('#grid').jqGrid('editCell', rowId, colIndex, true);`         |
| DataTables        | `edit`            | `var table = $('#example').DataTable(); table.cell(rowIndex, colIndex).edit();` |
| Kendo UI Grid     | `editCell`          | `var grid = $("#grid").data("kendoGrid"); var cell = grid.table.find("tr:eq(" + rowIndex + ") td:eq(" + colIndex + ")"); grid.editCell(cell);` |
| PrimeReact        | `toggleCellEdit`    | `const cell = { field: 'fieldName', rowIndex: 1 }; dt.current.toggleCellEdit(cell);` |
| Wijmo             | `startEditing`      | `var grid = wijmo.Control.getControl('#grid'); grid.startEditing(true, rowIndex, colIndex);` |

2024-06-17 06:36 UTC, prashanthr6383 commented on stencil-workspace/src/components/modus-table/modus-table.tsx
> +  async getCellEditable(rowIndex: string, columnId: string): Promise<void> {
@ElishaSamPeterPrabhu @coliff  can you please suggest ?

2024-06-17 06:42 UTC, ElishaSamPeterPrabhu commented on stencil-workspace/src/components/modus-table/modus-table.tsx
> +  async getCellEditable(rowIndex: string, columnId: string): Promise<void> {
I suggest `getEditableCell()` as it sounds like it returns cells who are editable, rather than `getCellEditable()` which sound like it returns the state of the cell whether its editable or not.
@prashanthr6383

2024-06-17 13:18 UTC, prashanthr6383 commented on stencil-workspace/src/components/modus-table/modus-table.tsx
> +  async getCellEditable(rowIndex: string, columnId: string): Promise<void> {
@coliff can you suggest on this

2024-06-19 07:14 UTC, coliff commented on stencil-workspace/src/components/modus-table/modus-table.tsx
> +  async getCellEditable(rowIndex: string, columnId: string): Promise<void> {
I don't have a strong opinion on this, but Sam's suggestion above makes sense.

2024-06-20 13:58 UTC, coliff approved these changes

2024-06-20 13:58 UTC, merged