2585: Autocomplete to emit selection changed event with ids
trimble-oss/modus-web-components pull request #2586
Opened 2024-06-12 09:40 UTC by Vasistan

## Description

This fix introduces new event **selectionsChanged** on modus autocomplete. This event emits when the option selections changes (selected/deselected)

References #2585

## Type of change

- [+] Bug fix (non-breaking change which fixes an issue)
- [+] New feature (non-breaking change which adds functionality)
- [-] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [+] Documentation update

## How Has This Been Tested?

Using the runbook, these changes are validated

## Checklist

- [+] My code follows the style guidelines of this project
- [+] I have performed a self-review of my own code
- [-] I have commented my code, particularly in hard-to-understand areas
- [+] I have made corresponding changes to the documentation
- [+] My changes generate no new warnings
- [-] I have added tests that prove my fix is effective or that my feature works
- [+] New and existing unit tests pass locally with my changes
- [-] Any dependent changes have been merged and published in downstream modules
- [+] I have checked my code and corrected any misspellings

2024-06-18 04:19 UTC, ElishaSamPeterPrabhu reviewed
Since the chip has a new prop `chipId` it should be added to the documentation of chips.

2024-06-18 04:19 UTC, ElishaSamPeterPrabhu commented on stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
> +  @Event() selectionsChanged: EventEmitter<string[]>;
The event is not emitted when the chip is removed with the help of close icon.

2024-06-18 04:22 UTC, Vasistan commented on stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
> +  @Event() selectionsChanged: EventEmitter<string[]>;
It is actually emitting that from handleCloseClick(...) that is where it remove the selected chip

2024-06-18 04:26 UTC, ElishaSamPeterPrabhu commented on stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
> +  @Event() selectionsChanged: EventEmitter<string[]>;
Its getting emitted when removed by deselecting from the dropdown.
Tested in this deploy preview : https://deploy-preview-2586--moduswebcomponents.netlify.app/

2024-06-18 04:41 UTC, Vasistan commented on stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
> +  @Event() selectionsChanged: EventEmitter<string[]>;
pushed the changes in the document update

2024-06-18 04:50 UTC, ElishaSamPeterPrabhu commented on stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
> +  @Event() selectionsChanged: EventEmitter<string[]>;
Its getting emitted now

2024-06-18 04:51 UTC, ElishaSamPeterPrabhu commented
> Since the chip has a new prop `chipId` it should be added to the documentation of chips.

@Vasistan The documentation of chips is not fully updated as `chipId` is not present in the canvas controls.

2024-06-18 05:00 UTC, ElishaSamPeterPrabhu commented on stencil-workspace/src/components/modus-chip/modus-chip.tsx
> +        chip-id={this.chipId}
Instead of `chip-id` it can be `id` for better accessibility purposes, you can refer to this link for more information regarding this : https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/button_role

2024-06-18 05:12 UTC, Vasistan commented on stencil-workspace/src/components/modus-chip/modus-chip.tsx
> +        chip-id={this.chipId}
Thanks for the suggestion. I was worried about the uniqueness of the ids available on the whole page (elements), that is why I introduced a new attribute. If this is a necessity, I can use the `id` field.

2024-06-18 08:35 UTC, Vasistan commented on stencil-workspace/src/components/modus-chip/modus-chip.tsx
> +        chip-id={this.chipId}
@ElishaSamPeterPrabhu updated the PR with review comments

2024-06-18 10:33 UTC, ElishaSamPeterPrabhu commented
@Vasistan The chip IDs are not editable in the canvas

2024-06-20 14:28 UTC, coliff commented on stencil-workspace/storybook/stories/components/modus-chip/modus-chip.stories.tsx
> +      description: "This chip's id, this created much more visiblity for testing",
please fix these typos

2024-06-25 11:31 UTC, coliff requested changes
Please fix the typos and resolve conflicts and then mark as ready for review (not draft). Thanks!

2024-06-27 08:06 UTC, Vasistan reviewed
Review feedback completed

2024-06-27 09:08 UTC, ElishaSamPeterPrabhu approved these changes

2024-06-27 09:09 UTC, merged