Issue-2733: modal update to hide border lines unless content is scrollable
trimble-oss/modus-web-components pull request #2734
Opened 2024-07-29 15:59 UTC by ausnewland11

## Description

Update to the modal component to hide header and footer border lines unless content is scrollable

References [#2733](https://github.com/trimble-oss/modus-web-components/issues/2733)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

2024-07-30 21:50 UTC, cjwinsor requested changes

2024-07-30 21:50 UTC, cjwinsor commented on stencil-workspace/src/components/modus-modal/modus-modal.tsx
> +    this.checkContentScrollable();
@ausnewland11 Can you make sure that if the content (slot) is updated and the state changes in a way that would toggle `isContentScrollable` that the modal is updated accordingly?

2024-08-01 17:22 UTC, ausnewland11 commented on stencil-workspace/src/components/modus-modal/modus-modal.tsx
> +    this.checkContentScrollable();
@cjwinsor Basing it off the docs [here ](https://modus.trimble.com/components/web/modals/styles/), the modal will be scrollable when the height of the dialog is past it's maximum. So the content/slot will contribute to that and the component re-renders anytime there is a change which will toggle `isContentScrollable` to update. I've written a test to simulate this

2024-08-09 13:46 UTC, prashanth-offcl commented on stencil-workspace/src/components/modus-modal/modus-modal.tsx
> +    this.checkContentScrollable();
Hi @ausnewland11, I just tested the scenario Chris mentioned (by dynamically adding content using timeout) and the scrollable class is not added. Can you check it?

2024-08-09 13:55 UTC, ausnewland11 commented on stencil-workspace/src/components/modus-modal/modus-modal.tsx
> +    this.checkContentScrollable();
@prashanth-offcl Did you do this testing in the browser or by running the component locally?

2024-08-09 14:53 UTC, prashanth-offcl commented on stencil-workspace/src/components/modus-modal/modus-modal.tsx
> +    this.checkContentScrollable();
@ausnewland11 I first tried in the deploy preview and ran the component locally as well.

2024-08-12 14:20 UTC, ausnewland11 commented on stencil-workspace/src/components/modus-modal/modus-modal.tsx
> +    this.checkContentScrollable();
@prashanth-offcl I've pushed an update. Could you please test again now

2024-08-22 10:57 UTC, prashanth-offcl commented on stencil-workspace/src/components/modus-modal/modus-modal.tsx
> +    this.checkContentScrollable();
@ausnewland11 This is the test code I'm using and I can still reproduce it. can you try with this once?

```
<modus-button id="btn-modal" color="primary">Open modal</modus-button>
<modus-modal
  header-text="Modal title"
  primary-button-text="Save changes"
  secondary-button-text="Sweet!"
  primary-button-aria-label="Save changes"
  secondary-button-aria-label="Sweet">
  <p>
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi voluptatem, deleniti laborum alias temporibus
    fuga iste tempora. Consequatur, aliquid, deleniti commodi ut eos rem, provident possimus iusto pariatur maiores
    autem!
  </p>
</modus-modal>

<script>
  document.querySelector('#btn-modal').addEventListener('buttonClick', () => {
    document.querySelector('modus-modal').open();
  });
  window.setTimeout(() => {
    const modal = document.querySelector('modus-modal');
    let html = '';
    for (let i = 0; i < 40; i++) {
      html += `<p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Eligendi voluptatem, deleniti laborum alias temporibus
                fuga iste tempora. Consequatur, aliquid, deleniti commodi ut eos rem, provident possimus iusto pariatur maiores
                autem!
              </p>`;
    }
    modal.innerHTML = html;
  }, 3000);
</script>
```

2024-08-22 15:42 UTC, ausnewland11 commented on stencil-workspace/src/components/modus-modal/modus-modal.tsx
> +    this.checkContentScrollable();
@prashanth-offcl Thank you for sharing your testing code, with that I was able to see what you were mentioning. I've added a resizeObserver that now works and adds the `Scrollable `class dynamically. Thank you for your patience on this

2024-08-23 12:49 UTC, prashanth-offcl approved these changes

2024-08-23 12:59 UTC, prashanth-offcl commented on stencil-workspace/src/components/modus-modal/modus-modal.tsx
> +    this.checkContentScrollable();
@ausnewland11 You're welcome. It is working nice now :)

2024-08-23 13:01 UTC, merged