2802 datepicker add position property to control component placement relative to the wrapped item
trimble-oss/modus-web-components pull request #2808
Opened 2024-08-26 07:45 UTC by ElishaSamPeterPrabhu

## Description

- Added a prop called `calendar-placement` to set the position of the calendar 
- Added popper function to change position seamlessly while scrolling but the default position is set to bottom-start
References 
Fixes #2802 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

2024-08-27 15:35 UTC, prashanth-offcl requested changes
@ElishaSamPeterPrabhu The prop name needs to be updated to `position` and we should handle the case described in the [link ](https://popper.js.org/docs/v2/modifiers/hide/). Rest of the changes looks good to me.

2024-08-27 18:10 UTC, ElishaSamPeterPrabhu commented
> `position`

Changed prop name to position

2024-08-28 05:49 UTC, prashanth-offcl approved these changes

2024-08-28 09:44 UTC, ElishaSamPeterPrabhu commented
> > `position`
> 
> Changed prop name to position ,not yet implemented the hide case

implemented the hide feature

2024-08-28 12:07 UTC, merged