Progress Bar: Add Indeterminate state
trimble-oss/modus-web-components pull request #2831
Opened 2024-09-03 11:49 UTC by ElishaSamPeterPrabhu

## Description

- Added prop called `mode` to determine determinate or indeterminate state
- Set aria-valuemax, aria-valuemin ,aria-valuenow to null

References 
Fixes #2785 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation update

## How Has This Been Tested?

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

2024-09-03 12:55 UTC, coliff commented on stencil-workspace/src/components/modus-progress-bar/modus-progress-bar.tsx
> -// eslint-disable-next-line
this is needed at the top

2024-09-03 12:56 UTC, coliff commented on stencil-workspace/src/components/modus-progress-bar/modus-progress-bar.scss
> +    &.indeterminate {
please run css lint before committing so it auto-sorts and formats the CSS

2024-09-06 09:46 UTC, prashanth-offcl requested changes
@ElishaSamPeterPrabhu please add E2E tests for the changes and resolve the build error and review comments.

2024-09-06 09:46 UTC, prashanth-offcl commented on stencil-workspace/src/components/modus-progress-bar/modus-progress-bar.tsx
> +  @Prop() mode: 'determinate' | 'indeterminate' = 'determinate';
@ElishaSamPeterPrabhu Stencil style guide recommends to keep the props in alphabetical order 
https://stenciljs.com/docs/style-guide#high-level-example-commented

2024-09-09 05:18 UTC, ElishaSamPeterPrabhu commented on stencil-workspace/src/components/modus-progress-bar/modus-progress-bar.tsx
> -// eslint-disable-next-line
added

2024-09-09 05:18 UTC, ElishaSamPeterPrabhu commented on stencil-workspace/src/components/modus-progress-bar/modus-progress-bar.tsx
> +  @Prop() mode: 'determinate' | 'indeterminate' = 'determinate';
Modified the props to be in aphabetical order

2024-09-09 05:19 UTC, ElishaSamPeterPrabhu commented on stencil-workspace/src/components/modus-progress-bar/modus-progress-bar.scss
> +    &.indeterminate {
Ran lint test and modified css properties positions

2024-09-09 09:10 UTC, ElishaSamPeterPrabhu commented
> @ElishaSamPeterPrabhu please add E2E tests for the changes and resolve the build error and review comments.

Added test cases and resolved comments

2024-09-11 17:51 UTC, prashanth-offcl commented on stencil-workspace/storybook/stories/components/modus-progress-bar/modus-progress-bar-storybook-docs.mdx
>  ```html
Can you add the example code for the indeterminate mode?

2024-09-12 07:32 UTC, prashanth-offcl approved these changes

2024-09-12 07:33 UTC, merged