DatePicker: bug with errorText
trimble-oss/modus-web-components pull request #2938
Opened 2024-10-29 06:23 UTC by prashanthr6383

## Description

References 
Fixes #2819  

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

2024-11-04 06:53 UTC, jewel-shajan requested changes
The validText functionality isn't working as intended. When valid text is provided, the date picker is highlighted in green, but the text itself is not displayed.

2024-11-04 06:58 UTC, prashanthr6383 commented
> The validText functionality isn't working as intended. When valid text is provided, the date picker is highlighted in green, but the text itself is not displayed.

fixed. please check

2024-11-05 12:38 UTC, jewel-shajan reviewed
Testing has been completed, and everything is functioning as expected.

2024-11-06 06:27 UTC, jewel-shajan approved these changes

2024-11-06 12:31 UTC, merged