Modal: Close button displays top left if headerText is not provided
trimble-oss/modus-web-components pull request #2977
Opened 2024-11-13 08:27 UTC by prashanthr6383

## Description

References 

Fixes #2598 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

2024-11-13 12:14 UTC, jewel-shajan reviewed
Testing is finished, and everything looks good. Now moving forward for PR review.

2024-11-14 04:05 UTC, saravananrmsmy requested changes

2024-11-14 04:05 UTC, saravananrmsmy commented on stencil-workspace/src/components/modus-modal/modus-modal.tsx
> +        <span class="modal-title">{this.headerText}</span>
@prashanthr6383 
If our intention is only to keep the close icon at the right can we do it without the introduction of span. Adding `margin-left: auto` for the .header-buttons should work. Can we try it out ?

2024-11-14 12:57 UTC, prashanthr6383 commented on stencil-workspace/src/components/modus-modal/modus-modal.tsx
> +        <span class="modal-title">{this.headerText}</span>
@saravananrmsmy  yes it works great. I have updated

2024-11-15 06:55 UTC, jewel-shajan reviewed
Testing has been successfully completed after the changes and the update has been moved to PR review.

2024-11-25 10:08 UTC, saravananrmsmy approved these changes

2024-11-25 10:10 UTC, coliff approved these changes

2024-11-25 10:10 UTC, merged