Slider: fix modus slider selection
trimble-oss/modus-web-components pull request #3026
Opened 2024-11-25 15:05 UTC by SuruthiShriP

## Description

There is no difference in the visibility of selected and non selected part of the slider as 
the entire part is shown in blue color.

https://deploy-preview-3026--moduswebcomponents.netlify.app/?path=/story/components-slider--default

References #2717

2024-11-25 16:30 UTC, SuruthiShriP commented
> @SuruthiShriP - Build is failing - please run tests locally to ensure all is working before committing changes. Thanks! ![image](https://private-user-images.githubusercontent.com/1212885/389598693-fd78eedc-435e-400d-b7a9-92aa7ce9490d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1NTI0NTUsIm5iZiI6MTczMjU1MjE1NSwicGF0aCI6Ii8xMjEyODg1LzM4OTU5ODY5My1mZDc4ZWVkYy00MzVlLTQwMGQtYjdhOS05MmFhN2NlOTQ5MGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjVUMTYyOTE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzE0OTljN2Y5NjNmYTBkOTc2YzlkYzU5ODA0ZjFlNmI3YThhZGZhZDg2NTBmYWRlMjFjZjYzYjU5OTQ4ZjkyYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.QvES_55nhv-MtGl8faKOwpIZu2pJPBbhRms3eETHYKc)



My local tests are running successfully, but not sure why its failing here. Can you please help me?

2024-11-26 07:10 UTC, jewel-shajan requested changes
For disabled state UI change is incorrect.
![image](https://github.com/user-attachments/assets/45ef46f3-7651-4a1d-9caf-6b210574c586)                            **In the Changed PR**
![image](https://github.com/user-attachments/assets/4bc1b090-60ba-48d2-a7e3-4fd3e11f632f)                                **Current Version**

2024-11-26 07:17 UTC, coliff commented
Yes, the disabled state should be gray. The slider design in this PR is good, an improvement, but it's actually different to what appears on the Figma file.

We need input from: @enowak1031 and @mitch-trimble if we can proceed with this.

![image](https://github.com/user-attachments/assets/23616b36-07a3-492a-aaca-3ea6bea52ae1)

2024-11-26 07:31 UTC, SuruthiShriP commented
![image](https://github.com/user-attachments/assets/daca13b7-c210-4c90-b09e-aec56ea7816e)
does this makes sense?

2024-11-28 09:51 UTC, jewel-shajan approved these changes

2025-04-07 08:25 UTC, coliff submitted a review, later dismissed

2025-06-23 08:13 UTC, merged