Adds inputmode to text=input
trimble-oss/modus-web-components pull request #534
Opened 2022-07-01 13:09 UTC by coliff

## Description

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (including CHANGELOG updates)
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

2022-07-01 16:20 UTC, ryan-henness-trimble requested changes

2022-07-01 16:20 UTC, ryan-henness-trimble commented on stencil-workspace/src/components/modus-text-input/modus-text-input.tsx
> +                   inputmode={this.inputmode}
we've tried to keep inputs in alpha-order so this would be moved up a bit. Though it does make sense to have it close to `type`, so up to you if you'd like to move it

2022-07-01 16:20 UTC, ryan-henness-trimble commented on stencil-workspace/src/components/modus-text-input/modus-text-input.tsx
> +                   inputmode={this.inputmode}
Nice PR 😄 there's a couple quick additions we should add
1. Under the changelog's 'Unreleased' section, let's add an 'Added' section with a detail about the new `inputmode`
2.  In the test file, `modus-text-input.e2e.ts`, let's add a test to make sure that the new input gets set and rendered correctly. I would test setting one other value other than `text`. This will be very similar to the `'renders changes to type'` test in that file

2022-07-04 10:31 UTC, coliff commented on stencil-workspace/src/components/modus-text-input/modus-text-input.tsx
> +                   inputmode={this.inputmode}
I'm a fan of alphabetical order so I'll move it. :-)

2022-07-05 16:02 UTC, ryan-henness-trimble approved these changes

2022-07-05 16:02 UTC, merged