Text inputs should not have 'clear' icon by default
trimble-oss/modus-web-components pull request #868
Opened 2022-11-21 10:11 UTC by coliff

## Description

Fix for #670

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation update

## How Has This Been Tested?

Locally with Edge v107

## Checklist:

- [x] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (including CHANGELOG updates)
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

2022-11-21 16:26 UTC, ryan-henness-trimble approved these changes

2022-11-22 07:35 UTC, coliff commented
thanks for approving @ryan-henness-trimble but the tests are failing, and I don't think it's ready. It 'works' locally in Storybook for me though with clear button not displaying by default and the option to turn it on works. Can you please take a look when you get a minute? I'm not sure how to resolve the issue.

2022-11-22 17:24 UTC, ryan-henness-trimble commented
Whoops didn't see that failing tests. Looks like some of them depend on `clearable` defaulting to true. @coliff 

### modus-text-input.spec.tsx -
```
import { newSpecPage } from '@stencil/core/testing';
import { ModusTextInput } from './modus-text-input';

describe('modus-text-input', () => {
  it('renders', async () => {
    const page = await newSpecPage({
      components: [ModusTextInput],
      html: '<modus-text-input></modus-text-input>',
    });
    expect(page.root).toEqualHtml(`
      <modus-text-input>
        <mock:shadow-root>
            <div class="modus-text-input">
                <div class="input-container medium">
                    <input class="null" type="text" tabindex="0">
                    <span class="icons"></span>
                </div>
            </div>
        </mock:shadow-root>
      </modus-text-input>
    `);
  });

  it('should get the correct class by size', async () => {
    const modusTextInput = new ModusTextInput();
    let className = modusTextInput.classBySize.get(modusTextInput.size);
    expect(className).toEqual('medium');

    className = modusTextInput.classBySize.get('large');
    expect(className).toEqual('large');
  });

  it('should not default to clearable', async () => {
    const modusTextInput = new ModusTextInput();
    expect(modusTextInput.clearable).toBeFalsy();
  });

  it('should default to enabled', async () => {
    const modusTextInput = new ModusTextInput();
    expect(modusTextInput.disabled).toBeFalsy();
  });

  it('should default to no error text', async () => {
    const modusTextInput = new ModusTextInput();
    expect(modusTextInput.errorText).toBeFalsy();
  });

  it('should default to no valid text', async () => {
    const modusTextInput = new ModusTextInput();
    expect(modusTextInput.validText).toBeFalsy();
  });

  it('should default to no helper text', async () => {
    const modusTextInput = new ModusTextInput();
    expect(modusTextInput.helperText).toBeFalsy();
  });

  it('should default to no inputmode', async () => {
    const modusTextInput = new ModusTextInput();
    expect(modusTextInput.inputmode).toBeFalsy();
  });

  it('should default to size medium', async () => {
    const modusTextInput = new ModusTextInput();
    expect(modusTextInput.size).toEqual('medium');
  });

  it('should default with no search icon', async () => {
    const modusTextInput = new ModusTextInput();
    expect(modusTextInput.includeSearchIcon).toBeFalsy();
  });

  it('should default with no label', async () => {
    const modusTextInput = new ModusTextInput();
    expect(modusTextInput.label).toBeFalsy();
  });

  it('should default with no placeholder', async () => {
    const modusTextInput = new ModusTextInput();
    expect(modusTextInput.placeholder).toBeFalsy();
  });

  it('should default to not required', async () => {
    const modusTextInput = new ModusTextInput();
    expect(modusTextInput.required).toBeFalsy();
  });

  it('should default with no value', async () => {
    const modusTextInput = new ModusTextInput();
    expect(modusTextInput.value).toBeFalsy();
  });

  it('should not default with minimum length validation', async () => {
    const modusTextInput = new ModusTextInput();
    expect(modusTextInput.minLength).toBeFalsy();
  });

  it('should not default with maximum length validation', async () => {
    const modusTextInput = new ModusTextInput();
    expect(modusTextInput.minLength).toBeFalsy();
  });
});
```

### modus-text-input.e2e.ts -
```
import { newE2EPage } from '@stencil/core/testing';

describe('modus-text-input', () => {
  it('renders', async () => {
    const page = await newE2EPage();
    await page.setContent('<modus-text-input></modus-text-input>');

    const element = await page.find('modus-text-input');
    expect(element).toHaveClass('hydrated');
  });

  it('renders changes to clearable', async () => {
    const page = await newE2EPage();

    await page.setContent('<modus-text-input clearable></modus-text-input>');

    let clear = await page.find('modus-text-input >>> .clear');
    expect(clear).toBeNull();

    const textInput = await page.find('modus-text-input');
    textInput.setProperty('value', 'Some value');
    await page.waitForChanges();
    clear = await page.find('modus-text-input >>> .clear');
    expect(clear).not.toBeNull();
  });

  it('renders changes to disabled', async () => {
    const page = await newE2EPage();

    await page.setContent('<modus-text-input></modus-text-input>');

    const textInput = await page.find('modus-text-input');
    const input = await page.find('modus-text-input >>> input');

    expect(textInput).not.toHaveClass('disabled');
    expect(await input.getProperty('disabled')).toBeFalsy();

    textInput.setProperty('disabled', 'true');
    await page.waitForChanges();

    expect(await input.getProperty('disabled')).toBeTruthy();
  });

  it('renders changes to errorText', async () => {
    const page = await newE2EPage();

    await page.setContent('<modus-text-input></modus-text-input>');

    const textInput = await page.find('modus-text-input');
    textInput.setProperty('errorText', 'Error.');
    await page.waitForChanges();

    const inputContainer = await page.find('modus-text-input >>> .input-container');
    expect(inputContainer).toHaveClass('error');

    const errorLabel = await page.find('modus-text-input >>> label.error');
    expect(errorLabel).not.toBeNull();
  });

  it('renders changes to validText', async () => {
    const page = await newE2EPage();

    await page.setContent('<modus-text-input></modus-text-input>');

    const textInput = await page.find('modus-text-input');
    textInput.setProperty('validText', 'Valid.');
    await page.waitForChanges();

    const inputContainer = await page.find('modus-text-input >>> .input-container');
    expect(inputContainer).toHaveClass('valid');

    const validLabel = await page.find('modus-text-input >>> label.valid');
    expect(validLabel).not.toBeNull();
  });

  it('renders changes to helperText', async () => {
    const page = await newE2EPage();

    await page.setContent('<modus-text-input></modus-text-input>');

    const textInput = await page.find('modus-text-input');
    textInput.setProperty('helperText', 'Helper.');
    await page.waitForChanges();

    const helperLabel = await page.find('modus-text-input >>> label.helper');
    expect(helperLabel).not.toBeNull();
  });

  it('renders changes to includeSearchIcon', async () => {
    const page = await newE2EPage();

    await page.setContent('<modus-text-input></modus-text-input>');

    const textInput = await page.find('modus-text-input');
    textInput.setProperty('includeSearchIcon', 'true');
    await page.waitForChanges();

    const searchIcon = await page.find('modus-text-input >>> svg');
    expect(searchIcon).not.toBeNull();
  });

  it('renders changes to inputmode', async () => {
    const page = await newE2EPage();

    await page.setContent('<modus-text-input></modus-text-input>');

    const textInput = await page.find('modus-text-input');
    textInput.setProperty('inputmode', 'search');
    await page.waitForChanges();

    const input = await page.find('modus-text-input >>> input');
    expect(input.getAttribute('inputmode')).toEqual('search');
  });

  it('renders changes to label', async () => {
    const page = await newE2EPage();

    await page.setContent('<modus-text-input></modus-text-input>');

    const textInput = await page.find('modus-text-input');
    textInput.setProperty('label', 'Hello Label');
    await page.waitForChanges();

    const label = await page.find('modus-text-input >>> .label-container label');
    expect(label.textContent).toEqual('Hello Label');
  });

  it('renders changes to placeholder', async () => {
    const page = await newE2EPage();

    await page.setContent('<modus-text-input></modus-text-input>');

    const textInput = await page.find('modus-text-input');
    textInput.setProperty('placeholder' [...]

2022-11-24 15:16 UTC, coliff commented
thanks @ryan-henness-trimble! I copied and pasted that code and it works.

2022-11-25 07:37 UTC, msankaran0712 requested changes

2022-11-25 07:37 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-text-input/modus-text-input.spec.tsx
> +                    <input class="null" type="text" tabindex="0">
why is it null?

2022-11-25 07:38 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-text-input/modus-text-input.spec.tsx
> +                    <input class="null" type="text" tabindex="0">
In [modus-text-input.spec.tsx](https://github.com/trimble-oss/modus-web-components/pull/868/files/8e424d318e82c6e298de2e729aa1ec2425d35e35#diff-f52c68127f09a17e2cd5a7533feaa7a8e9287d48d3ad4a7d55c91c58ef3ec4b6) I believe the condition should return undefined instead of null when clearable isn't set

2022-11-25 08:06 UTC, coliff commented on stencil-workspace/src/components/modus-text-input/modus-text-input.spec.tsx
> +                    <input class="null" type="text" tabindex="0">
thanks - fixed this. thanks for the suggestion!

2022-11-25 08:20 UTC, msankaran0712 approved these changes

2022-11-25 08:20 UTC, merged