Add Autocomplete
trimble-oss/modus-web-components pull request #971
Opened 2023-01-17 17:44 UTC by ryan-henness-trimble

## Description

Initial `modus-autocomplete` addition.

This component still needs to implement keyboard controls.

Fixes #424 

## Type of change

- [X] New feature (non-breaking change which adds functionality)
- [X] Documentation update

## How Has This Been Tested?

Manually, unit and e2e tests.

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation (including CHANGELOG updates)
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules
- [X] I have checked my code and corrected any misspellings

2023-01-18 11:31 UTC, msankaran0712 commented
hey @coliff @ryan-henness-trimble why is Azure build failing for this PR ?

2023-01-18 11:36 UTC, coliff commented
Because the deploy-preview token doesn't work on forks. It displays the exact error if you click 'Details': https://github.com/trimble-oss/modus-web-components/actions/runs/3942055355/jobs/6745244252

That's why I reconnected Netlify for deploy previews as a quick fix.

2023-01-18 22:02 UTC, ryan-henness-trimble commented
I just want to doublecheck on the `controls` page before adding it - are we sure we want it? It seems it won't add much value since we will only be able to set controls for the text input which has got a controls page already

2023-01-18 23:13 UTC, ryan-henness-trimble commented
- The size of the dropdown menu is slightly smaller than the search text box
  - The `modus-text-input` needed to have a `box-sizing: border-box`, it was overflowing its container.

- A couple of accessibility issues for the last autocomplete example
  - Made the example not required. Not sure how to handle the required elements when they are nested

- In the docs tab, why is there a gap after the 3rd example and the javascript block?
  - The code example seemed to overlap the dropdown, it is not happening anymore so I removed the gap

- Can we enable the controls option in the canvas tab so that we can play around with the examples
  - Controls enabled

2023-01-23 14:38 UTC, msankaran0712 requested changes

2023-01-23 14:38 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
> +  @Listen('click', { target: 'document' })
I strongly feel that we should establish a standard in terms of naming conventions for properties, public methods, events, handlers, etc . and which code block goes where.

2023-01-23 14:38 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
> +            {this.displayOptions() &&
what happens when a user adds value to the prop `options` and also adds slot elements?

2023-01-23 14:38 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
> +                  innerHTML={option.outerHTML}
can't we simply use the slot elements instead of hiding them and creating new `li` elements as we do here?

2023-01-23 14:44 UTC, msankaran0712 commented
Do we support lazy loading? if not we might need a separate issue for that.

2023-01-23 15:01 UTC, msankaran0712 commented
hey @ryan-henness-trimble one last comment,  I think the style guide says options are to be displayed only after the user enters something.

2023-01-23 15:44 UTC, ryan-henness-trimble commented on stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
> +            {this.displayOptions() &&
They both display right now, with the slot elements below the regular options

2023-01-23 15:44 UTC, ryan-henness-trimble commented on stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
> +  @Listen('click', { target: 'document' })
Agreed, are there any here that don't align with what we generally do now?

2023-01-23 15:48 UTC, ryan-henness-trimble commented on stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
> +                  innerHTML={option.outerHTML}
We could but I think having full control over them makes the filtering more intuitive since we can `map` over the `visibleCustomOptions` rather than removing the slots from the DOM

2023-01-23 16:13 UTC, ryan-henness-trimble commented
> @ryan-henness-trimble Do we support lazy loading? if not we might need a separate issue for that.

No lazy loading implemented yet. I'll create a story for that and keyboard controls

2023-01-24 09:38 UTC, msankaran0712 commented on stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
> +  @Listen('click', { target: 'document' })
I guess I have used a different naming convention in the components I created, I can rename those

2023-01-24 09:44 UTC, msankaran0712 commented
@ryan-henness-trimble netlify build is failing

2023-01-24 15:36 UTC, ryan-henness-trimble commented on stencil-workspace/src/components/modus-autocomplete/modus-autocomplete.tsx
> +  @Listen('click', { target: 'document' })
Up to you, I can update them here in this PR too

2023-01-24 15:45 UTC, ryan-henness-trimble commented
@msankaran0712 Netlify is building now. Let me know if you'd like me to update any naming

2023-01-25 06:11 UTC, msankaran0712 approved these changes

2023-01-25 16:39 UTC, merged